modules/aws/etcd/ignition.tf
modules/azure/etcd/ignition.tf
modules/openstack/etcd/ignition.tf

Setting "enable" to false in an Ignition config has no effect since
"disable" is a seperate (and not yet implemented) option.

modules: remove unneeded resources

---

Documentation/platforms/azure/README.md
config.tf
convert.sh

This variable was introduced by mistake early on when comparing the
existing installer and that one: there is a distinction between cluster
name and DNS name on the existing one due to constraint with the
CloudFormation stack naming (policies). However, this does not apply
to this installer specifically as CloudFormation is not used.
Additionally, the cluster name is used everywhere to generate the DNS
records.

config.tf/convert.sh/Documentation: nuke unused tectonic_dns_name var

---

Documentation/variables/config.md
config.tf

The only platform that uses `tectonic_etcd_servers` is AWS, more
specifically the `platforms/aws/etcd` module, which either returns
the list of FQDNs for the provisioned etcd nodes, or that list.
For the output to be consistent, we must return the hostnames/IPs
only. Users of that output expects to format that list to add the
port / scheme as necessary, which is more flexible.

config.tf/Documentation: tectonic_etcd_servers expects hostnames/IPs

---

modules/aws/vpc/outputs.tf
modules/aws/vpc/variables.tf
modules/aws/vpc/vpc-public.tf
modules/aws/vpc/vpc.tf
platforms/aws/main.tf
platforms/aws/variables.tf

BYO VPC slipped through the recent refactoring and wasn't properly tested.  It was not working before these changes.
With these changes clusters CAN now be built into existing VPC and will work as expected.
[The conditional operator always evaluates both branches](https://github.com/hashicorp/hil/issues/50). On one of the branches, the VPC resource may not be present when using an external VPC, because it's count is set to zero. Thus we have to wrap the potentially missing resource in a fake `join()`. Because the expression is now treated like an list of VPC resources, having an empty list is a valid state and the build works as expected.
Hashicorp is aware of the [issue](https://github.com/hashicorp/terraform/issues/11566) and intends to fix it.
This issue also affected @Quentin-M 's …

Fixes for BYO VPC

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md

Add a section that explains where the console is running, and how to access the credentials generated.

docs: add next steps to access Console, kubeconfig

---

modules/aws/vpc/vpc.tf

We were not creating a new VPC when no external VPC ID was specified. The logic is inverted.
The issue could be seen with `data.aws_vpc.cluster_vpc` [describing all](https://github.com/hashicorp/terraform/blob/0b0a76a3d5f13812996207b0268368c694278902/builtin/providers/aws/data_source_aws_vpc.go#L74) the VPCs (`id = ""`) rather than the one we were supposed to create.
```
2017/03/30 13:40:56 [ERROR] root.masters: eval: *terraform.EvalReadDataApply, err: data.aws_vpc.cluster_vpc: multiple VPCs matched; use additional constraints to reduce matches to a single VPC
2017/03/30 13:40:56 [ERROR] root.masters: eval: *terraform.EvalSequence, err: data.aws_vpc.cluster_vpc: multiple VPCs matched; use additional constraints to reduce matches to a single VPC
2017/03/30 13:40:56 [ERROR] root.masters: …
```

modules/aws/vpc: Create VPC if no external VPC is specified

---

platforms/azure/variables.tf

Terraform get was failing due to incorrect syntax:
terraform get platforms/azure
Error loading Terraform: Error loading config: Error parsing platforms/azure/variables.tf: At 36:14: illegal char
Verified with terraform validate:
terraform validate platforms/azure/
Error loading files Error parsing platforms/azure/variables.tf: At 36:14: illegal char

switch : to = to correct syntax

---

modules/tectonic/resources/manifests/config.yaml
modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/resources/manifests/identity/configmap.yaml

This commit removes templated variables from the console deployment. This
allows us to manage the console deployment manifest with operators.

modules/tectonic: stop templating console

---

Documentation/install/azure/azure-terraform.md

Remove references to AWS in Azure docs.

switch AWS names to Azure names

---

Makefile

Terraform comes with a convenient syntax checking and formatting tool which can be used to ensure templates follow canonical syntax rules.
This change introduces two new make targets:
* `structure-check` will be used by the upcoming PR checker to validate canonical syntax
* `canonical-syntax` can be used at any time to align the complete repository to canonical syntax.

Add syntax formatting make targets

---

modules/aws/etcd/outputs.tf

`var.external_endpoints` is a list, so calling `length()` on it will return the number of elements.
No need to `join()` convert it to a string to check emptiness.
@Quentin-M @s-urbaniak

Use same conditional format as in rest of module

---

Dockerfile
Makefile

This change updates the Dockerfile to:
* build terraform from our coreos/terraform fork, to include the custom plugins we use.
* install make and bcrypt-tool in the container image to provide a self-sufficient installer environment.
On top of that, there is a fix for the syntax checking make target to make it work reliably.
These changes allow us to start putting together the Jenkins testing tasks.
@s-urbaniak @Quentin-M

Update Dockerfile and fix syntax checking

---

modules/tectonic/resources/manifests/ingress/hostport/daemonset.yaml
modules/tectonic/resources/manifests/ingress/ingress.yaml
modules/tectonic/resources/manifests/ingress/nodeport/deployment.yaml

- addresses: https://github.com/coreos-inc/tectonic-issues/issues/219.
- Updates ingress controllers to remove default ssl cert.
the cert is satisfied at the ingress resource.
- Adds vhost to ingress resource. Sets ingress class correctly.

update ingress to enable use by others.

---

modules/tectonic/assets.tf
modules/tectonic/resources/manifests/config.yaml

The ingress manifests are templated to inject the FQDN for the console.
Somehow, the variable carrying the FQDN value was also including `https://` before the actual name.
This is incompatible with Ingress manifest syntax and was causing the ingress creation to fail.
This change removes the `https://` prefix from the variable value. Instead, we set it in-line wherever the variable interpolation needs to include it.
@s-urbaniak @squat

Fix FQDNs for console ingress

---

config.tf
modules/aws/ignition/resources/services/kubelet.service
modules/azure/master/ignition-master.tf
modules/azure/master/resources/master-kubelet.service
modules/azure/worker/ignition-worker.tf
modules/azure/worker/resources/worker-kubelet.service
modules/openstack/nodes/ignition.tf
modules/openstack/nodes/resources/kubelet.service

Update the kubelet-wrapper env vars and update node-agent to support new
env vars.
The following environment variables used by kubelet-wrapper have been
deprecated:
KUBELET_VERSION has been replaced with KUBELET_IMAGE_TAG
KUBELET_ACI has replaced with KUBELET_IMAGE_URL
RKT_OPTS has been replaces with RKT_RUN_ARGS
See https://github.com/coreos/coreos-overlay/blob/build-1220/app-admin/kubelet-wrapper/files/kubelet-wrapper#L29-L39.

*: Update kubelet-wrapper env vars and node-agent

---

modules/tectonic/assets.tf
modules/tectonic/resources/manifests/console/service.yaml
modules/tectonic/resources/manifests/ingress/default-backend/configmap.yaml
modules/tectonic/resources/manifests/ingress/default-backend/deployment.yaml
modules/tectonic/resources/manifests/ingress/default-backend/service.yaml
modules/tectonic/resources/manifests/ingress/nodeport/deployment.yaml
modules/tectonic/resources/tectonic-rkt.sh
modules/tectonic/resources/tectonic.service
modules/tectonic/resources/tectonic.sh

This replaces the curl based logic in tectonic.sh with kubectl.
It launches a rkt container using the hyperkube image and applies the
configuration.
It also fixes implicit namespace creation for services which were
created previously in the tectonic-system namespace implicitely.
Fixes #86
/cc @alexsomesan

tectonic: replace curl with kubectl in the install script

---

modules/bootkube/resources/manifests/kube-flannel.yaml
modules/openstack/nodes/secgroup.tf

CNI doesn't set any port explicitely for vxlan, hence it defaults to the
Linux default, which is 8472, see
http://lxr.free-electrons.com/source/drivers/net/vxlan.c#L43.
Setting it to 4789 makes tools like `tcpdump -vv` happily decode encapsulated VXLAN
packets for better debugability.
Also open port 4789 explicitely in Openstack to prevent sporadic communication
problems between nodes.

flannel: use IANA port 4789 for vxlan

---

platforms/openstack/neutron/dns.tf

... since they are not created right now.

openstack/neutron: create A-records

---

config.tf
modules/aws/ignition/ignition.tf
modules/aws/ignition/variables.tf
platforms/aws/main.tf

This introduces a new variable "tectonic_vanilla_k8s" which omits deploying tectonic assets if set to true.
/cc @mxinden @alexsomesan

aws: deploy vanilla k8s cluster

---

Documentation/generic-platform.md
modules/azure/master/ignition-master.tf
modules/azure/master/resources/master-kubelet.service
modules/azure/master/variables.tf
modules/azure/worker/ignition-worker.tf
modules/azure/worker/resources/worker-kubelet.service
modules/azure/worker/variables.tf
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml
modules/bootkube/resources/manifests/pod-checkpoint-installer.yaml
platforms/aws/main.tf
platforms/azure/main.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

To be consistent with other tools in community:
https://github.com/kubernetes/kubeadm/issues/150#issuecomment-280986966
https://github.com/kubernetes/kubernetes/pull/41835
Original discussion: https://github.com/kubernetes/kubernetes/pull/39112
Originally a value of `true` was proposed, but looks like it might be extraneous and other tools (kubeadm, for example) are not populating the value.
/cc @alexsomesan @Quentin-M @aaronlevy

Make node role labels consistent with other probjects

---

modules/bootkube/resources/manifests/kube-apiserver.yaml

This commit changes the `--runtime-config` flags on the apiserver so
that only stable API groups and the RBAC APIs are enabled. in 1.6, RBAC
graduates to beta and we can remove that line as well.

modules/bootkube: disable alpha API groups

---

modules/aws/ignition/resources/services/init-assets.service

WantedBy/Before needs to be in the [Install] section rather than in the
[Unit] section of the systemd unit.
This fixes it.

aws/init-assets: fix systemd dependency

---

config.tf
modules/tectonic/resources/manifests/config.yaml
modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/variables.tf

This change adds the required flags to the console deployment to enable Dex API calls. Also updates dex to v2.3.0

console: Add flags for token revocation in console and update dex.

---

modules/tectonic/assets.tf

PR #231 introduced identity_api_service in
modules/tectonic/resources/manifests/config.yaml but does not propagate
the variable in assets.tf
This fixes it.

modules/tectonic: fix identity_api_service

---

modules/aws/etcd/network.tf
modules/aws/etcd/nodes.tf
modules/aws/etcd/variables.tf
modules/aws/master-asg/elb.tf
modules/aws/master-asg/master.tf
modules/aws/master-asg/variables.tf
modules/aws/vpc/security-groups.tf
modules/aws/vpc/variables.tf
modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf
modules/aws/vpc/vpc.tf
modules/aws/worker-asg/security-groups.tf
modules/aws/worker-asg/variables.tf
modules/aws/worker-asg/worker.tf
platforms/aws/main.tf
platforms/aws/variables.tf
terraform.mk

With the exception of autoscaling groups this allows for custom tags on AWS resources.
The autoscaling group resource is tricky, because it is not a map type, but rather a map of strings to objects which prevents us from using interpolation syntax in the templates.
We are figuring out ways to implement this feature, but it will probably mean introducing a new field to the autoscaling group resource object in terraform.
Fixes #204

aws: allow custom tags for AWS resources

---

modules/azure/master/ignition-master.tf
modules/azure/master/variables.tf
platforms/azure/main.tf

Currently the azure platforms directly invokes bootkube.sh and
tectonic.sh. This fixes it by using the provisioned systemd services.
Fixes #240
Tested successfully on Azure.
/cc @alexsomesan @sozercan @coresolve

modules/azure: use provisioned tectonic and bootkube service

---

config.tf
platforms/aws/main.tf

If tectonic_etcd_count is set, use it. If unset retain the current
behavior to imply the amount of etcd nodes based on the count of
availability zones.
Fixes #213

platforms/aws: respect tectonic_etcd_count variable

---

platforms/aws/terraform.tfvars.example

If you follow the AWS getting started guide, you'll likely hit the
following error because terraform tries to refer to non-existent
VPC resources by default:
$ terraform apply -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws
Error refreshing state: 8 error(s) occurred:
* data.aws_subnet.external_master.2: InvalidSubnetID.NotFound: The subnet ID 'subnet-333333' does not exist
status code: 400, request id: 5bf3c607-4f50-41a0-82f7-38cd0ce162e3
* data.aws_subnet.external_master.0: InvalidSubnetID.NotFound: The subnet ID 'subnet-111111' does not exist
status code: 400, request id: 16c136e8-1492-4607-b935-71c32f35d0eb
* data.aws_subnet.external_master.1: InvalidSubnetID.NotFound: The subnet ID 'subnet-222222' does not exist
status code: 400, request id: …

platforms/aws: by default create the VPC for the user

---

platforms/aws/variables.tf

The minimum value for gp2 IOPS is 100, this updates the default to
reflect this.
Without this, if a user runs terraform plan or apply, it would inform
the user that the volume needs to be recreated due to IOPs changing from
"100" => "0" after the refresh gathers AWS' default value of "100" from
the API.

Update default IOPS for AWS gp2 volumes to 100

---

modules/tectonic/resources/manifests/ingress/default-backend/configmap.yaml

Fix for #165 that broke Azure provided FQDN since host name is too long for nginx ingress controller

Platform/Azure: Add server-name-hash-bucket-size to ingress configmap

---

modules/aws/vpc/existing-vpc.tf
modules/aws/vpc/variables.tf
modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf
platforms/aws/main.tf
platforms/aws/variables.tf

This change allows the VPC module to create subnets in arbitrary subsets of availability zones and using per-subnet custom CIDR ranges.
Resolves #215 and #214 
cc: @s-urbaniak @Quentin-M @sym3tri

AWS: VPC subnets with custom CIDRs and AZs per workers / masters

---

installer/assets/heapster-deployment.yaml
installer/assets/ingress/hostport/nginx-ingress-daemonset.yaml
modules/tectonic/resources/manifests/heapster/deployment.yaml
modules/tectonic/resources/manifests/ingress/hostport/daemonset.yaml

This finishes migrating several tolerations and affinity definitions from annotations to properties in the pod spec.
cc @Quentin-M @aaronlevy

Migrate more manifests to k8s 1,6

---

installer/frontend/platforms.js
installer/server/platforms.go

- Don't require dev mode for terraform in GUI.
- Move AWS Terraform to the top of the dropdown.
- Rename old AWS mode to AWS CloudFormation.

Default to AWS Terraform in GUI installer.

---

installer/frontend/cluster-config.js

Including:
- Storage info (iops, type, size)
- Public/private VPC
- Separate counts for master/worker AZs.
- Add TODOs for the few vars we're not yet passing to the backend.

frontend: Send more tfvars to backend.

---

installer/frontend/components/aws-tf-poweron.jsx
installer/frontend/components/base.jsx
installer/frontend/components/reset-button.jsx

Only show it if terraform isn't running.
This prevents users from getting stuck on the bootup page if terraform apply fails.

frontend: Add reset button on bootup page. 

---

installer/server/terraform.go
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

Because the assets are not meant to live in the executor's working directory forever, we can't use absolute path to them. Otherwise once downloaded, they will not work anymore.
Also, expand any given ~ because it is commonly used by CLI users!
Fixes https://github.com/coreos/tectonic-installer/issues/286 https://github.com/coreos/tectonic-installer/issues/289

Improve paths to license / pull secret

---

modules/aws/ignition/resources/services/kubelet.service

These two were wrong all along.
According to [Kubelet docs](https://kubernetes.io/docs/admin/kubelet/) they should use a hyphen not underscore between words.
cc: @s-urbaniak @Quentin-M @sym3tri

Kubelet arguments should use '-' not '_'

---

config.tf
modules/aws/ignition/ignition.tf
modules/aws/ignition/variables.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver-secret.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/variables.tf
platforms/aws/main.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

This introduces the possibility to configure the etcd CA cert, client
cert, and client key to be used for secure etcd connectivity, if an external etcd is specified.
Todos:
Fixes #233
Fixes #147

[WIP] module/bootkube: support secure external etcd connections

---

.gitignore

The `.terraformrc` is generated automatically and user specific.
It should not amount to SCM changes.
@Quentin-M  @s-urbaniak

Ignore generated .terraformrc

---

Documentation/troubleshooting.md

I'm cleaning up the FAQs and Troubleshooting guides for this release. The only thing I'm going to do to this file before we bring the old Installer files over to this repo is change the title. Just to keep my head straight.

Docs: change title to match standard format

---

installer/scripts/release/common.env.sh
installer/scripts/release/get_terraform_bins.sh
installer/scripts/release/make_release_tarball.sh
installer/server/terraform/sources.go
release.groovy

This PR adds the TerraForm binary, as well as the TerraForm templates to the release binary.
Note that users of the release won't necessarily have to have TerraForm installed on their machine (even though they could), the executor will automatically pick-up the one that is shipped in the release.
```
├── matchbox
│   ├── ...
├── tectonic-installer
│   ├── darwin
│   │   ├── installer
│   │   └── terraform* (upstream)
│   ├── linux
│   │   ├── installer
│   │   └── terraform* (upstream)
│   └── windows
│       ├── installer
│       └── terraform* (upstream)
├── platforms*
│   ├── ...
├── modules*
│    ├── ...
└── config.tf*
*: new
```

installer/scripts: add TerraForm binary/templates to release tarball

---

Makefile

This makes sure that `make destroy` works even we haven't run `make apply`
before.
This is useful when running the `make destroy` directly within a container.

Makefile: Add '${BUILD_DIR}/.terraform' to the dependency of 'make destroy'.

---

installer/scripts/release/make_release_tarball.sh

https://github.com/coreos/tectonic-installer/pull/283#discussion_r113019124 actually broke the release script because the variable contains multiple paths to copy, on purpose. Using quotes makes the script think it should copy one path containing spaces.

installer/scripts/release/make_release_tarball: Revert breaking review

---

Jenkinsfile

Fixes smoke test not knowing CLUSTER during `post`

Expose cluster ID to all smoke tests

---

platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl
platforms/metal/matchers.tf

cc @aaronlevy might simplify your v.1.6.2 bump.

platforms/metal: Template config.tf versions into CL configs

---

installer/scripts/release/common.env.sh
installer/scripts/release/get_terraform_bins.sh
installer/scripts/release/make_release_tarball.sh

- Don't check AWS creds at the start of make_release_tarball.sh.
- Copy local installer binaries to release dir instead of grabbing them from s3.
- Move terraform-specific env vars to get_terraform_bins.sh. They're only used in this one place.
- Use straightforward string interpolation instead of eval() to construct terraform binary URLs.

scripts: Don't require S3 to make a tarball.

---

modules/aws/etcd/nodes.tf
modules/aws/master-asg/master.tf

Currently if a new version of CoreOS comes out on a user's configured
channel after they've already deployed, and they re-run terraform apply,
Terraform will detect the new AMI, and when reconciling desired state,
it will attempt to destroy existing nodes to update the AMI.
In order to avoid this, I added a ignore_changes to both the etcd node
resource, and the master launch configuration resource, to avoid
updating masters/etcd nodes if the AMI changes.
Longer term, I would expect the Container Linux Update Operator, or a
terraform operator could resolve this, but this seems like a reasonable
change to prevent accidental destruction of a cluster.
Previously this change also set prevent_destroy, but that cannot be
parameterized with vars, so it was removed.

Ignore AMI updates on etcd/master nodes to prevent destroying nodes accidently

---

installer/assets/ingress/default-backend-configmap.yaml
modules/tectonic/resources/manifests/ingress/default-backend/configmap.yaml

nginx sends "transfer-encoding: chunked" header, which is blacklisted in http2.
This causes spdy errors in Chrome.

ingress config: Disable http2.

---

modules/aws/etcd/variables.tf
modules/aws/master-asg/variables.tf
modules/aws/worker-asg/variables.tf

Much like #261, these values default should be set to the minimum value
AWS allows rather than leaving it empty, as refreshes detect the
implicit zero value of zero changing to "100" when querying AWS for the
current value.

Set default iops for master, etcd, worker root volumes to 100

---

platforms/metal/cl/coreos-install.yaml.tmpl
platforms/metal/remote.tf

* Disallow SSH as user core during the install to disk
* Increase SSH timeout to 60 minutes to allow leeway
* This prevents terraform from SSH'ing to machines during the install phase so that a single terraform apply is needed to complete the install process.

platforms/metal: Hack to allow a single terraform apply

---

installer/frontend/yarn.lock

Latest yarn creates a slightly different lockfile given the same package.json. This should fix the issue where running `make` modifies yarn.lock.

frontend: Update yarn.lock file. 

---

modules/aws/etcd/nodes.tf
modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

Prevents terraform from recreating the resource when a new CoreOS release
comes out.
This an extension of the same changes done to etcd and masters in #367

Ignore AMI changing on worker launch config

---

config.tf

Replace CoreOS Container Linux Update server default variable `https://public.update.core-os.net` with Tectonic Update server default variable `https://tectonic.update.core-os.net`. This fixes with the issue where updates were not available in Tectonic Console

config.tf - Update Tectonic Update Server Variable

---

README.md

noticed that the link was still pointing to 0.8.8, this just corrects that

change terraform link to 0.9.4

---

installer/glide.lock
installer/glide.yaml

Running `make vendor` (without any glide.yaml changes) was causing vendor diffs. It should be a no-op unless something in glide.yaml is bumped. This should pin the unpinned dependencies based on the current glide.lock.
Run `make vendor` and verify the diff is empty.
```
make vendor
git status
```

glide.yaml: Fix unpinned dependencies in glide.yaml

---

Documentation/dev/audiences.md
README.md

Expanding some thoughts from https://github.com/coreos/tectonic-installer/pull/372 on how we use tools like `make`. They are helpful for developers/contributors but complicate the usage for regular end-users.

Docs: clarify audiences and use-cases

---

modules/aws/vpc/sg-master.tf
modules/aws/vpc/sg-worker.tf

This commit locks down the master and worker security groups for AWS
since we know that etcd pods and control plane pods that need access to
etcd will only be scheduled on master nodes. For that reason, the etcd
ports, 2379-2380 and 12379-12380, only need to accept connections from
other master nodes.
See
https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/util/etcdutil/migrate.go#L132.
cc @sym3tri @Quentin-M

modules/aws/vpc: lock down security groups

---

installer/frontend/components/success.jsx

* Update "kubectl link" to "Configuring credentials" on CoreOS tutorial / doc site for specific steps to download kubectl / kubectl-config in Tectonic Console.
https://coreos.com/tectonic/docs/latest/tutorials/first-app.html#configuring-credentials
* Update "deploy your app" link to "Deploying a simple application" on CoreOS tutorial / doc site
https://coreos.com/tectonic/docs/latest/tutorials/first-app.html#deploying-a-simple-application

Update external links on the last success screen

---

modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf

This fixes an issue @sym3tri noticed. Before this change, the number of NAT gateways created was based on the number of master subnets. This doesn't make sense if the number of worker subnets is lower, since not all NAT gateways will be attached to worker subnets in that case.
With this change, we create as little NAT gateways as needed to support the number of worker subnets attached or to fit in the number of master subnets available (hence the min(..) expression).
@sym3tri @Quentin-M @s-urbaniak

Only create minimum number of NAT gateways needed

---

installer/server/terraform/executor_test.go

The test `TestExecutorSimple` was frequently timing out when the Jenkins executors are overloaded. Extending the timeout to ensure this passes.
/cc @Quentin-M

Extend timeout for terraform apply test

---

Documentation/install/aws/aws-terraform.md
Documentation/install/bare-metal/metal-terraform.md

Specify which version of go should be used. `make build` will fail if not at version 1.8

Documentation/install/aws: specify go version 1.8

---

platforms/metal/cl/bootkube-worker.yaml.tmpl
platforms/metal/matchers.tf

* Problem: In the case a cluster is deployed, various Kubernetes updates are applied over time, and then workers are added by re-using the terraform config to scale workers, the Kubelet version would be out-of-date. This could be done by extending `tectonic_metal_worker_names`, `tectonic_metal_worker_domains`, and `tectonic_metal_worker_macs` and re-applying.
* Start the `kubelet-env.service` to detect the Kubelet version from the bootstrapped control plane to create the kubelet.env file if missing
Note: Adding new controllers in tfvars to try to scale controllers is not supported to begin with on bare-metal (controllers are etcd peers), so launching controllers with version mismatch is not a problem to solve. Controller scaling will come once etcd is run via self-hosted etcd.

platform/metal: Add kubelet-env.service to workers

---

platforms/aws/route53.tf

platforms/aws: apply tags to internal route53 zone

---

modules/tectonic/resources/manifests/ingress/default-backend/configmap.yaml

This was causing a number of bugs in console.
- 400 errors messages were getting captured and un-viewable
- I suspect 401/403 errors were breaking the "you need to login" logic.
/cc @rithujohn191

tectonic: stop capturing 400x errors in default ingress backend

---

modules/bootkube/resources/manifests/kube-apiserver.yaml

Adds audit related flags to the API server manifests for logging to a file in a host volume. I did not update the bootstrap API manifest because it seems unnecessary.
It is expected you would configure fluentd to tail this log file. 
An alternative approach is to make the API server container use `/dev/stdout` as the path to the logfile. This makes it harder and less efficient to configure capturing logs, since the streams will become interleaved, and the API server logs and the audit logs have different formats. This is the simplest approach currently.
If we wish to not use a host mount and not use `/dev/stdout`, then we could avoid it by running a sidecar pod which tails and prints the log file from an empty volume, but then pod restarts will cause some logs to get lost, and isn't …

Configure audit logging for kube-apiserver

---

modules/aws/ignition/ignition.tf
modules/aws/ignition/resources/services/etcd-member.service
modules/aws/ignition/variables.tf
modules/azure/master/ignition-master.tf
modules/azure/master/resources/etcd-member.service
modules/azure/master/variables.tf
modules/azure/worker/ignition-worker.tf
modules/azure/worker/resources/etcd-member.service
modules/azure/worker/variables.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/openstack/nodes/ignition.tf
modules/openstack/nodes/variables.tf
platforms/aws/main.tf
platforms/azure/main.tf
platforms/metal/cl/bootkube-worker.yaml.tmpl
platforms/metal/matchers.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

Hey.
@s-urbaniak could you take a look at the second commit and tell me why this line was the way it was? It seems like you introduced the `127.0.0.1:2379` endpoint in there.
@s-urbaniak @squat From looking on what gets created on AWS, it looks like the security groups regarding to etcd are not too bad? Is there something we need to remove there?

Remove etcd gateway

---

installer/server/terraform.go
installer/server/terraform/executor.go
installer/server/terraform/executor_test.go

Rather than tmp, so users always have the assets somewhere,
regardless of whether they download them or not, and
regardless of potential system reboots.
We should probably have a flag / env variable that controls that,
but we have little time right now. Must switch to doing self-hosted etcd
cleanup for the release now.
Fixes #446

server/terraform: create the executor next to the installer

---

git-version

- bash doesn't always exist in /bin
- Use $() instead of backticks
- Wrap string in double-quotes to prevent globbing/splitting. (see https://github.com/koalaman/shellcheck/wiki/SC2086)
I doubt anyone cares, but this change makes it possible to build & use the tectonic installer on freebsd. (Yes I actually tested this.)

Clean up git-version script.

---

Documentation/install/aws/requirements.md

I think this info should be added to the Tectonic tutorials as well, but I'm not sure where.

Docs: adding AWS S3 credentials info.

---

platforms/metal/matchers.tf

* A merge conflict stripped this required template variable
* I added this in https://github.com/coreos/tectonic-installer/commit/92bb19bb095cf845d7734f1dd34c0d8cf7e9ea56, but I think git clobbered it in https://github.com/coreos/tectonic-installer/commit/1827f92aaf5537bc57e66ea48278fdb969c6e37f

platforms/metal: Fix missing kube_version_image that was stripped

---

installer/Makefile
installer/scripts/release/get_installer_bins.sh
installer/scripts/release/make_release_tarball.sh
installer/scripts/release/upload_installer_bins.sh
installer/scripts/release/upload_release_tarball.sh

The installer doesn't work on windows, so we shouldn't get users' hopes up by giving them a windows binary.

Temporarily remove windows from release binaries.

---

Documentation/admin/index.md
Documentation/admin/logging-customization.md
Documentation/admin/logging-destination.md
Documentation/admin/logging.md
Documentation/files/logging/fluentd-aggregator-deployment.yaml
Documentation/files/logging/fluentd-aggregator-svc.yaml
Documentation/files/logging/fluentd-configmap.yaml
Documentation/files/logging/fluentd-ds.yaml
Documentation/files/logging/fluentd-namespace.yaml
Documentation/files/logging/fluentd-role-binding.yaml
Documentation/files/logging/fluentd-role.yaml
Documentation/files/logging/fluentd-service-account.yaml
Documentation/files/logging/fluentd-svc.yaml
Documentation/files/logging/monitoring/fluentd-prometheus-service-monitor.yaml
Documentation/files/logging/monitoring/prometheus-fluentd-role-binding.yaml
Documentation/files/logging/monitoring/prometheus-fluentd-service-account.yaml
Documentation/files/logging/monitoring/prometheus-fluentd.yaml

Adds manifests for deploying a fluentd based logging stack, along with manifests for enabling prometheus to collect metrics from fluentd.
This document assumes you have somewhere to store logs, such as Elasticsearch, but does not document configuring/setting these services up. It also documents potential other storage destinations, but I haven't tested it using anything other than an Elasticsearch cluster deployed on k8s (using the setup from pires/kubernetes-elasticsearch), that said, changing the backend shouldn't be too difficult.
I haven't written an sort of conclusion section because generally that would be "view your logs in Kibana", but wasn't sure if I should include that, since I'm trying to not assume where your logs are stored too much.
One thing I'm considering is whether I …

Document aggregated logging

---

config.tf
installer/assets/candidate/node-agent.yaml

Adds support for container image caching

installer/assets: Bump node-agent

---

installer/examples/aws-vpc.json

#509 didn't have this test, but it did add a new tfvar to the desired output.

frontend: Fix test that didn't exist when region tfvar PR was merged.

---

platforms/aws/route53.tf

Fixes https://github.com/coreos-inc/tectonic-issues/issues/234.
- Should fix eventual consistency related issues & co.
- Should also fix when LB Services have been created: the records will get removed - but probably not the ELBs tho!

platforms/aws/route53: delete records before deleting the zone

---

modules/aws/etcd/nodes.tf
modules/aws/master-asg/elb.tf
modules/aws/master-asg/master.tf
modules/aws/vpc/sg-elb.tf
modules/aws/vpc/sg-etcd.tf
modules/aws/vpc/sg-master.tf
modules/aws/vpc/sg-worker.tf
modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf
modules/aws/vpc/vpc.tf
modules/aws/worker-asg/worker.tf
modules/azure/master/master.tf
modules/azure/vnet/security-groups.tf
modules/azure/vnet/virtualnet.tf

modules/aws,azure: use the new tag format for k8s 1.6

---

installer/assets/self-hosted/kube-apiserver.yaml.tmpl
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-flannel.yaml
modules/bootkube/resources/manifests/kube-proxy.yaml
modules/bootkube/resources/manifests/pod-checkpointer.yaml
modules/tectonic/resources/manifests/ingress/hostport/daemonset.yaml
modules/tectonic/resources/manifests/monitoring/node-exporter-ds.yaml
modules/tectonic/resources/manifests/updater/node-agent.yaml

New KVO uses upstream DS rolling updates, and so now we need to specifiy
the correct strategy.

*: Add RollingUpdate strategy to DS manifests

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx

Also, fix bug where auto-scrolling did not occur at the start of terraform apply/destory.

frontend: Scroll only if user is scrolled to the bottom of logs.

---

installer/server/defaults/defaults.go
installer/server/terraform.go

server: Calculate tectonic_kube_etcd_service_ip from service CIDR.

---

platforms/metal/tectonic.tf

Fixes https://github.com/coreos-inc/tectonic-issues/issues/240
Regression introduced in #468

Define master_count so that baremetal works again. Broken by PR #468.

---

Jenkinsfile

Jenkins executors were filling up with files in build workspaces causing jobs to fail. This cleans the workspace after each execution regardless of success or failure.
Since don't currently perform any caching this should not affect build time.

Clean workspace after build

---

Documentation/variables/azure.md
examples/terraform.tfvars.azure
modules/azure/dns/etcd.tf
modules/azure/dns/main.tf
modules/azure/dns/master.tf
modules/azure/dns/variables.tf
modules/azure/etcd/lb.tf
modules/azure/master/api-lb.tf
modules/azure/master/console-lb.tf
modules/azure/master/output.tf
platforms/azure/dns-todo/worker.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/azure/variables.tf

This PR amends https://github.com/coreos/tectonic-installer/pull/374 to:
- Cleanup the public_ips & master FQDN's from using long and incorrect FQDN's e.g. when using an existing DNS zone resource group
- Rename `tectonic_azure_create_dns_zone` to `tectonic_azure_use_custom_fqdn` to convey its functionality better around which FQDN's is used: either 1) custom FQDN that uses `tectonic_base_domain` (default) or 2) the [FQDN](https://www.terraform.io/docs/providers/azurerm/r/public_ip.html#fqdn) set up by Azure.
- Update Azure's `etcd_service_ip` in the bootkube module (similar to recent changes for AWS: https://github.com/coreos/tectonic-installer/pull/411)
This has been tested against Terraform v0.9.4 (since it's now the [default](https://github.com/coreos/tectonic-installer/pull/219) in …

platforms/azure: fix the usage of an existing DNS zone resource group

---

Jenkinsfile

Moved the cluster destruction invocation the `post` section of the Jenkinsfile which ensures that cluster cleanup regardless of build status.

Always destroy clusters after smoke

---

Documentation/install/bare-metal/metal-terraform.md

If the key is not in the ssh-agent, Terraform won't be able to SSH into the nodes and proceed. This is quite difficult to diagnose because there is no log whatsoever if the DEBUG logs were not enabled. At least, have this mentioned in the documentation once..

Documentation/install/bare-metal: Document ssh-agent requirement

---

installer/Makefile
installer/frontend/Makefile

- Add front-end js as a dependency for binassets.
- Add `make dist` rule to download & create a tarball. (but not upload a release)
- Fix path of frontend assets in `make clean`
- Make all go files a dependency for installer binaries.
- Make all js files a dependency for `yarn build`
- Make `package.json` & `yarn.lock` dependencies for `yarn install`
Fixes multiple issues, such as:
- `make` rebuilt js even if no js code changed
- `make` didn't bundle changed js (had to run `make clean && make` to get new js bundled)
- `make clean` didn't `rm app-bundle.js`
- `make clean` didn't `rm .workspace` (used for making release)
Fixes issue #528, where make didn't bundle changed js. 
This still rebuilds some go stuff if you run `make`, but it's much better than the current behavior (which rebuilds …

Improve Makefiles

---

modules/bootkube/outputs.tf
platforms/aws/tectonic.tf

Just recognized while testing bare metal, that module.bootkube.content_hash is redundant with module.bootkube.id.
This fixes it.
/cc @alexsomesan

bootkube: remove redundant content_hash variable

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx

Implement some of the stuff in latest mocks for the poweron page.
- Add spacer between "show logs" & "save log"
- Hide destroy/reapply buttons unless terraform is finished.
- Show useful messages upon tf success/failure.
Here's what it looks like:
Ignore the logs in this first screenshot. They're from the output of a successful tf destroy.

frontend: Clean up styling of poweron page.

---

Documentation/install/aws/uninstall.md

remove CF references
Add steps for terraform destroy using the provided tools and config
from installer or assets.zip.
(does not include CLI User-level instructions update in each of the *-terraform.md docs.)

Doc/install/aws/uninstall: Describe CLI destroy of GUI-made cluster

---

config.tf

Shows CLUO section on cluster settings page even if experimental operators are not installed.

config.tf: Bumps console to v1.5.5

---

Jenkinsfile
installer/tests/sanity/k8s_test.go

The pull secret and license had been swapped in the Jenkinsfile causing Tectonic resources to not be created since the pull secret was missing.
Also enabled Pod logging test since the cause of it's failures should be this issue.

Fix license and pull secret / reenable Pod logging test

---

installer/frontend/components/aws-vpc.jsx

If user hasn't entered a subdomain yet, populate the field with the cluster name.

frontend: Default subdomain to cluster name.

---

modules/tectonic/resources/manifests/monitoring/node-exporter-ds.yaml
modules/tectonic/resources/manifests/monitoring/node-exporter-svc.yaml
modules/tectonic/resources/manifests/monitoring/prometheus-k8s-service-monitor-k8s-apps-http.yaml
modules/tectonic/resources/manifests/monitoring/prometheus-k8s-service-monitor-kubelet.yaml
modules/tectonic/resources/manifests/monitoring/prometheus-k8s.yaml
modules/tectonic/resources/manifests/monitoring/prometheus-operator.yaml

Revert any labels changes to the monitoring assets made in PR:  https://github.com/coreos/tectonic-installer/pull/517
Fixes: https://github.com/coreos/tectonic-installer/issues/576
@brancz @fabxc @aaronlevy

modules/.../monitoring: revert label changes

---

modules/tectonic/crypto.tf

if a cert doesn’t contain subjectAltNames Chrome >=58 and future
versions of Firefox will give a `NET::ERR_CERT_COMMON_NAME_INVALID`
error even if the CA is trusted and the CN matches.
currently the generated CSR only contain a subject CN.  this change
adds a matching subjectAltName to the ingress cert signing request.

ingress tls_cert_request: add subjectAltName

---

installer/tests/sanity/k8s_test.go

Smoke tests have been failing because of API server errors listing Pods while waiting for them all to be ready. This seemed to happen after fixing deploying Tectonic components, since these components get deployed during the test potentially the extra load increases the number of failures. 
This change makes the Pod status check tolerant of Pod listing failure during the check. Any failures will be logged in the test.
If we see frequent API server failures logged we should determine if there is a regression.

Tolerate API errors while waiting for Pods to be ready

---

installer/frontend/components/alert.jsx
installer/frontend/components/tf-poweron.jsx

frontend: Move terraform-related buttons & errors next to terraform step

---

config.tf

Fixes
- https://github.com/coreos-inc/tectonic-issues/issues/246
- https://github.com/coreos/tectonic-installer/issues/617

config: Bumps console to v1.5.6

---

builder-run
installer/scripts/release/make_github_release.sh

Ran into some issues whey trying to cut a release. Details are in the comments.

Release script fixes

---

Documentation/install/aws/index.md

@coresolve 
*note* there will be a hotpatch for the docs on coreos.com for this so it gets fixed before the next release.

Docs: bump aws download installer url.

---

Makefile

Always invoke [terraform get](https://www.terraform.io/docs/commands/get.html) in order to ensure that necessary modules are installed, to avoid build errors, rather than relying on whether the .terraform directory exists, since it might be stale.
See #571 for reference.

Always invoke terraform get

---

platforms/openstack/neutron/nodes.tf
platforms/openstack/nova/nodes.tf

The tectonic_vanilla_k8s flag was previously defined, but not
actually used. Conditionally deploy Tectonic assets based
on the value of this flag.
See also: #607 #194

platforms/openstack: Use tectonic_vanilla_k8s flag

---

examples/terraform.tfvars.azure
modules/azure/dns/etcd.tf
modules/azure/dns/main.tf
modules/azure/dns/master.tf
modules/azure/dns/variables.tf
modules/azure/master/output.tf
modules/azure/master/variables.tf
platforms/azure/dns-todo/worker.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/azure/variables.tf

This PR:
- cleans up the conditional construction of the FQDN's to only occur in the module outputs.
- ensures that the outputs won't use the `base_domain` if `use_custom_fqdn` is not requested, and instead rely on the FQDN Azure sets up.
- removes duplicate `master_count = "${var.tectonic_master_count}"` introduced in https://github.com/coreos/tectonic-installer/pull/557

modules/azure: refactor FQDN conditionals and their usage

---

platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/matchers.tf
platforms/metal/remote.tf

Setting `tectonic_vanilla_k8s` to `true` now correctly omits the tectonic systemd unit.
Follows https://github.com/coreos/tectonic-installer/pull/194

metal: implement tectonic_vanilla_k8s

---

images/tectonic-builder/Dockerfile
installer/Makefile
installer/scripts/license-gen/collect_project_licenses.sh
installer/scripts/license-gen/licenses/all_licenses.json
installer/scripts/license-gen/pkg_lists/go_pkg_inputs.txt
installer/scripts/license-gen/pkg_lists/js_pkg_inputs.txt

**PR details**: `collect_project_licenses.sh` downloads all dependencies of projects [listed](https://docs.google.com/spreadsheets/d/1gJIAHgEB8Av1gFNWznsx0nI_GHAEoN4gsiOc1NskJNc/edit#gid=0) which have 'Needs license info' == 'yes', finds their license info, and aggregates JSON output into a single list in a file. Go dependency licenses collected using [license-bill-of-materials](https://github.com/coreos/license-bill-of-materials); JS dependency license info collected using `package.json` files post-installation.
**Tests**: I tested the script locally. Will run in any environment that has Go, `yarn`, `jq`, and the `license-bill-of-materials` binary installed.
**Sample output**:
```
[
{
"project": "github.com/docker/distribution",
"licenses": [
{
"type": "Apache License 2.0",
"confidence": …
```

License collection

---

installer/api/api.go

Method should be GET, not POST. Bug introduced in #325.

Make download assets work again. 

---

Documentation/variables/openstack-nova.md
examples/terraform.tfvars.openstack-nova
platforms/openstack/nova/nodes.tf
platforms/openstack/nova/variables.tf

Add a default network to compute nodes. This variable
must be explicitly specified if more than one network
is available to choose from, or the node creation will fail.

platforms/openstack/nova: Add default network

---

modules/openstack/nodes/secgroup.tf

Kubernetes uses port 10250 to retreive logs.
`kubectl logs …` will fail with a timeout if this port is blocked.

modules/openstack: Add port 10250 to security group

---

installer/api/handlers_frontend.go

Server: Don't add an extra newline to logs about serving local files.

---

platforms/metal/cl/bootkube-controller.yaml.tmpl

Release notes say "Segregates control-plane / user workloads to master / worker nodes respectively", so you do need this taint on the controller kubelet.
https://github.com/coreos/matchbox/pull/528

platforms/metal: Add NoSchedule taint to controllers

---

modules/aws/etcd/dns.tf

Currently only one A-record for etcd nodes is being created.
This fixes it by considering the instance count of created etcd nodes.

modules/aws: create correct count of etcd a-records

---

modules/aws/ignition/resources/init-assets.sh
modules/bootkube/assets.tf
modules/bootkube/resources/bootkube.sh

Currently, attempting a `plan` immediately after a successfull `apply` falsely reports that changes are still necessary. A subsequent `apply` for these supposed changes leads to other changes being reported by further `plans`. A vicious circle is created.
This is caused by a previous change to support optional manifests which renders additional manifests into the output location of a `template_dir` resource. Because `template_dir` checksums the contents of this location to determine if changes are necessary, it leads to above mentioned behaviour.
This fix avoids rendering the optional manifests into the location checksummed by `template_dir`. Consequently, calling `plan` or `apply` after a successful build reports no changes necessary.
/cc: @sym3tri

Fix idempotency for plan / apply: don't render optional manifests into template_dir outputs

---

installer/glide.lock
installer/glide.yaml
installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/matchbox.go
installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/provider.go

* Update terraform-provider-matchbox from v0.1.0 to v0.1.2. See release notes https://github.com/coreos/terraform-provider-matchbox/releases
* Also pin crypto package which was unpinned and causing glide update to fail. No diff in vendor from that.
Closes #712

installer/vendor: Update terraform-provider-matchbox to v0.1.2

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
examples/terraform.tfvars.openstack-nova
platforms/aws/main.tf
platforms/aws/variables.tf
test/aws.tfvars

This change follows up on cleanup due after moving to Terraform 0.9.x
In 0.8.x we had a limitation of not being able to reference data-sources as values for `count` attributes.
The `tectonic_aws_az_count` was working around this by asking the user to fill in the number of AZs.
This was fixed in 0.9.x and we can now pick those up from a datasource.
With this change we make it simpler for users to choose between auto-computed subnets or explicitly set ones. We also have one less input variable to care for.
/cc: @sym3tri

Remove the tectonic_aws_az_count input variable

---

modules/openstack/etcd/output.tf
modules/openstack/nodes/output.tf
platforms/openstack/neutron/network.tf
platforms/openstack/neutron/nodes.tf

When assigning neutron ports, the `security_groups` attribute is ignored on
`openstack_compute_instance_v2`. Apply all the security groups by id on the
`openstack_networking_port_v2` instead. Also create a specific port for etcd
nodes for consistency with the controllers and nodes.

openstack/neutron: Fix security groups

---

platforms/openstack/neutron/nodes.tf

openstack_compute_floatingip_associate_v2.worker was incorrrectly using the
tectonic_master_count instead of the tectonic_worker_count

openstack/neutron: Fix worker floating IP association

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.openstack-nova
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

Currently both variables need to be set even if tectonic_vanilla_k8s is
set to true.
This fixes it.
Fixes #133

config.tf: pull_secret_path and license_path optional

---

modules/aws/master-asg/elb.tf

modules/aws: configure ELB idle timeout

---

Documentation/admin/workload-separation.md

Sub note that provides clarity on the meaning on _n_ in workload separation chart.

docs: clarify 'n' in workload separation table

---

Jenkinsfile
installer/scripts/filter.sh

This uses a very rough heurestic (string length) to remove credentials from log output. This is a requirement for opening log output up to the public.
cc/ @philips

Filter logs for credentials

---

installer/Makefile

This PR for updates the Makefile for the installer to always pass `-i` when performing a Go build. This will cause the build to be cached in `$GOPATH/pkg` and will speed up future builds.

Always cache go builds with -i

---

platforms/metal/cl/bootkube-worker.yaml.tmpl

* kubelet-env starts and docker creates missing directories so
it could create a directory /etc/kubernetes/kubeconfig
* Terraform races with kubelet-env can if it runs after docker
has run once, the kubeconfig will erroneously be placed in a
directory /etc/kubernetes/kuebconfig/kubeconfig
Impact is that under the right (wrong) circumstances, no workers will join the cluster.
cc @sym3tri

platforms/metal: Fix race condition adding workers

---

platforms/aws/s3.tf

We use cluster names for generating bucket names with the region and domain.
However, buckets must start with a lower case letter and are restricted to 63 chars,
so this commit prepends the letter 'a' and md5s the region name and domain.  It also switches dashes for dots as the delimitter because double dashes are allowed but dashes next to dots are not.

cluster names/bucket names

---

modules/bootkube/resources/experimental/manifests/etcd-operator.yaml

All system components are sitting on master nodes.
However, etcd operator was somehow dismissed for that.

manifests: etcd operator pod should select master nodes

---

test/aws.tfvars

The error when destroying:
aws_launch_configuration.worker_conf: Refreshing state... (ID: testgg2-worker-003aca4fa6abcc68ade1a21132)
aws_autoscaling_group.workers: Refreshing state... (ID: testgg2-workers)
Error refreshing state: 2 error(s) occurred:
* module.etcd.data.ignition_config.etcd[1]: index 1 out of range for list data.ignition_systemd_unit.etcd3.*.id (max 1) in:
${data.ignition_systemd_unit.etcd3.*.id[count.index]}
* module.etcd.data.ignition_config.etcd[2]: index 2 out of range for list data.ignition_file.node_hostname.*.id (max 1) in:
${data.ignition_file.node_hostname.*.id[count.index]}
Looks like the real bug is in https://github.com/coreos/tectonic-installer/blob/master/modules/aws/etcd/ignition.tf but stuff is broken now so let's work around the issue to get tests working …

Jenkins tests: Don't set tectonic_etcd_count to 3, as that currently breaks tf destroy.

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.openstack-nova
modules/bootkube/assets.tf
modules/bootkube/assets_tls.tf
modules/bootkube/outputs.tf
modules/bootkube/variables.tf
platforms/aws/main.tf
platforms/aws/tectonic.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/metal/matchers.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

*/config: compute service k8s IPs

---

Documentation/variables/azure.md
examples/terraform.tfvars.azure
modules/azure/dns/etcd.tf
modules/azure/dns/main.tf
modules/azure/dns/master.tf
modules/azure/dns/variables.tf
modules/azure/master/variables.tf
platforms/azure/dns-todo/worker.tf
platforms/azure/main.tf
platforms/azure/variables.tf

This PR fixes the following issues introduced in https://github.com/coreos/tectonic-installer/pull/417 and https://github.com/coreos/tectonic-installer/pull/602, which replaced `create_dns_zone` with `use_custom_fqdn` and changed the default value of `use_custom_fqdn`:
- If `use_custom_fqdn` was `false` a DNS Zone would not be created
- If `user_custom_fqdn` was `true`, which was the default, it would destroy an existing DNS zone whether the user intended it or not, as it took the place of `create_dns_zone` in the logic of the DNS module.
This PR restores `create_dns_zone` and limits its use to the DNS module, and limits `use_custom_fqdn` to the Master module, creating the ability to configure both if desired, and separating the use cases out as independent variables.

azure: restore create_dns_zone and make use_custom_fqdn optional

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
platforms/aws/main.tf
platforms/aws/variables.tf

This allows users to add additional security groups to nodes on AWS. My specific use-case is that I have a `base` security group managed outside the Tectonic config which allows SSH from bastion hosts among other things.

platforms/aws: Support additional security groups

---

Documentation/troubleshooting/workstation-etcd-api-server-restore.md

Running a local Kubernetes API server on a local workstation based on an etcd snapshot can be useful for debugging, and understanding database backups. In a few simple steps this can be accomplished on Windows, Linux, or OSX.

Documentations: troubleshooting: add a workstation restore guide

---

config.tf

Enforces signing of payloads, see:
https://github.com/coreos-inc/tectonic-channel-operator/releases/tag/0.3.3
cc @marineam @yifan-gu @aaronlevy @derekparker 
Fixes #831

Update TCO version to 0.3.3

---

platforms/openstack/neutron/dns.tf
platforms/openstack/nova/dns.tf

Only create a DNS record for the Tectonic console if
tectonic_vanilla_k8s=false.

platforms/openstack: Don’t create console DNS on vanilla

---

modules/openstack/etcd/ignition.tf
modules/openstack/etcd/secgroup.tf
modules/openstack/etcd/variables.tf
modules/openstack/nodes/output.tf
modules/openstack/nodes/secgroup.tf
modules/openstack/nodes/variables.tf
platforms/openstack/nova/dns.tf
platforms/openstack/nova/main.tf
platforms/openstack/nova/nodes.tf

- Plumb tectonic_experimental flag through to openstack/nova
to conditionally enable self-hosted etcd
- Update security groups with conditional logic for self-hosted
and external etcd clusters
- Conditionally disable etcd DNS entries for self-hosted mode

*/openstack/nova: Add support for self-hosted etcd

---

modules/aws/ignition/resources/services/kubelet-env.service

Bind the /etc/kubernetes dir so the kube-env doesn't create
the host path if it happens to run before /etc/kubernetes/kubeconfig
is placed by terraform.
Same as https://github.com/coreos/tectonic-installer/pull/722

modules/aws: Fix kube-env race condition for aws platform.

---

Jenkinsfile
Makefile

This PR adds an example and a docs stage to our Jenkins build pipeline. It first runs the respective targets and then checks if anything changed.
@s-urbaniak Let me know what you think.
Is there a way to force make to run a target to prevent `make: Nothing to be done for 'examples'.`?

test: Run make {examples,docs} and check for changes

---

modules/tectonic/resources/manifests/monitoring/prometheus-k8s-rules.yaml

This is syncing the changes from https://github.com/coreos-inc/tectonic-prometheus-operator/pull/58 this repo. For the sake of comprehensibility I'll quote the description from there here:
On @rithujohn191's request we are adding recording rules for the container CPU usage in addition to the already existing CPU requests/spec recording rule.
While these recording rules are not strictly necessary for console to query this data it will improve the performance when querying, as recording rules pre-calculate and store the calculated values in an extra time-series.
These added recording rules return CPU usage in its base units, so 1.0 is using one entire core. It is best practice in Prometheus to use base units, so note that when using this metric you may need to query something like the …

monitoring: add cpu usage recording rules

---

modules/bootkube/assets.tf
modules/bootkube/assets_tls.tf
modules/tectonic/assets.tf
modules/update-payload/assets.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/remote.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/nodes.tf
platforms/openstack/nova/nodes.tf

The use of the `path.cwd` everywhere results in local paths being stored
in the state.  This causes noisy, false, diffs when working in a team
setting or via an automated deployment system.  Just using `.` should
have the same effect while keeping the paths in the state relative.

Replace all occurences of path.cwd

---

modules/bootkube/resources/manifests/pod-checkpointer.yaml

By convention it should match the name of the daemonset.
Fixes #848

Fix the pod-checkpointer container name.

---

README.md

This link doesn't work and until we can filter all of the secrets out
of stdout it is pointless to include it.

README: remove link to jenkins

---

installer/frontend/cluster-config.js
installer/frontend/components/aws-vpc.jsx

Some copy and styling changes for the tectonic_aws_external_private_zone switch.  Please suggest changes.

frontend: split-dns-copy

---

modules/bootkube/resources/experimental/manifests/etcd-operator.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml
modules/tectonic/resources/manifests/identity/deployment.yaml
modules/tectonic/resources/manifests/monitoring/prometheus-operator.yaml
modules/tectonic/resources/manifests/stats-emitter.yaml
modules/tectonic/resources/manifests/updater/kube-version-operator.yaml
modules/tectonic/resources/manifests/updater/tectonic-channel-operator.yaml
modules/tectonic/resources/manifests/updater/tectonic-prometheus-operator.yaml

Affected components:
- Controller Manager
- Scheduler
- Stats
- KVO
- TCO
- Tectonic Prometheus Operator
Not updated:
- DNS
- Prometheus
- Tectonic etcd Operator
- CLUO (Operator, not agent)
Partially addresses #749.

Change many components to run as user 'nobody'.

---

modules/bootkube/resources/manifests/pod-checkpointer.yaml

This change is causing daemonset upgrade problems that we need to debug
further. It may be a kubelet issue. Since this change is not strictly
required we should back it out completely for now.
See #848 for more details.

Revert "Fix the pod-checkpointer container name. (#844)"

---

installer/frontend/components/make-node-form.jsx

Default to booting a HA cluster with 3 masters, 3 workers, and (unless experimental) 3 etcds.
Fixes #457.

frontend: Default to 3 nodes for AWS masters & workers.

---

Jenkinsfile
test/aws-exp.tfvars
test/scripts/aws-destroy.sh
test/scripts/aws.sh

Our smoke tests failed to catch a regression with one of the
experimental features because the smoke tests do not enable
`tectonic_experimental`. This PR does two things:
1. it adds a parallel step to the tests that runs with the experimental features enabled.
2. it moves the inline jenkins test code to its own file.

Jenkinsfile: test experimental features

---

Documentation/troubleshooting/troubleshooting.md

Previous content on this page was redundant with worker-nodes.md. Changing this page to an index for the folder to allow for proliferation of troubleshooting guides within it.

docs: Changing page to folder index.

---

Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md

Point release bump. Nothing urgent if you want to bump for this release or the next one.
https://github.com/coreos/matchbox/releases/tag/v0.6.1

Documentation: Reference matchbox v0.6.1 release

---

installer/Makefile

It is exported everywhere. Also, use standard export syntax without colon. It's confusing otherwise.

Makefile: Remove extraneous CGO_ENABLED=0

---

platforms/openstack/neutron/network.tf

Update the security group variables to reference the correct
ids now that there are separate master/node security groups.
Broken by https://github.com/coreos/tectonic-installer/pull/825

platforms/openstack/neutron: Fix security group id

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

It doesn't contribute anything and leads to unnecessary apiserver
restarts during the bootstrap process.

Remove flock timeout from apiserver.

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

Reverts coreos/tectonic-installer#915
As per discussion in https://github.com/coreos/tectonic-installer/pull/915#issuecomment-304720940 this was supposed to get in post-1.6.4.

Revert "Remove flock timeout from apiserver."

---

modules/aws/etcd/nodes.tf
modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

I noticed that after successfully applying the templates from master, any subsequent `plan` operation will show that changes are required to update the value of the IOPS attribute in the block device mapping of the ASG launch configuration.
The reason for this is that during a previous apply, for a device type other than IO1 setting IOPS will just ignore the value. When doing a plan later on, the previously set value will not be returned by the AWS API, and so Terraform assumes that it has diverged and attempts to update it.
With this change we only attempt to set the actual IOPS value on volumes of type IO1, while for everything else we pass 0, which is the neutral value for this attribute. This avoids the perceived divergence and will not signal required changes later on.

Idempotency fix: don't set IOPS value unless device type is IO1

---

installer/frontend/fields.js

Related to #919, #914, & #920.

frontend: Restrict AWS cluster names to 19 chars and all lowercase.

---

test/scripts/aws-common.sh
test/scripts/aws-destroy.sh
test/scripts/aws.sh

- Reduce duplicated code by moving common stuff to aws-common.sh
- Truncate or append to cluster name if name is too short or too long
- Set max cluster name length to 19 chars (max length that currently works)
We need this to prevent regressions, because people keep appending characters to the cluster name when creating other aws resources (elbs, s3 buckets, etc).

Test with a max length cluster name.

---

modules/aws/ignition/ignition.tf
modules/azure/master/ignition-master.tf
modules/azure/worker/ignition-worker.tf
modules/openstack/nodes/ignition.tf

- 555 should be 755.
- 420 translates to 644.
- If octal is being used it should be prefixed by 0.
- Quotes are unnecessary.

Fix incorrect file modes.

---

Jenkinsfile

This should give us more insight about where time is spent when bringing up & testing a cluster.

Enable timestamps for Jenkins output

---

installer/frontend/fields.js
modules/aws/master-asg/elb.tf
tests/smoke/aws/smoke.sh

Commit on top of #914.
Once this test passes, https://github.com/coreos/tectonic-installer/issues/413 will be fixed.

Test with long cluster names (28 chars)

---

Jenkinsfile

Paired with @kans.
- Don't repeat withCredentials args three times, [one of which was incorrect](https://github.com/coreos/tectonic-installer/commit/ff3c92ba79e2b5c10d05b6b89a98acf936bf4bd3#commitcomment-22354809).
- TF Destroy is part of blue ocean console output. (Previously, it was hidden.)
- Don't re-run tf destroy if build or lint fails.
- Set more fine-grained timeouts for various steps.
- Don't needlessly checkout scm again when destroying.
- Lastly: fix indentation.

Jenkins cleanup

---

modules/aws/ignition/resources/detect-master.sh

- Retry fetching region & instance ID.
- Avoid false positive comparisons that could potentially cause a node to think it's the first master when it isn't.
- Wrap some fields in quotes to prevent potential issues with globbing.

Make detect-master.sh more robust.

---

modules/aws/master-asg/elb.tf

This avoids having the API servers’ logs being hammered with:
```
http: TLS handshake error from 10.0.44.6:28942: EOF
```
Fixes https://github.com/coreos/tectonic-installer/issues/893.

modules/aws/master-asg: switch ELBs’ health checks to using SSL targets

---

modules/aws/master-asg/master.tf

Give masters access to s3:HeadObject to avoid 403 when key doesn't exist
within bucket (due to s3 propagation delays, details below).
Reasons for this are: @diegs and I were troubleshooting his cluster not coming up. We found the masters had a failed `init-assets.service`, logs gave us a 403 Permission Denied error on `aws s3 cp` for `HeadObject`. It turns out you get a 403 if a object's key (which is a file or directory) doesn't exist, and you don't have permissions to ListBucket/HeadObject, as mentioned in  mentioned in https://github.com/aws/aws-cli/issues/1689 and documented in https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html#rest-object-head-permissions
It's pretty hard to reproduce, as it seems to be due to the eventual consistency model in S3. This specific case …

Provide masters access to s3:HeadObject and s3:ListBucket

---

modules/bootkube/assets.tf

This allows for bootstrapping to work with smaller service CIDRs.
See also: https://github.com/kubernetes-incubator/bootkube/issues/531
cc @dghubble @brianredbeard

Change bootstrap etcd service port to 20.

---

Jenkinsfile
tests/smoke/aws/smoke.sh

We want to ensure that our smoke tests run with limited privileges so we
can catch when a change adds a dependency on a new privilege.
@ggreer @Quentin-M

Jenkinsfile,tests/smoke: assume minimum role

---

modules/bootkube/resources/experimental/manifests/etcd-operator.yaml

Fixes https://github.com/coreos/tectonic-installer/issues/959.
See issue for details.

modules/bootkube: fix etcd-operator startup with S3 backups and nobody

---

platforms/azure/tectonic.tf
platforms/vmware/remote.tf

The tectonic_vanilla_k8s flag was previously defined, but not
actually used. Conditionally deploy Tectonic assets based
on the value of this flag.
Related: #637 
Fixes: #960

platforms/*: Use tectonic_vanilla_k8s flag

---

Jenkinsfile
images/tectonic-installer/Dockerfile
images/tectonic-installer/README.md

Add stage to build docker image containing compiled binaries.
> We are already compiling the installer in the CI pipeline of the
Tectonic installer. I would propose building a Docker image with
terraform and the compiled binaries as a step of the pipeline so anyone
can just go ahead and start her cluster without any dependencies by
using the quay.io/coreos/tectonic-installer-dev:master image.
In addition, this specifies a Docker image per stage, and not per entire pipeline.
Fixes #689

Build docker image

---

installer/frontend/components/aws-cloud-credentials.jsx

This prevents us from hitting the AWS API every time these fields are changed.

frontend: Validate lengths of AWS key/secret.

---

tests/smoke/aws/README.md
tests/smoke/aws/smoke.sh

Now that smoke tests are run with a limited role, we need to simplify
how we update the policies for that role in the event that the
privileges needed to run the Tectonic installer grow or shrink. This
commit introduces a `set-role` command in the `smoke.sh` script for that
purpose and documents the use of the tool in a README.
fixes: #1001 
cc @sym3tri @ggreer

tests/smoke/aws: simplify updating test policy

---

modules/aws/ignition/resources/services/kubelet.service
modules/azure/master/resources/master-kubelet.service
modules/azure/worker/resources/worker-kubelet.service
modules/openstack/nodes/resources/kubelet.service
modules/vmware/node/resources/services/kubelet.service

Otherwise the uuid file won't survive the reboot which makes `rkt rm --uuid=` useless.
Xref: https://github.com/kubernetes-incubator/bootkube/pull/562

modules/*: Update kubelet.service to save kubelet pod uuid in less volatile location

---

modules/tectonic/resources/tectonic.sh

Currently, if wait_for_tpr fails, whole `tectonic.sh` fails. This fixes
it.

modules/tectonic: don't exit on failure in wait_for_tpr

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/node/nodes.tf
platforms/vmware/remote.tf
platforms/vmware/variables.tf

Follow up on https://github.com/coreos/tectonic-installer/pull/625 for VMware platform.
Allow users to specify the SSH private key via a variable in cases where
ssh-agent isn't available or configured.

vmware: add tectonic_vmware_ssh_private_key variable

---

Makefile
tests/smoke/aws/smoke.sh

Example tfvars for each platform are located in the examples
folder. Automatically copy and rename this file matching the
specified platform for `make localconfig`
Fixes #923

Makefile: automatically create tfvars file for specified platform

---

git-version

This is a very small improvement to what we have. Instead of putting the build artifacts with the tag if available, we will always include the commit as well, thus hinting if someone weird happened..

git-version: always use commit as part of the version

---

modules/vmware/node/ignition.tf

Change permissions of `/etc/sysctl.d/max-user-watches.conf` and `/etc/kubernetes/kubelet.env` similar to https://github.com/coreos/tectonic-installer/pull/936

vmware: Fix incorrect file modes

---

Jenkinsfile

```
20:25:09 [TerraForm: AWS] + main assume-role ''
20:25:09 [TerraForm: AWS] + COMMAND=assume-role
20:25:09 [TerraForm: AWS] + '[' 2 -eq 0 ']'
20:25:09 [TerraForm: AWS] + shift
20:25:09 [TerraForm: AWS] + case $COMMAND in
20:25:09 [TerraForm: AWS] + assume_role ''
20:25:09 [TerraForm: AWS] + set +x
20:25:09 [TerraForm: AWS] 
20:25:09 [TerraForm: AWS] Parameter validation failed:
20:25:09 [TerraForm: AWS] Invalid length for parameter RoleName, value: 0, valid range: 1-inf
```

Jenkinsfile: add `TECTONIC_INSTALLER_ROLE` to smoke tests

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
modules/aws/master-asg/master.tf
modules/aws/master-asg/variables.tf
modules/aws/worker-asg/variables.tf
modules/aws/worker-asg/worker.tf
platforms/aws/main.tf
platforms/aws/variables.tf

This change allows users to specify their own external IAM role names for use as instance profiles on master and worker nodes.
Fixes #666 
/cc: @robszumski

Implement BYO node IAM roles

---

Makefile

This change allows users to inject arguments to the terraform commands invoked by make.
To use this feature, one would set environment variables like in this example:
```
export TF_GET_OPTIONS="-no-color -update=false"
export TF_PLAN_OPTIONS="-no-color -out=./plan-file"
export TF_APPLY_OPTIONS="-no-color -parallelism=20"
export TF_DESTROY_OPTIONS="-no-color -refresh=flase"
```
Our immediate use case for this feature is to be able to pass "-no-color" when running in Jenkins, thus cleaning up the log files of unreadable ANSI color codes.

Makefile: allow injecting extra arguments to plan / apply / destroy 

---

modules/openstack/nodes/secgroup.tf

Flannel is configured to use UDP 4789 for vxlan overlay (https://github.com/coreos/tectonic-installer/blob/4ea97a0/modules/bootkube/resources/manifests/kube-flannel.yaml#L23) so we don't need 8472 open on any nodes. Instead, we need to also open 4789 open on controllers.

openstack: Fix flannel security groups

---

platforms/openstack/neutron/nodes.tf
platforms/openstack/nova/nodes.tf

The openstack cloud provider expects the hostname and instance name to match.

openstack: make instance names match hostnames

---

modules/aws/vpc/vpc-public.tf

This prevents the internet gateway to be deleted before Elastic IPs which
can cause destroy failure.
Fixes #1017

modules/aws: add dep from aws_eip.nat_eip to aws_internet_gateway.igw

---

platforms/openstack/neutron/dns.tf
platforms/openstack/neutron/network.tf
platforms/openstack/neutron/nodes.tf

With `experimental=true`, no etcd nodes should be created, and external
DNS records are not needed.

platforms/openstack/neutron: Fix external resources for self-hosted etcd

---

modules/aws/master-asg/elb.tf

@ethernetdan noticed strange behaviour on the Kubelets when master nodes are being scaled.
This might be due to the fact that nodes are being removed from the API ELB while having ongoing connections from kubelets.

Enable connection draining for the API ELBs

---

installer/frontend/ui-tests/pages/platformPage.js

Should fix a flakiness issue with GUI tests.

GUI tests: wait for platform select to be visible, not body.

---

Jenkinsfile

Because we cannot `destroy` the AWS cluster on first try due to various [flakes](https://github.com/coreos/tectonic-installer/issues/1017). None of the Smoke Tests passed today, mostly due to the IGW time-out issue (currently hardcoded in Terraform). This add retries on the `destroy` step, thus allowing the smoke tests to pass if we were able to destroy the cluster eventually. What this means technically is that we expect our users to run destroy multiples times. This change should be reverted once everything is back to normal.
We keep the failure hook in case `apply` fails, so we can garbage collect.

Jenkinsfile: retry destroy on AWS Smoke until #1017/#1054 are fixed

---

modules/vmware/node/ignition.tf

VMware Tools were enabled on etcd nodes but not enabled on Controller/Worker nodes. Systemd unit resource already existed, however was not part of the main ignition-config resource. Binaries for open-vm-tools are already part of CoreOS Container Linux VMware release image.
https://github.com/vmware/open-vm-tools

vmware: enable vmware tools on controller/master

---

modules/azure/master-as/master.tf
modules/azure/worker-as/workers.tf

This change assigns the newly introduced Availability Sets to the corresponding Virtual Machines.
Without this, the node VMs would not actually be placed in the respective AvSets.
/cc: @discordianfish

Azure: configure corresponding AS for VMs

---

Jenkinsfile
contrib/internal-cluster/README.md
contrib/internal-cluster/main.tf
contrib/internal-cluster/vars.tf
contrib/internal-cluster/vpn.tf
images/tectonic-builder/Dockerfile
tests/smoke/aws/smoke.sh
tests/smoke/aws/vars/aws-vpc.tfvars

Enable a smoke test that creates Tectonic cluster in a private VPC. In
order for this to work, we need to first create a VPN connection into
the private VPC. This commit adds two commands to smoke.sh for managing
the state of the private VPC `create-vpc` and `destroy-vpc`.

contrib,tests: add private vpc smoke test

---

modules/aws/ignition/resources/detect-master.sh
modules/aws/master-asg/elb.tf

The ELB name was changed in #920 from `CLUSTER-api-internal` to `CLUSTER-int`
In addition the tag Name is set for the AWS ELB, but is not the same as the actual ELB name.  In the AWS console `CLUSTER-int` shows up on the right side which is the actual ELB name, but in the tags for the ELB `Name=CLUSTER-api-internal` is listed which may cause confusion.

ELB Name is CLUSTER-api-int

---

tests/smoke/aws/smoke.sh
tests/smoke/aws/vars/aws-vpc.tfvars

This commit enables the cleanup destroy block to run for private VPC
test clusters even if `create-vpc` was not run in the same shell.
To test:
```sh
docker run --rm -it -v $PWD:/go/src/tectonic-installer \
-e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
--device=/dev/net/tun --cap-add=NET_ADMIN \
-w /go/src/tectonic-installer quay.io/coreos/tectonic-builder:v1.15 /bin/bash
./tests/smoke/aws/smoke.sh destroy vars/aws-vpc.tfvars
```
Verify that Terraform does not hang while waiting for input. Instead,
Terraform should error because it could not find the tfstate file in
question, which is expected unless the cluster was created. The benefit
is that now, as long as the cluster was created, it does not matter if
`create-vpc` was run or not.
cc @ggreer @Quentin-M

tests/smoke/aws: enable destroy retry for vpc test

---

tests/smoke/aws/vars/aws-vpc.tfvars

This commit reduces the node count for the private vpc test in order to
accomplish two goals:
1. smoke test bringing up a single master cluster; and
2. reduce total resource utilization.
This test should give us greater confidence in the installer since it
tests a new configuration.
cc @Quentin-M @kans

tests/smoke/aws/vars: reduce test node count

---

Documentation/troubleshooting/controller-recovery.md

As of Tectonic 1.6, master label is replaced by `node-role.kubernetes.io/master`
Fixes: https://github.com/coreos/tectonic-installer/issues/837 
/cc: @coresolve

docs: controller-recovery Tectonic 1.6 label updates

---

modules/update-payload/assets.tf

Need to define the variales otherwise the `make payload` command will
fail.
A follow-up PR should move those tectonic operators into a sub-directory
so we don't need to maintain this in the future.
/cc @Quentin-M @alexsomesan @s-urbaniak

update-payload: Fix "make payload".

---

installer/Makefile
modules/aws/ignition/resources/init-assets.sh
modules/aws/ignition/resources/s3-puller.sh
modules/bootkube/resources/bootkube.sh
modules/tectonic/resources/tectonic-rkt.sh
modules/tectonic/resources/tectonic.sh
modules/update-payload/awsutil.sh
modules/update-payload/make-update-payload.sh
modules/update-payload/publish-payload.sh
modules/update-payload/upload-payload.sh
tests/smoke/aws/smoke.sh
tests/smoke/bare-metal/smoke.sh

- `make shellcheck` now checks shell scripts in `tests/` and  `modules/`
- Update all shell scripts in those dirs to pass, either by fixing the warning/error or disabling the rule for that line.
Shellcheck is part of the Jenkins tests, so new lint errors should fail the build. We can clean up the existing stuff in time. Basically, this stops us from making new mistakes.

Shellcheck everything

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/updater/app-version-tectonic-etcd.yaml
modules/tectonic/resources/manifests/updater/tectonic-etcd-operator.yaml
modules/tectonic/resources/tectonic.sh
modules/update-payload/assets.tf
modules/update-payload/make-update-payload.sh

This PR adds the manifests for tectonic-etcd-operator(TEO) `v0.0.1` and the appversion `tectonic-etcd` to the installer.
The TEO will reconcile the versions for its components, etcd-operator and the etcd-cluster, according to the version map maintained by the TEO. 
For the starting TEO version `v0.0.1` these will be etcd-operator(`v0.3.2`) and etcd-cluster(`v3.1.7`). Both these versions have been updated in config.tf.
@yifan-gu @sym3tri 
/cc @xiang90 @hongchaodeng

*: add manifests for tectonic-etcd-operator and tectonic-etcd appversion

---

modules/tectonic/resources/manifests/etcd/cluster-config.yaml

As suggested by @xiang90, this PR introduces resource requests to self-hosted etcd in order to guarantee that they will get enough resources to support the cluster.
Since we document that `t2.medium` instances are the bare-minimum, and since we default to that, this sets the recommended resources for a 10 nodes Kubernetes cluster (500m CPU / 300MB RAM), which should comply with what we currently have.

m/tectonic/r/m/etcd/cluster-config.yaml: add resource requests

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml
modules/bootkube/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf
platforms/vmware/tectonic.tf

Per discussion at https://github.com/coreos/tectonic-installer/issues/347#issuecomment-307177869,
the core components will now have a required pod anti-affinity field
with a label selector that selects labels of the pods of the same version,
so that multiple pods of the same version don't get scheduled into one node while
the pods of different versions can still be scheduled together
/cc @aaronlevy @alexsomesan @s-urbaniak @Quentin-M

bootkube: Add required pod anti-affinity field with proper label selectors.

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
platforms/vmware/variables.tf

The variables were changed at some point without changing the
examples in the comments. This just updates those comments to
eliminate potential for confusion

vmware: fixed example variable names for VMWare terraform vars

---

installer/frontend/components/bm-cluster-info.jsx

The order differed between baremetal & aws. Now they're the same.
Doesn't actually affect the layout, since we currently have no experimental feature checkboxes.

frontend: Consistent order of tectonic license & experimental features

---

Jenkinsfile

This should help us get a better idea of what's failing. I floated the idea in the Monday meeting and nobody seemed to object.

Jenkinsfile: Keep up to 100 builds. 

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.openstack-nova
examples/terraform.tfvars.vmware
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/stats-emitter.yaml
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf
platforms/vmware/tectonic.tf
tests/smoke/aws/vars/aws-ca.tfvars
tests/smoke/aws/vars/aws-exp.tfvars
tests/smoke/aws/vars/aws-tls.tfvars
tests/smoke/aws/vars/aws-vpc.tfvars
tests/smoke/aws/vars/aws.tfvars
tests/smoke/bare-metal/vars/metal.tfvars

This commit makes the stats reporting URL configurable so that all test
clusters will report statistics to the staging stats database. Although
we already filter out all test data from the production database, it is
useful to submit statistics to the staging database so that we can
happily automate tests that fetch data from that database without
interfering with or causing problems in prod.
Updated: turns out to be consistent with how we setup vars, for the
Tectonic module on any platform, we need to be more verbose.
cc @Quentin-M @kans

modules/tectonic,tests/smoke: make stats URL configurable

---

config.tf
modules/update-payload/payload.json

Update container-linux-update-operator to v0.2.1 for the next Tectonic release.
* [Release notes](https://github.com/coreos/container-linux-update-operator/releases/tag/v0.2.1)
* [Images](https://quay.io/repository/coreos/container-linux-update-operator?tab=tags)
Closes https://github.com/coreos/container-linux-update-operator/issues/75
Testing on Tectonic (in addition to earlier CLUO testing):
* Spun up a bare-metal Tectonic cluster with update-operator v0.2.1
* Verify update-agent daemonset gets deployed using the right image / version
* Verify D-Bus needs reboot signal triggers a node to reboot
* Verify only one machine will reboot at a time (send multiple signals)
* Verify an actual CL upgrade succeeds (deployed at stable 1353.7.0, trigger upgrade to 1409.2.0)
* Verify Tectonic …

config.tf: Update CLUO from v0.2.0 to v0.2.1

---

modules/aws/etcd/nodes.tf

This is to prevent Terraform from destroying/re-creating the etcd nodes right away
after a deployment where root_volume_type is not io1.
I am tempted to add ``lifecycle { ignore_changes = [ "*" ] }``.
Fixes #1035
Also created https://github.com/coreos/tectonic-installer/issues/1167 for future ref

modules/aws/etcd/nodes.tf: change hardcoded value of IOPS to 100

---

Jenkinsfile
images/tectonic-builder/Dockerfile
installer/README.md
release.groovy

Bump node to 8.1.2 & yarn to 0.24.6. This lets us use async/await in some frontend tests.

Upgrade Node.js

---

modules/bootkube/resources/experimental/manifests/kenc.yaml

This reenables kenc to be deployed and thus self-hosted etcd to be
recoverable.

modules/bootkube: fix kenc.yaml indentation

---

tests/smoke/cluster_test.go

Tests failing because we are trying to read logs ... but the pod is still being created when we time-out trying to read these logs. This is Friday night hot-fix that should help us a bit. We could wait for the pod to be there before starting a time-out clock.. but this will help.
```
--- FAIL: Test/Cluster/GetIdentityLogs (180.00s)
smoke_test.go:112: failed with error: failed to gather logs for tectonic-system/tectonic-identity, failed to find pods with prefix "tectonic-identity" (found pods in tectonic-system: )
smoke_test.go:113: retrying in 3s
smoke_test.go:112: failed with error: failed to gather logs for tectonic-system/tectonic-identity, failed to find pods with prefix "tectonic-identity" (found pods in tectonic-system: )
smoke_test.go:113: retrying in 3s
smoke_test.go:112: failed …
```

tests/smoke/cluster_test.go: increase timeout/delay for getting pod logs

---

installer/frontend/components/aws-cloud-credentials.jsx

Fixes an annoyance where tf apply would fail despite valid AWS creds.
Apparently, however terraform is using these creds, it's not using them the same way as the go code. In the GUI, creds with trailing spaces get accepted as valid, then tf apply errors-out with a weird complaint about a signature missing an equal sign.

frontend: Don't let users enter AWS creds with starting/trailing spaces

---

Jenkinsfile
tests/smoke/aws/cluster-foreach.sh
tests/smoke/aws/smoke.sh
tests/smoke/forensics.sh

- Add forensic script to ssh to machine & print debugging info
- Add cluster-foreach script to run forensics script on each machine in the ASG.
- Get jenkins & smoke tests to run these scripts automatically (even on failure).

Jenkins: print systemd logs

---

Jenkinsfile
images/tectonic-builder/Dockerfile
modules/update-payload/make-update-payload.sh
modules/update-payload/publish-payload.sh
modules/update-payload/upload-payload.sh
release.groovy
tests/smoke/aws/cluster-foreach.sh

- Update builder image to use shellcheck v0.4.6.
- Fix new shellcheck errors.
- Update Jenkinsfile to use new builder image.
Ubuntu & Debian are on v0.4.4. People using homebrew or other installation methods are likely on newer versions that cause `make lint` to report shellcheck errors that Jenkins doesn't catch.

Use shellcheck v0.4.6

---

Jenkinsfile

This is a temporary stopgap as timeouts frequently cause our builds to abort.  The pipeline timout has also been increased so that we have time to run destroy.

tests: increase smoke test timeouts

---

tests/conformance/conformance.sh

Disable shellcheck to allow MNT_SECRETS to pass in multi-valued variable.

tests/conformance: disable shellcheck for docker run command

---

tests/conformance/conformance.sh

Docker run complains about the double quotes even though shellcheck wants them :(

tests/conformance: remove double quotes to make bash docker run happy

---

tests/conformance/conformance.sh

${MNT_SECRETS} is a multi-valued variable that cannot have quotes around it.

tests/conformance: remove double quotes for docker run command

---

Jenkinsfile
tests/smoke/aws/smoke.sh

Jenkinsfile: added step after second destroy attempt that cleans all
created resources
tests/smoke/aws/: function that runs the grafiti Docker container and
deletes resources based on `tectonicClusterID`
In the case of `terraform destroy` failure, `grafiti delete` will clean up resources unsuccessfully destroyed using their `tectonicClusterID` tag.
Fixes #1116

tests/smoke/aws/: grafiti cleanup hook if smoke test fails

---

tests/conformance/conformance.sh

We don't want the while loop to exit in case of errors, hence we should not `set e`. Or else it can cause false early termination.

tests/conformance: avoid early termination of script

---

modules/vmware/etcd/ignition.tf
modules/vmware/etcd/resources/etcd-cluster
modules/vmware/etcd/variables.tf
platforms/vmware/main.tf
platforms/vmware/remote.tf
platforms/vmware/tectonic.tf

Fixes #459 with a follow up on https://github.com/coreos/tectonic-installer/pull/751
- sets locksmith on etcd nodes to use etcd tls information (if etcd not external or self-hosted)
- sets etcd nodes to use TLS settings part of 751 for etcd-member service
- sets etcd-member service to use endpoints via https (if not self-hosted)
- introduces variables required for etcd tls
- copies over tls secrets to nodes via file provisioners
Tested with parameters
```
tectonic_master_count = 1
tectonic_worker_count = 1
tectonic_etcd_count = 3
```
and
```
tectonic_experimental = false
```
***VS***
```
tectonic_experimental = false
```

vmware: enable tls for staticly-provisioned etcd

---

installer/frontend/components/cluster-type.jsx
installer/frontend/platforms.js

Shouldn't this link open the GUI installer docs?

frontend: Change AWS docs link to open GUI installer docs

---

Documentation/admin/aws-scale.md

typo: `$ terraform apply $ terraform plan \`

docs: fix command syntax errors

---

installer/frontend/.babelrc
installer/frontend/components/header.jsx

We previously made https://github.com/coreos/tectonic-installer/commit/68c4adbdf492f97d728b9c5a04b51e5343d16a04 in order to make the commit/dirty flag available for debugging purposes. As we removed the `--version` and we introduced the header, this disappeared.
This PR adds a 7-characters commit SHA and the dirty flag in the header to get this information back.

installer/frontend: add git short SHA + dirty flag to the header

---

modules/aws/master-asg/elb.tf

Cleanup
Fixes https://github.com/coreos/tectonic-installer/issues/1134
API-External ELB is setup with listening on SSH ports however security groups do not allow SSH traffic.
I believe this is an old configuration from older versions where SSHing into master was done via ELB.

aws: remove SSH listen from API-external ELB

---

CONTRIBUTING.md

From an idea in https://github.com/coreos/tectonic-installer/pull/1122#issuecomment-309531602,
as a new contributor I didn't know from reading the CONTRIBUTING
document that I was expected to run certain `make` commands. This
commit spells it out for contributors that come after me. As tests
are added this list should be expanded.

CONTRIBUTING: adds basic make commands to run before submitting a PR

---

modules/tectonic/resources/manifests/monitoring/prometheus-k8s-rules.yaml

This is a bugfix for the previously introduced alerting rules. The alerting rules did not trigger correctly, in the case where a target is still discovered cannot be scraped successfully, this is now fixed. Additionally runbook links to recovery guides for the kube-scheduler and kube-controller-manager.
The alerting rules have already been reviewed by the monitoring team and have been merged in the Tectonic Prometheus Operator, this PR is just to sync the state.
@s-urbaniak @alexsomesan @Quentin-M 
/cc @robszumski @fabxc @mxinden @gouthamve

monitoring: ensure triggering alerts on down targets

---

contrib/internal-cluster/vars.tf
contrib/internal-cluster/vpn.tf

Currently those IDs are hardcoded. When they are being updated, we have
to bump manually.
This fixes it by looking up those AMIs using a datasource.
Fixes #1265

contrib/internal-cluster: use datasource in favor of AMI IDs

---

installer/frontend/components/bm-nodeforms.jsx

Change "you'd like to use as masters" to "you'd like to use as workers" on Define Workers page.
Add missing space char that wasn't being output after `{docs}`.
Before | After
--- | ---

frontend: Fix text on Bare Metal Define Masters / Workers pages

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/variables.tf
platforms/aws/tectonic.tf

The default behavior of Kubernetes's controller manager is to mark a node
as Unhealthy after 40s without an update from the node's kubelet. However,
AWS ELB's Route53 records have a fixed TTL of 60s. Therefore, when an ELB's
node disappears (e.g. scaled down or crashed), kubelet might fail to report
for a period of time that exceed the default grace period of 40s and the
node might become Unhealthy. While the eviction process won't start until
the pod_eviction_timeout is reached, 5min by default, certain operators
might already have taken action. This is the case for the etcd operator as
of v0.3.3, which removes the likely-healthy etcd pods from the the
cluster, potentially leading to a loss-of-quorum as generally all kubelets
are affected simultaneously.
To cope with this issue, we …

platforms/aws: set controller manager’s timers to work around ELB’s TTL

---

installer/frontend/components/dry-run.jsx
installer/frontend/components/submit-definition.jsx

Link mentions of assets zip in the GUI text to the relevant docs page.
Fixes #1259

frontend: Add links to assets zip docs

---

Makefile

This change adds support for the new `init` command in Terraform 0.10+ which will download the provider modules on demand.
It will only perform the init command if the version of Terraform used is greater then 0.9.x

Makefile: support Terraform v0.10.x

---

modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

This is necessary when updating the component with required pod anti-affinity.

modules/bootkube: Add "maxUnavailable:0" to the rolling update strategy.

---

modules/openstack/secgroups/output.tf
modules/openstack/secgroups/rules/default/secgroup.tf
modules/openstack/secgroups/rules/default/variables.tf
modules/openstack/secgroups/rules/etcd/secgroup.tf
modules/openstack/secgroups/rules/etcd/variables.tf
modules/openstack/secgroups/rules/k8s/secgroup.tf
modules/openstack/secgroups/rules/k8s/variables.tf
modules/openstack/secgroups/secgroup.tf

The existing security group module was using the [deprecated](https://developer.openstack.org/api-ref/compute/#list-networks)
nova-networks API. Updated to use the neutron API directly
and consolidated the security groups to avoid unneccessary
duplication.

modules/openstack/secgroups: Refactor to use neutron API

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/node/nodes.tf
modules/vmware/node/variables.tf
platforms/vmware/main.tf
platforms/vmware/variables.tf

Looks like https://github.com/coreos/tectonic-installer/pull/995 broke the master for vmware. This is my fault with bad testing :( 
VMware module was referencing `tectonic_vmware_ssh_private_key_path` variable that exists in platform/variables.tf but not known to individual module. This pr passes `tectonic_vmware_ssh_private_key_path` to VMware module.

vmware: private key variable

---

installer/frontend/components/base.jsx
installer/frontend/components/tooltip.jsx

The "Next Step" button's tooltip was not working because it has the CSS rule `pointer-events: none`. This fixes it by changing `WithTooltip` to use a wrapping `div` instead of modifying its child element.
Also, if we use a wrapping `div`, I think it makes sense to allow `WithTooltip` to have multiple `children`, which simplifies the code.

frontend: Fix next step tooltip & allow tooltips to apply to multiple elements

---

installer/frontend/components/tf-poweron.jsx
installer/frontend/components/ui.jsx

If the Terraform apply step fails, change the spinner icons for later steps to indicate that they are not expected to progress. However, still allow those steps to indicate success or error (e.g. the "Resolving..." step may still succeed).
Applies to both AWS and Bare Metal.
Fixes #1271

frontend: If Terraform apply fails, stop later step spinners

---

tests/smoke/README.md

Add new information documenting how to compile the smoke test binary rather than using `go test`.
cc @rithujohn191

tests/smoke/README: update smoke test docs

---

modules/aws/etcd/nodes.tf
modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

modules/aws/: add tags to root volumes of instances
All volumes should get the same tags as all other resources.
**Note:** launch configuration volume declarations do not support tagging according to https://github.com/hashicorp/terraform/issues/14558
Applies to #1115

AWS Volume tags

---

config.tf

This is a cherry-pick of https://github.com/coreos/tectonic-installer/pull/1299 into the 1.6.7 release branch.

Bump hyperkube to v1.6.7_coreos.0

---

Jenkinsfile
images/tectonic-builder/Dockerfile

This is using a more flake-resistent Terraform build.

Jenkins: CI test using a flake-resistent Terraform build

---

installer/frontend/components/aws-cluster-info.jsx

During user testing, folks were unsure of how these tags were used. Adding AWS to this label should indicate a bit more that they show up on AWS resources.

frontend: add AWS to field label

---

Jenkinsfile

We saw the following flake two times already:
```
+ bin/smoke -test.v -test.parallel=1 --cluster
=== RUN   Test
=== RUN   Test/Common
=== RUN   Test/Common/APIAvailable
=== RUN   Test/Cluster
=== RUN   Test/Cluster/AllNodesRunning
=== RUN   Test/Cluster/GetIdentityLogs
=== RUN   Test/Cluster/AllPodsRunning
Sending interrupt signal to process
After 10s process did not stop
```
https://jenkins-tectonic-installer.prod.coreos.systems/blue/rest/organizations/jenkins/pipelines/tectonic-installer/branches/PR-1247/runs/27/nodes/39/steps/81/log/?start=0
https://jenkins-tectonic-installer.prod.coreos.systems/blue/rest/organizations/jenkins/pipelines/tectonic-installer/branches/PR-1272/runs/2/nodes/39/steps/75/log/?start=0
Currently we have 35/45 minute timeouts in the Jenkinsfile. The Go based …

Jenkinsfile: bump smoke test timeout to 60 minutes

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/tectonic-aws-vpc.progress
installer/frontend/cluster-config.js

installer/frontend/: 'tectonic_autoscaling_group_extra_tags' will be populated by data from user-provided tags.
User-defined 'extra' tags are not being applied to autoscaling groups because tag data doesn't populate `tectonic_autoscaling_group_extra_tags`.
Applies to #1115

Apply 'extra tags' to autoscaling groups

---

modules/aws/vpc/vpc-public.tf

modules/aws/vpc/: apply internet gateway tags
Internet gateways should get the same tags as all other resources.
Applies to #1115

AWS Internet Gateway tags

---

modules/aws/vpc/sg-etcd.tf

Worker nodes should not have direct access to etcd, and should
only be accessing the api services on the master nodes. This
change removes the worker security group from etcd access.

aws: remove worker access from etcd nodes

---

modules/aws/etcd/ignition.tf
modules/aws/etcd/variables.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/openstack/etcd/ignition.tf
modules/openstack/etcd/variables.tf
modules/vmware/etcd/ignition.tf
modules/vmware/etcd/variables.tf
platforms/aws/main.tf
platforms/openstack/neutron/main.tf
platforms/vmware/main.tf

The client certificates are still needed for locksmith to function
properly.

modules/*/etcd: pass client certs to standalone etcd

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/cluster-config.js

This reverts commit b018c80dc6c4c62fcc38ff9836d1f56e9917e8ce, reversing changes made to d684cca43d80fe92ce94186ccaee9ed7d590c5f6.
When running `terraform plan` to deploy a cluster, the following error message is received:
```
1 error(s) occurred:
* variable tectonic_autoscaling_group_extra_tags should be type list, got map
```
Comments like https://github.com/hashicorp/terraform/issues/7705#issuecomment-300564571 indicate that terraform cannot handle complicated data structures, such as lists of maps whose structures are not explicitly declared, i.e. user-created variables. Therefore the changes created by b018c80dc6c4c62fcc38ff9836d1f56e9917e8ce should be reverted until lists of arbitrary maps are supported. In the meantime a workaround will be created and merged.

Revert "Merge pull request #1314 from estroz/autoscaling-group-tags"

---

Jenkinsfile
images/tectonic-builder/Dockerfile

With this PR comes a new version of the tectonic-builder image (v1.29).

tests: Update tectonic-builder to allow writes to coreos go folder 

---

Documentation/install/aws/index.md
Documentation/install/bare-metal/index.md

During user testing, two things tripped people up that are very easy to fix:
1. The `$PLATFORM` variable is strange if you are not used to the command line, plus we don't actually do the variable interpolation.
2. Some users were unfamiliar with `darwin` = macOS, as this is not a way it is branded.
This change simply gives macOS and Linux users the command to run.
cc: @meghanschofield

docs: print platform lines explictly

---

release.groovy
tests/conformance/conformance.sh

This updates the tectonic-builder image in the `release.groovy` pipeline
script and the `tests/conformance/conformance.sh` script to v1.31.
This image contains our patched version of [terraform](https://github.com/coreos/terraform). @rithujohn191 and @amrutac Can you confirm that this is acceptable for the conformance test and release process? Otherwise I will prepare a separate image.
@gopilal Thanks for pointing this out to me!

Update tectonic-builder in release and conformance scripts

---

modules/tectonic/resources/manifests/updater/operators/container-linux-update-operator.yaml
modules/update-payload/payload.json

* CLUO will default to manage-agent=false in a future release. Retain the original behavior in Tectonic until the new version operator for this component is ready.
* Corresponds to this change which will go into a future CLUO release https://github.com/coreos/container-linux-update-operator/pull/104

modules/update-payload: Retain cluo manage-agent behavior

---

modules/openstack/nodes/ignition.tf
modules/openstack/nodes/variables.tf
platforms/openstack/neutron/main.tf

The tectonic service was not started initially, but the systemd
unit was still enabled, so it would start and fail after a reboot.

modules/openstack: Disable tectonic.service for vanilla

---

modules/aws/master-asg/master.tf

After installing a cluster into an existing VPC without public endpoints, I always have changes reported to the load-balancers attached to the master ASG because of any empty string:
```
~ module.masters.aws_autoscaling_group.masters                                                                     
load_balancers.#:          "2" => "3"                                                                                                                      
load_balancers.0:          "" => ""                                                                                                                        
load_balancers.204496288:  "cluster-int" => "cluster-int"                                                                                            
load_balancers.3856535629: …
```

platforms/aws: Compact master load balancers list

---

Makefile

- Move .PHONY directives next to each rule. We keep forgetting to update the single .PHONY line at the bottom.
- Remove .PHONY directives that don't apply to any rule.
- Add .PHONY directives to rules that we always want to run (basically all the rules in the root makefile).

Makefile: Fix .PHONY directives.

---

Documentation/variables/azure.md
examples/terraform.tfvars.azure
modules/azure/master-as/ignition-master.tf
modules/azure/master-as/master.tf
modules/azure/master-as/resources/master-kubelet.service
modules/azure/master-as/variables.tf
modules/azure/master-ss/master.tf
modules/azure/vnet/nic-worker.tf
modules/azure/vnet/outputs.tf
modules/azure/worker-as/ignition-worker.tf
modules/azure/worker-as/output.tf
modules/azure/worker-as/resources/worker-kubelet.service
modules/azure/worker-as/variables.tf
modules/azure/worker-as/workers.tf
modules/azure/worker-ss/ignition-worker.tf
modules/azure/worker-ss/workers.tf
modules/bootkube/assets.tf
modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/bootstrap-manifests/bootstrap-controller-manager.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-cloud-config.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/variables.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/azure/variables.tf
tests/smoke/azure/smoke.sh

This adds support for the k8s cloud-config feature on Azure.
Generally this opens the possibility to configure cloud-configs for
other platforms too.
Credit goes to "fish", https://github.com/discordianfish
/cc @discordianfish I squashed the whole commit history into one
because it turned out to be rebase hell. I hope you don't mind. Also PTAL.
/cc @alexsomesan @metral
Supersedes #999

modules/azure,modules/bootkube: add cloud-config support

---

Documentation/install/vmware/vmware-terraform.md
modules/vmware/etcd/ignition.tf
modules/vmware/node/ignition.tf

Ignition v0.14.0 (introduced to stable in Container Linux 1409.2.0) [enables VMware Tools services](https://github.com/coreos/ignition/pull/339) by default. Enabling the service via ignition is no longer required & causes issues with booting up CL 1409.2.0 via Terraform. Removing the dependency from Ignition resources.
Also updates the documentation as `DHCP=no` is the default and makes recommendations to use thin provisioning in template and making the VM template name reflect CL version number.
This change assumes user provisioning to VMware infrastructure is using the latest stable CL image.

vmware: 1409.2.0 updates/remove vmtoolsd from ignition

---

Makefile

Fixes build on systems where GNU make is not the default make. (This is more common than you might think.)

Use $(MAKE) instead of "make"

---

platforms/vmware/main.tf
platforms/vmware/tectonic.tf

Follow up on https://github.com/coreos/tectonic-installer/pull/780
fixes:
- syntax error for archive_file resource for assets (copy pasted from AWS; https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/tectonic.tf#L139
- add `kubelet_cni_bin_dir` missing variable to workers https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/main.tf#L138
/cc : @abhinavdahiya

vmware: calico network policy support fixes

---

installer/Makefile
installer/frontend/nightwatch.json
installer/scripts/add_matchbox_hosts.sh

- Use variables instead of duplicating paths.
- Add a Makefile rule for common cleanup code instead of duplicating it.
- Fix indentation.
- Move frontend/ui-tests/utils/addMatchboxHosts.sh to scripts/add_matchbox_hosts.sh so it's shellchecked.
- Don't needlessly chmod +x add_matchbox_hosts.sh
- Die on errors in add_matchbox_hosts.sh
- Use `yarn run baremetal-installer-tests` instead of `yarn baremetal-installer-tests`. I'm surprised this even worked.
- Remove output_folder from nightwatch. We weren't using it.
- Put pid files in /tmp, not ui-tests/reports/.

frontend: Clean up GUI tests.

---

tests/smoke/bare-metal/smoke.sh

Should help troubleshoot #1054.

Smoke tests: Print logs if matchbox or dnsmasq fail.

---

tests/smoke/aws/vars/aws-ca.tfvars
tests/smoke/aws/vars/aws-exp-np.tfvars
tests/smoke/aws/vars/aws-exp.tfvars
tests/smoke/aws/vars/aws-tls.tfvars
tests/smoke/aws/vars/aws-vpc.tfvars
tests/smoke/aws/vars/aws.tfvars

tests/aws: Remove tectonic_admin_password_hash/email from the tfvars to use jenkins env variables

---

platforms/vmware/tectonic.tf

Intend to fix #1405 
**Background:**
Bootkube module requires a list of `etcd_endpoints`. In current implementation, list was generated thru modules.etcd output in platform/vmware. This creates implicit dependency for bootkube module on completion of module.etcd. On platform/vmware, all instances are (attempted to be) generated at the same time, constrained by the infrastructure  (vmware) provider's configuration limits. 
Consider a tectonic cluster with 3 etcd nodes, 2 masters and 2 works. All instance/VM generations are executed in parallel. If master nodes "win the race", bootkube module is not 100% completed (missing bootstrap assets as they depend on etcd nodes output) and `./generated` folder is SCP'ed without bootstrap manifests. If etcd nodes "win the race" of being provisioned …

vmware: fix etcd vs master race condition

---

modules/tectonic/resources/manifests/stats-emitter.yaml

To provide better support and track any potential upgrade issues, we'd
like to begin tracking the version of Tectonic that was first installed
on a cluster using the variable `initialTectonicVersion`.
This commit uses the prefix `initial` since we will soon be also be collecting the currently installed version of Tectonic.
Fixes #445.
cc @sym3tri @s-urbaniak

modules/tectonic/resources: collect initial tectonic version

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

This is to prevent Terraform from re-creating the master and worker nodes right away after a deployment where root_volume_type is not io1.
Issue #1035 is reproduced exactly the same for master and worker nodes.
- https://github.com/coreos/tectonic-installer/issues/1035
- https://github.com/coreos/tectonic-installer/pull/1166
- https://github.com/coreos/tectonic-installer/commit/93d485d9

Changed hardcoded value of IOPS to 100

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.vmware
modules/dns/designate/etcd.tf
modules/dns/designate/master.tf
modules/dns/designate/outputs.tf
modules/dns/designate/tectonic.tf
modules/dns/designate/variables.tf
modules/dns/designate/worker.tf
modules/dns/route53/etcd.tf
modules/dns/route53/master.tf
modules/dns/route53/outputs.tf
modules/dns/route53/tectonic.tf
modules/dns/route53/variables.tf
modules/dns/route53/worker.tf
platforms/openstack/neutron/dns.tf
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/nodes.tf
platforms/openstack/neutron/variables.tf

Fixes #9. This PR does a few things:
- Makes DNS pluggable by introducing `designate` and `route53` drivers
- Refactors openstack/neutron to use module for DNS
This still needs to be tested; we're still in the process of setting up an testing cluster with Designate installed.

Add pluggable DNS modules

---

config.tf
modules/bootkube/resources/experimental/manifests/etcd-operator.yaml

This PR enables the debug logging feature introduced in etcd-operator 0.4.2.
https://github.com/coreos/etcd-operator/pull/1232
The operator will now write logs for certain critical actions(like pod creation/deletion) to a logfile, which will be persisted to an underlying hostPath volume on the node where the operator pod happens to run. 
This logfile helps in debugging failed clusters where the logs for Kubernetes pods are no longer available. The logfile can be retrieved if the nodes of the failed cluster are still accessible by ssh.
/cc @xiang90 @hongchaodeng @coresolve

*: enable debug logging for etcd-operator by default

---

modules/bootkube/assets.tf
modules/bootkube/resources/kubeconfig
modules/bootkube/variables.tf
modules/tectonic/assets.tf
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

modules: kubeconfig 'name' field updated with cluster name 
platforms: added 'cluster_name' keys for each platforms' bootkube module
Tests: created cluster, manually confirmed that `kubeconfig` cluster name was the user-defined cluster name and not `local`
Sample config:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: aws-tls-pr-1360-601234567890
cluster:
server: https://aws-tls-pr-1360-601234567890-api.tectonic.dev.coreos.systems:443
certificate-authority-data: ***OMITTED***
users:
- name: kubelet
user:
client-certificate-data: ***OMITTED***==
client-key-data: ***OMITTED***==
contexts:
- context:
cluster: aws-tls-pr-1360-601234567890
user: kubelet
```
Applies to #512

Use user-defined cluster names in kubeconfig

---

images/tectonic-builder/Dockerfile

tectonic-builder image should have grafiti installed for cluster cleanup.
Required for #1263

images/tectonic-builder: Added 'grafiti' build step to image

---

modules/tectonic/resources/manifests/console/service.yaml

This commit removes the NodePort type from the Tectonic Console Service
so that the service takes the default type, ClusterIP. The rationale for
this change is that without a hardcoded NodePort port, the Tectonic
Console could randomly be assigned one of the ports that Tectonic
reserves for ingress. This causes tectonic.service unit to fail to
deploy the ingress service since the NodePorts it requests are already
assigned. The Tectonic Console service does not need to be assigned a
NodePort, in fact, that configuration is likely vestigial from before
Tectonic used an ingress controller to manage access to the console.
cc @s-urbaniak @Quentin-M

modules/tectonic/resources: make console service ClusterIP

---

config.tf
modules/update-payload/payload.json

* https://github.com/coreos/container-linux-update-operator/releases/tag/v0.2.2
* Tectonic explicitly sets `-manage-agent=true` to retain the previous behavior which manages an update-agent daemonset.

config.tf: Update Container Linux Update Operator to v0.2.2

---

Documentation/files/aws-policy-grafiti.json
Jenkinsfile
tests/smoke/aws/smoke.sh

Jenkinsfile: removed grafiti docker container dependency
tests/smoke/aws: removed grafiti docker container dependency
Environment variables required by `grafiti` to delete orphaned cluster resources are present within `tectonic-builder` containers and not accessible by a `grafiti` container. Cluster cleanup should be done by the same container that created the cluster.

Run 'grafiti' as cleanup step after AWS smoke test failure

---

README.md

Sets the CLUSTER value which is used by the Makefile to the same
value as TF_VAR_tectonic_cluster_name which is used in the symlink.

readme: fix broken step for running tests on local machine

---

tests/conformance/conformance.sh

regression seen due to https://github.com/coreos/tectonic-installer/pull/1421

tests/conformance: update conformance script with tectonic admin credentials.

---

modules/bootkube/assets.tf
modules/bootkube/resources/kubeconfig
modules/bootkube/variables.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/config.yaml
modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

tectonic/resources/manifests/config.yaml: clusterName key holds user-defined cluster
name value to update kubeconfig
tectonic/resources/manifests/console/deployment.yaml: bridge cluster name env var takes
clusterName from configmap
Tests: incoming
Applies to #512 and complements #1360, https://github.com/coreos-inc/bridge/pull/1585
Merge after #1360

Console configmap takes cluster name

---

Documentation/install/aws/troubleshooting.md

Documenation/install/aws: documented resource tagging
Certain resources are either not tagged with user-defined tags or at all. This update explains to what extent those resources are tagged, if at all

Document resource tagging issues

---

modules/tectonic/resources/manifests/updater/operators/kube-version-operator.yaml

This is broken for people upgrading from previous versions, so turn it
off until it is fixed.

kvo: disable image pre-warming.

---

modules/update-payload/make-update-payload.sh

Be default, when upgrading from an old version (several releases behind),
the intermediate payloads will be skipped unless they are "enforced".
The "enforced" field tells tco NOT to skip this payload during
the upgrade.

modules/update-payload: Add an option to enforce payload.

---

installer/frontend/components/success.jsx

This is the last screen of the wizard, so `canNavigateForward()` should always return `false`. `allDone` appears to never be defined anyway.

frontend: Success.canNavigateForward() should just return false

---

config.tf

Includes various bug fixes that we've made over the past 4 days.

Bump Tectonic console to v1.8.1.

---

tests/jenkins-jobs/README.md
tests/jenkins-jobs/builder_tectonic_builder_upstream_terraform.groovy
tests/jenkins-jobs/tectonic_builder_docker_image.groovy

This is a jenkins job that build the tectonic-builder.
Instead of build manually this job can trigger the build and push to the repo.
There is a jenkins seed job that will read the /tests/jenkins-jobs and create all jobs in this folder. For now just this will be created.

ci/tests: add jenkins job to build tectonic-builder image

---

config.tf
platforms/aws/main.tf
platforms/aws/tectonic.tf
platforms/aws/variables.tf

#1071 This is addressing request for clean up. 
I was able to test this successfully.
According to Hashicorp with Terraform 0.11.0 one way of assigning values to lists/maps will be introduced, and the old way which required having `[]` will be removed.

Removing extra "[]" from AWS templates 

---

installer/frontend/components/cluster-type.jsx

Platform dropdown was defaulting to AWS manual install instead of AWS GUI install.
If AWS GUI install is disabled using the `-platforms` command line option, the default will be whichever option appears first in the dropdown.

frontend: Fix Platform default to be AWS using GUI

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

The Auto Scaling groups defined for masters and workers on AWS correctly configure the desired capacity based on `instance_count` but leave the minimum size = `1`. This can result in far less capacity than is desired in the event of losing an instance.

modules/aws: Configure ASG minimum size = desired instance count

---

modules/update-payload/make-update-payload.sh

Reverts coreos/tectonic-installer#1473 as we decide to enforce each intermediate payload be default for now until we have a better design to enable skipping intermediate updates.

Revert "modules/update-payload: Add an option to enforce payload."

---

modules/tectonic/resources/tectonic-rkt.sh
modules/tectonic/resources/tectonic.sh

This commit makes the tectonic.sh script POSIX compliant. This is
necessary because the k8s base image for hyperkube will no longer have
bash installed once https://github.com/kubernetes/kubernetes/pull/48365
lands, so bash-specific syntax will cause cluster bootstrapping to fail.
cc @alexsomesan @sym3tri

modules/tectonic/resources: make tectonic scripts POSIX

---

installer/frontend/components/tf-poweron.jsx

Disables the Next Step button as soon as the destroy action begins (rather than waiting for the destroy action to complete). This avoids the situation where you could be viewing the Installation Complete page while the destroy is running and then be unexpectedly thrown back to the Start Installation page when the destroy action completes.
Also fixes a bug in the logic that should leave the Next Button disabled while `status` is `"Running" `.
Fixes: #1311

Destroy cluster disable next step

---

changes.md

Reverts coreos/tectonic-installer#1510 which was apparently still in WIP.

Revert "changes.md: update for 1.6.7-tectonic.2 / 1.7.1-tectonic.1"

---

tests/jenkins-jobs/README.md
tests/jenkins-jobs/tectonic-installer-nightly-build.groovy
tests/jenkins-jobs/tectonic-installer-nightly-trigger.groovy

This fixes the Jira Issue: TECTEST-13
This job will trigger the tectonic-installer pipeline against master to test the changes in the master branch. the job will run every day around 3 AM UTC time.

ci/tests: add nightly jenkins job to run the tests for tectonic-installer

---

modules/dns/designate/variables.tf

The `admin_email` variable was used, but not defined

modules/dns/designate: Define admin_email variable

---

modules/net/calico-network-policy/resources/manifests/kube-calico.yaml

Both calico install-cni & flannel install-cni drop cni binaries. [this](https://github.com/projectcalico/cni-plugin/commit/23fcd5ff1990b1c9a33c7d1f6f4c437d0e6100e5) allows us to prevent calico drop binaries that flannel already does.
PR on [projectcalico/cni-plugin](https://github.com/projectcalico/cni-plugin/pull/341)

fix condition where both flannel and calico drop same binaries

---

.gitignore
config.tf
modules/update-payload/payload.json

Changelog:
- 1.7.1: bump console to v1.8.4 (#208)
- 1.7.1: add dex configMap migration (#206)

kube-version-operator: update to v1.7.1-kvo.2

---

.gitignore
config.tf
modules/update-payload/payload.json

Cherry-picking https://github.com/coreos/tectonic-installer/pull/1548.
Changelog:
- 1.7.1: bump console to v1.8.4 (#208)
- 1.7.1: add dex configMap migration (#206)

1.7.1: kube-version-operator: update to v1.7.1-kvo.2

---

modules/update-payload/sign-payload.sh
modules/update-payload/upload-payload.sh

Enable signing a staging payload without yubikey.
Enable overwriting the staging payload when submitting the release payload.

Update signing scripts

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx
installer/frontend/components/ui.jsx

Adds progress bars for both the AWS Terraform apply step and for the Starting Tectonic step for both AWS and bare metal.
The Terraform progress is estimated by parsing the log output. This PR uses a very simple approach with the intention of improving the progress bar accuracy in a future PR.
The Tectonic progress is based on the sub-steps, except that the progress bar will not move backwards of a sub-step flips off again.
Makes some CSS changes to improve horizontal alignment of the page elements.
Adds back the install step "cancel" state, introduced by #1274, which seems to have been
accidentally removed and changes its text color to match the pending state.
Fixes #562

frontend: Add progress bars to Start Installation page

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/metal.json
installer/frontend/__tests__/examples/tectonic-aws-vpc.progress
installer/frontend/__tests__/examples/tectonic-aws.progress
installer/frontend/__tests__/examples/tectonic-baremetal.progress
installer/frontend/cluster-config.js
installer/frontend/components/aws-cluster-info.jsx

Remove the Container Linux Update Channel dropdown option from the AWS install Cluster Info page.
See #1209

frontend: Remove Container Linux Update Channel input

---

Jenkinsfile
Makefile

Yifan recently spotted inconsistencies between the state of the installer and the update payload, at a few different places, including in our most recent RC. 
This payload is a very critical part of Tectonic. I suggest we start considering the update payload as a first-class citizen by verifying its up to date status in every PR. Thus, every PR that would modify the update payload at the end of the chain, will be required to update it as part of the PR. Annoying conflicts might potentially appear, but it should be very limited as we rarely modify these managed manifests.
/cc @alexsomesan @s-urbaniak @sym3tri

Makefile: add a structure check for the update payload

---

installer/frontend/components/success.jsx

Partially implements #363.
- Add assets download area
- Text changes
The "Install kubectl" and "Deploy Your First Application" sections will be removed in a separate PR after that info has been moved to Console.

frontend: Installation Complete screen assets download and UI changes

---

modules/azure/master-as/ignition-master.tf
modules/azure/worker-as/ignition-worker.tf
modules/net/ignition/ignition.tf
modules/net/ignition/outputs.tf
modules/net/ignition/resources/tx-off.service

This commit disables TX checksum offloading as a workaround to fix #1171. We ran some iperf benchmarks to determine how different MTU and tx checksum offloading combinations would perform. From the results shown below, we found that disabling TX checksum offloading and keeping the default MTU does not result in a major performance penalty; it will be the most maintainable workaround going forward.
cc @crawford @philips @Quentin-M 
<details>
iperf.yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: iperf
namespace: default
labels:
app: iperf
spec:
replicas: 1
template:
metadata:
name: iperf
labels:
app: iperf
spec:
containers:
- name: iperf-server
image: networkstatic/iperf3
args:
- -s
ports:
- containerPort: 5201
protocol: TCP
nodeSelector: …
```

modules/azure: disable TX checksum offloading

---

config.tf
modules/update-payload/payload.json

Cherry-picks https://github.com/coreos/tectonic-installer/pull/1584 on the 1.7.1 branch.

kvo: v1.7.1-kvo.4 & regenerate update payload.

---

installer/frontend/app.jsx
installer/frontend/tectonic-ga.js

- Add sendError() to TectonicGA.
- Add window.onerror handler.
- Reduce nesting in send() & log error if ga is not a function.

frontend: Add JS error reporting.

---

config.tf

This is needed to test PVC + managed disks, since the workers are on managed disks.
This fixes #1589.

azure: bump hyperkube to 1.7.2

---

installer/frontend/components/success.jsx

Decision is to remove the navigation links from this page (see https://github.com/coreos/tectonic-installer/issues/363#issuecomment-320329693).

frontend: Installation Complete screen - remove Back and Start Over links

---

installer/scripts/release/common.env.sh

VERSION is no longer being set in Makefile, so `make dist` created `tectonic-.tar.gz`
Regression introduced in #1131.

scripts: fix `make dist`

---

modules/update-payload/make-update-payload.sh
modules/update-payload/payload.json

Before 1.7.1, TCO updates itself by applying the TCO deployment manifest in the payload.
In order to make sure it updates itself first without changing other cluster state, we need to make TCO appears first in the list.

modules/update-payload: Make sure TCO always updates itself first.

---

tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy

The Tectonic installer PR trigger job waits until the main pipeline
finishes. This enables mutliple trigger jobs to run concurrent,
otherwise we could never test more than one PR at once.
@cpanato What do you think? Is this a sane fix?

tests: Enable concurrent PR builds

---

Jenkinsfile
images/tectonic-builder/Dockerfile
images/tectonic-builder/README.md
release.groovy
tests/conformance/conformance.sh
upstream-terraform-trigger.groovy

We are currently using a custom terraform version for our default CI
pipeline (See https://github.com/coreos/tectonic-installer/pull/1247).
As end users of Tectonic installer use upstream terraform we need to
test with upstream terraform as well. We are building and publishing the
Tectonic builder image both with CoreOS Terraform as well as upstream
Terraform. This is done via docker `--build-arg` `TERRAFORM_URL`. CoreOS
Terraform is used for normal PR and branch tests, upstream Terraform is
used once per day on master.
* Add `--build-arg` `TERRAFORM_URL` to Tectonic builder Docker file
* Update documentation in tectonic-builder/README.md
* Add upstream-terraform-trigger.groovy pipeline job
With this commit v1.36 and v1.36-upstream-terraform of the Tectonic
builder images are pushed to …

tests: Add upstream terraform trigger

---

installer/frontend/actions.js
installer/frontend/app.jsx
installer/frontend/components/base.jsx
installer/frontend/reducer.js

This makes React Router's history is the source of truth for all location information.

frontend: Fix back button / stop storing current pathname in Redux

---

Jenkinsfile
images/tectonic-smoke-test-env/Dockerfile
tests/rspec/lib/aws.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/forensic.rb
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/ssh.rb
tests/rspec/lib/tfvars_file.rb
tests/smoke/aws/vars/aws.tfvars.json

For now, this simply triggers the forensic.sh script via our rspec
shared example. With this change comes a new version of the
tectonic-smoke-test-env. Namely v3.0.

tests: Trigger forensic scripts in rspec tests

---

tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy

This change removes the synchronously from the PR trigger job

tests/ci: Do not block PR trigger job until triggered jobs are finished

---

installer/frontend/components/success.jsx

Remove "Install kubectl" and "Deploy Your First Application" sections because they have been moved to the Tectonic Console start page.
Text and layout changes for the remaining sections.
Completes installer side of #363.

frontend: Installation Complete page changes

---

tests/jenkins-jobs/README.md
tests/jenkins-jobs/tectonic_installer_upstream_terraform_trigger.groovy
upstream-terraform-trigger.groovy

this fixes https://github.com/coreos/tectonic-installer/issues/1559
waiting for #1444 to be merged then I can update this PR to remove some unnecessary files.
cc @mxinden @squat

tests/ci: add upstream-terraform-trigger as jenkins script

---

installer/api/handlers_aws.go

Currently, only the first 100 hosted zones are retrieved from AWS.
This is the default MaxItems. This change will make subsequent calls
if the response indicates there are more records to be listed.

aws: Retrieve all route 53 hosted zones

---

Jenkinsfile
tests/jenkins-jobs/tectonic_installer_public_pr_trigger_no_smoke.groovy

By adding an additional trigger job, we can differentiate the amount of
tests that should run per PR:
- `do-not-test` - run no tests at all
- no labels - run all tests except smoke tests
- `do-smoke-test` - run all tests
This is to temporally unblock Tectonic installer developers e.g. @ggreer which don't need to run the entire smoke test suite on their PRs all the time. In the long run I would like to implement more fine granular triggers (e.g. by cloud provider, ...).

tests: Add option to trigger PR with and without smoke tests

---

Jenkinsfile
modules/bootkube/outputs.tf
modules/tectonic/output.tf
platforms/aws/tectonic.tf
platforms/metal/tectonic.tf
platforms/vmware/tectonic.tf

As noted by @squat, we were using a funny spelling for the word 'Terraform'.
This fixes it.

Fix spelling of 'Terraform' word

---

installer/api/handlers_terraform.go

This change makes the the backend compatible with Terraform beyond 0.9.x
It adds logic to determine the version of Terraform being used and decides based on version if it needs to run `terraform get` in case of 0.9.x or `terraform init` for 0.10.x and beyond.
Note that the new `init` command also includes the previous functionality of `get` so there is no need to run both.
/cc: @sym3tri

Installer: make backend compatible with Terraform 0.10.x

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/forensic.rb
tests/rspec/lib/kubectl_helpers.rb
tests/rspec/lib/shared_examples/k8s.rb

I soon want to add Azure to our RSpec code base. This will make it as simple as adding  a child class to the `Cluster` parent class.

tests: Refactor cluster logic to use inheritance for different platforms

---

README.md

The Tectonic Installer jenkins isn't word readable so this badge is
pointless. Remove it until we have published results.

README: remove CI badge

---

modules/openstack/secgroups/rules/etcd/secgroup.tf
modules/openstack/secgroups/rules/etcd/variables.tf
modules/openstack/secgroups/rules/k8s/secgroup.tf
modules/openstack/secgroups/rules/k8s/variables.tf
modules/openstack/secgroups/secgroup.tf
modules/openstack/secgroups/variables.tf
platforms/openstack/neutron/main.tf

The cAdvisor port is insecure and the others are only required internally.

openstack: Restrict security groups for insecure and internal ports

---

platforms/openstack/neutron/lbaas.tf
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/network.tf
platforms/openstack/neutron/nodes.tf

Add LBaaSv2 load balancer to balance traffic for k8s masters.
DNS record for the API is updated to point to the load balancer
rather than the masters directly. A floating IP is associated with
the load balancer to provide internet connectivity.

platforms/openstack/neutron: Add LBaaSv2 for masters

---

Documentation/variables/openstack-neutron.md
examples/terraform.tfvars.openstack-neutron
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/network.tf
platforms/openstack/neutron/variables.tf

Make the nameservers configurable so users can choose whatever nameservers
they need to use. Also makes the nameserver usage consistent for both
the nodes and the generated OpenStack subnet resource. The same defaults
of the Google nameservers are still used.

openstack: Configurable nameservers

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

We don't always upgrade the control plane when bumping tectonic versions
(e.g. from 1.6.7-tectonic.1 to 1.6.7-tectonic.2). I think it only makes
sense to enforce the anti-affinity when we are actually bumping
kubernetes.
Right now we have a divergence where 1.6.7-tectonic.2 clusters that
were installed from that version will have '1.6.7-tectonic.2'
anti-affinity in their manifests, whereas anything prior will have
'1.6.7-tectonic.1'.

Use kubernetes version for anti-affinity.

---

config.tf
modules/azure/etcd/etcd.tf
modules/azure/master-as/master.tf
modules/azure/worker-as/workers.tf

Currently, the Container Linux version is referenced in the `storage_image_reference` map for the creation of Azure resources as `version   = "${var.versions["container_linux"]}"`.
The `versions` var points to the `tectonic_versions` map, defined in `config.tf`.
The default map for `tectonic_versions` map hardcodes `container_linux`, which is causing Azure implementations to be instantiated w/ an old version of Container Linux.
This PR uses `version   = "latest"` instead, which will work across all Azure SKUs / `cl_channel`s.
@crawford: this fixes what we were discussing on the channel
cc: @alexsomesan @s-urbaniak @squat

azure: Remove hardcoded Container Linux version

---

config.tf
modules/azure/etcd/etcd.tf
modules/azure/master-as/master.tf
modules/azure/worker-as/workers.tf

Cherry-picks #1668 in the Tectonic 1.7.1 release.
/cc @justaugustus

azure: Remove hardcoded CL ver (`versions["container_linux"]`)

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
platforms/vmware/variables.tf

Add a note to vars & examples regarding use of multiple DNS servers that gets fed into systemd-networkd on Virtual Machines.

docs: vmware - multiple DNS server use in vmware

---

modules/update-payload/make-update-payload.sh
modules/update-payload/payload.json

This copies the appversion's metadata in the payload so we can
decide whether to create an appversion by looking at its annotation
in the payload.

make-update-payload.sh: Include AppVersion's metadata in desired versions.

---

modules/tectonic/resources/manifests/updater/migration-status-kind.yaml

This commit fixes the API group of the Migration Status CRD. The correct
API group is `kvo.coreos.com`. The incorrect group was causing the
Tectonic systemd unit to fail to bring up all the components.
Fixes a regression introduced in: #1704 
cc @yifan-gu @rithujohn191

modules/tectonic: fix CRD API group

---

modules/tectonic/resources/manifests/updater/app-version-kind.yaml
modules/tectonic/resources/manifests/updater/app_versions/app-version-kubernetes.yaml
modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-cluster.yaml
modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-etcd.yaml
modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-monitoring.yaml
modules/tectonic/resources/manifests/updater/migration-status-kind.yaml
modules/tectonic/resources/manifests/updater/tectonic-channel-operator-kind.yaml

This PR reverts #1704 and the PR that tried to patch it #1714. There are several incorrect API types in manifests that cause clusters not to come up:
* https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/updater/tectonic-channel-operator-config.yaml#L2
* https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/tectonic.sh#L216
* https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/tectonic.sh#L223
These should be addressed all at once rather than in pieces in follow up commits.
cc @rithujohn191 @yifan-gu

Revert `Change all AppVersion TPRs to CRDs.`

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

Pull request #1667 introduced a regression in the kube-scheduler and
kube-controller-manager deployments that prevented them from being
created by bootkube start because the pod specs were invalid. The specs
contained a selector field, which should have been in the disruption
instead.
This reverts commit 6a37f2e365094165254679d3cac100ab7e20f143.
@yifan-gu @diegs

Revert "Use kubernetes version for anti-affinity."

---

modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/resources/manifests/identity/deployment.yaml
modules/tectonic/resources/manifests/ingress/default-backend/deployment.yaml
modules/tectonic/resources/manifests/ingress/nodeport/deployment.yaml

This commit pins the identity, ingress, and console components to master
nodes and configures them with preferred anti-affinity to promote HA
configurations.
Tomorrow, when @derekparker is in, we can create the update-spec and add these new manifests to allow clusters to update to this configuration.

modules/tectonic/resources: pin components to masters

---

modules/openstack/secgroups/output.tf
modules/openstack/secgroups/rules/k8s_nodes/secgroup.tf
modules/openstack/secgroups/rules/k8s_nodes/variables.tf
modules/openstack/secgroups/secgroup.tf

Users should be able to use port 80 with their installs. 
We were running a load balancer on port 80 forwarding to 30080 on each worker but the kube-proxy would load balance traffic to port 80 on the other workers. Hence, to support HTTP on port 80 this port needs to be open inside the cluster.

modules/openstack/secgroups: Enable Port 80 for workers inside cluster

---

modules/azure/vnet/outputs.tf

It appears that in the case of using an externally managed DNS domain, the API endpoint configured in kubeconfig was still based on the default Azure (`<CLUSTER>.<LOCATION>.cloudapp.azure.com`).
This change fixes the problem by propagating the FQDN of the record created in external DNS for the API endpoint.
/cc: @sym3tri @Quentin-M @robszumski This should be included in the nearest release.

Azure: correct API endpoint FQDN when using external DNS

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

The anti-affinity label should match the kubernetes version instead
of the tectonic version.
The selector of the controller manager and scheduler should not
contain the anti-affinity label.

module/bootkube: Fix anti-affinity labels / selectors for controller manager and scheduler.

---

installer/frontend/components/cidr.jsx
installer/frontend/components/k8s-cidrs.jsx

Shows an error box if the number of configured nodes is greater than the pod range will allow. (But does not disable the Next Step button.)
Shows an info box if over 75% of the range will be used by the configured nodes.
This PR only checks for AWS. A future PR will add the warning for bare metal.
See #791

frontend: Add warning for small pod IP address ranges

---

config.tf
modules/update-payload/payload.json

Changes:
- Migrate ChannelOperatorConfig/AppVersion/TectonicVersion/MigrationStatus TPR to CRD.
- Support install new object if its upgrade behavior is "CreateOrUpdate".

config.tf: Bump TCO to 0.4.3

---

modules/tectonic/resources/manifests/console/deployment.yaml

modules/tectonic/resources: remove creation timestamp from console deployment

---

modules/update-payload/payload.json

Sorry, the correct payload is on the `crd_migrations` working branch for the release, but not in master. The test infrastructure was broken and thus these did not run.

modules/update-payload/payload.json: fix after #1699

---

modules/update-payload/sign-payload.sh

Otherwise if we cancel signing when yubikey asks for pin, the old
sig will be removed already.

sign-payload.sh: Copy old signature to sig.old if it exists already.

---

installer/frontend/ui-tests/README.md

Google Chrome v60 is now in the stable channel. I think this means there should be no need to specify the Chrome binary path.

frontend/tests: GUI Tests README fixes

---

modules/azure/etcd/etcd.tf
modules/azure/master-as/master.tf
modules/azure/worker-as/workers.tf

I seems the current installer can leak OS disks when deleting instances on Azure (observed in the CI environment).
This change attempts to address that problem.
/cc: @mxinden @cpanato

Azure: delete os disk on termination

---

config.tf
modules/update-payload/payload.json

This TEO release does not update the etcd-operator or the self-hosted cluster. It just recognizes the change of AppVersions now being CRDs by using the updated operator-client. 
@Quentin-M @yifan-gu @xiang90 @hongchaodeng

config.tf: bump TEO to 0.0.2 for CRD migration

---

platforms/openstack/neutron/main.tf

90f4d06c changed the worker DNS records to the port on the
private subnet. Reverting this change so that workers can
be accessed externally by name.

platforms/openstack/neutron: Revert DNS change for workers

---

installer/frontend/components/tf-poweron.jsx

The Start Installation page design changes includes removing the Start Over link. (Start Over button is still available after destroying a cluster.)
Also moves Download assets button to the left and hides it until Terraform has finished.
Related to #356

frontend: Remove Start Over link from Start Installation page

---

Documentation/generic-platform.md
Documentation/tutorials/index.md

Replaces all appearances of "self-driving" in Tectonic docs.

Documentation/*.md: Swap out self-driving for automated operations

---

tests/jenkins-jobs/README.md
tests/jenkins-jobs/tectonic_installer_multibranch_job.groovy

Before merging this PR we need to delete the existing `tectonic-installer` Jenkins job.
This will replace the existing one.
cc @mxinden

tests/ci: add multibranch tectonic-installer jenkins job

---

config.tf

- Cherry-picks https://github.com/coreos/tectonic-installer/pull/1780
- Already in KVO.3

config.tf: bump dex to v2.6.1

---

Documentation/hack/centos-workers.md
Documentation/install/aws/aws-terraform.md
Documentation/install/aws/index.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/tutorials/installing-tectonic.md
Documentation/tutorials/tectonic-sandbox/index.md

Version strings have yet to be updated upstream to 1.7.1-tectonic.2
The "Let's Get Started" has also been added to`Documentation/tutorials/tectonic-sandbox/index.md`.

Update version string to 1.7.1-tectonic.2

---

Documentation/install/rhel/installing-workers.md

There is a newer `tectonic-release` package with some minor fixes that should be preferred in the documentation.

docs: update the RHEL package version

---

installer/scripts/maintenance/clean-aws.sh

this fixes an issue in the clean.sh script which was using an `ash` instead of `bash`
cc
@mxinden

tests/maintenance: fix typo

---

Documentation/tutorials/sandbox/index.md
Documentation/tutorials/sandbox/install.md

Add install guide to Sandbox overview

---

installer/frontend/components/cluster-type.jsx
installer/frontend/components/restore.jsx
installer/frontend/platforms.js

Platforms can also be disabled using the `-platforms` command line option.

frontend: Add restore modal errors for unsupported or disabled platforms

---

installer/frontend/components/base.jsx
installer/frontend/trail.js

Also moves canReset to be an attribute of the trail pages.

frontend: Add Start Over button back to install screen

---

installer/frontend/ui-tests/utils/awsInstallerInput.js
tests/smoke/aws/vars/aws-vpc-internal.tfvars.json

The GUI tests are failing because the are using one of the output files
from a different frontend test rather than their own configuration. This
GUI test modifies the configuration file to suite its needs, which will
always be a game of catchup. This fixes the issue for the time being but
it will need more refactoring.
cc @kyoto

tests: fix GUI test

---

git-version
installer/scripts/release/common.env.sh
installer/scripts/release/make_github_release.sh

- Fixes an issue where the tag was never used as part of the version, as initially intended (intro in #987) 
- Fixes an issue where the commit SHA was used for the release instead of the provided tag (intro in #1613) - therefore creating invalid tarball names and breaking the Github release creation (`422 Unprocessable Entity` because no tag with that name)
- Fixes a issue that existed for too long where the Github release was created without a name provided - letting Github pick a default name for the release, a.k.a. the git commit message, and thus forcing the release manager to rename the release manually after the fact
/cc @sudhaponnaganti 
edit: sorry I just noticed that I pushed to origin by mistake, leaving the office.

Fix legacy release scripts

---

modules/bootkube/resources/bootkube.service
platforms/metal/cl/bootkube-controller.yaml.tmpl

This introduces an explicit weak start-ordering between kubelet and bootkube,
with the following rationale:
* After: bootkube needs kubelet to work
* Wants: kubelet may be crash-looping for some time at first before kubelet.env
appears, so we introduce a weak dependency here (i.e. no `Requires`).

bootkube: add explicit start ordering

---

tests/rspec/lib/aws_vpc.rb

Before, whenever the vpn connection was never established, `@vpn_connection.stop` would fail, which meant that `terraform_destroy` was never executed.

tests: Always run terraform_destroy in aws vpc test

---

Jenkinsfile
tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/aws_iam.rb
tests/rspec/lib/aws_vpc.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/grafiti.rb
tests/rspec/spec/aws_vpc_internal_spec.rb
tests/rspec/spec/meta-tests/aws_vpc_spec.rb
tests/rspec/spec/meta-tests/tfvars_file_spec.rb

This PR removes our main AWS test that was implemented in bash. In order to replace it this PR introduces in addition in RSpec:
- Grafiti to run after failed destroy
- Assume AWS tectonic-installer role

Replace aws test implemented in bash

---

tests/jenkins-jobs/tectonic_builder_docker_image.groovy
tests/jenkins-jobs/tectonic_installer_nightly_trigger.groovy
tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy
tests/jenkins-jobs/tectonic_installer_public_pr_trigger_no_smoke.groovy
tests/jenkins-jobs/tectonic_installer_upstream_terraform_trigger.groovy

- Add extra notification when running the nightly build to
tectonic-installer channel
- add option to notify when have repeated failures

tests/ci: add slack notification to #tectonic-installer channel

---

installer/frontend/ui-tests/pages/awsCredentialsPage.js

test/frontend: add way to use Session token or normal aws cred in UI tests for aws

---

tests/jenkins-jobs/tectonic_builder_docker_image.groovy

Jenkins complain: ERROR: (tectonic_builder_docker_image.groovy, line 36) No such property: QUAY_USERNAME for class: javaposse.jobdsl.dsl.helpers.step.StepContext

test/ci: fix issue in dsl

---

platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl

This updates kubelet setup on bare-metal to unify with all other
platforms. It gets rid of path activation and enables kubelet.service
directly from ignition.

platforms/metal: unify kubelet, install as enabled

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/ui-tests/pages/awsCredentialsPage.js

Otherwise they end up with duplicate ids.
Also makes it easier to test with Nightwatch.

frontend: Add id attributes to the session token radio inputs

---

config.tf

**Image:**  `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.12`
*Breaking changes:*
- SSL passthrough is disabled by default. To enable the feature use `--enable-ssl-passthrough`
*New Features:*
- Support for arm64
- New flags to customize listen ports
- Per minute rate limiting
- Rate limit whitelist
- Configuration of nginx worker timeout (to avoid zombie nginx workers processes)
- Redirects from non-www to www
- Custom default backend (per Ingress)
- Graceful shutdown for NGINX
Complete changelog [here](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/Changelog.md)

Update nginx ingress controller to 0.9-beta.12

---

README.md

This PR updates our PR testing documentation.
I will follow up with further documentation on how to run our tests locally with the preparation for our RSpec introduction meeting this week.

tests: Update GitHub PR testing process

---

modules/aws/etcd/ignition.tf
modules/azure/etcd/ignition.tf
modules/openstack/etcd/ignition.tf

All etcd flags are preceded by double dash except for "-peer-client-cert-auth" which can be found with either single and double dash (modules/vmware/etcd/ignition.tf, modules/bootkube/resources/experimental/bootstrap-manifests/bootstrap-etcd.yaml)
Not sure if there's any reason behind this, so just adding consistency here by setting always double dash.

Double dash flag consistency.

---

Makefile
tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/name_generator.rb

When someone runs the smoke tests locally this PR enforces that a cluster name is set. This ensures, that we can identify a left over cluster with a person instead of seeing random cluster names.

tests: Enfore consistent name for local clusters

---

modules/tectonic/assets.tf
modules/tectonic/resources/manifests/config.yaml
modules/tectonic/resources/manifests/stats-emitter.yaml

This commit removes the `tectonicUpdaterEnabled` statistic from the
stats-extender and from the Tectonic Installer since this option is
always enabled. No changes are needed to the BigQuery schema thanks to
the design of the `extensions` schema. Furthermore, since the updater was
decoupled from the experimental features, the reported value for this metric
has been incorrect.
cc @alexsomesan @sym3tri

modules/tectonic: remove updater enabled statistic

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf
platforms/aws/variables.tf

Possibly related to this issue with the Terraform AWS provider:
terraform-providers/terraform-provider-aws#1521
Terraform or the AWS API report `0` IOPS for `gp2` volumes after creation.
If I create a `gp2` volume with these modules, every subsequent run of
Terraform will attempt to destroy and recreate the LC in order to make
IOPs match. This change sets IOPS to 0 for non-`io1` type volumes.
Since the number of IOPS for `gp2` volume is based on the size, Terraform
arguably should only accept the `iops` parameter for `io1` volumes.
Interestingly, for the etcd nodes, this problem does not occur because
the Terraform state shows 100 IOPS even for `gp2` volumes.

Fix terraform resource churn

---

modules/aws/vpc/variables.tf
modules/aws/vpc/vpc.tf
platforms/aws/main.tf

Proposing a change - this maintains the same naming convention as the previous Tectonic installer.

Append the base domain to the VPC name

---

README.md

To improve usability of runnning the smoke tests locally, we run them
inside a docker container. The Tectonic installer repository will be
mounted into the container before executing the tests. In order for the
installer to read the *pull-secret* and *license* file, they have to be
in the repository folder, otherwise they can not be read by the
installer during runtime.
This commit adds a hint to the README to point this fact out.

tests: Add hint to README for license and pull secret path
