coreos/tectonic-installer

modules/aws/etcd/ignition.tf
modules/aws/master-asg/elb.tf
terraform.mk

* Fix missing '$' in HCL expression
* Makefile: fix PATH appending for paths with spaces
* Health-check on API ports in the API ELBs
@s-urbaniak @Quentin-M

Assortment of fixes

---

platforms/aws/variables.tf

I think these are the generalcase defaults. LMK if this messes something
up though.

platforms/aws: default cidr and vpc

---

platforms/openstack/neutron/terraform.tfvars.example
platforms/openstack/nova/terraform.tfvars.example

openstack: add example configuration

---

modules/tectonic/resources/tectonic.sh

We still get 404s randomly on AWS when waiting for TPRs.
This makes TPR waiting more resilient by not only listing TPR values but
also namespacing the query and also querying the TPR list and filtering
for the requested name.

tectonic: more resilient tpr wait function

---

Documentation/variables/platform-aws.md
Documentation/variables/platform-azure.md

Documentation: regenrate variable docs

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
modules/tectonic/variables.tf
platforms/aws/variables.tf
platforms/azure/variables.tf

Added missing descriptions and updated existing ones. If we're happy with these, the last step is to re-generate the variable docs.

Improve AWS, Azure, Tectonic variable descriptions

---

platforms/azure/terraform.tfvars.example

Found another reference to AWS in Azure installer.

remove reference to route 53 in azure template

---

Documentation/install/aws/aws-terraform.md

Remove the need to manually adjust the Terraform path.

Use pwd for path export

---

Documentation/hack/centos-workers.md

Documentation: Add CentOS workers document

---

config.tf

https://github.com/coreos-inc/bridge/releases/tag/v1.3.0

config.tf: bump console to v1.3.0

---

modules/aws/master-asg/elb.tf
modules/aws/master-asg/master.tf
modules/aws/master-asg/variables.tf
platforms/aws/main.tf
platforms/aws/route53.tf
platforms/aws/variables.tf

aws: bring your own private VPC

---

Jenkinsfile

This change introduces a simple Jenkins Pipeline DSL file that right now just runs one test: the Terraform syntax check.
Although not much of a test in itself, this serves a good base for tweaking Jenkins to run PR checks and other tests safely.
Once this is in place, we I will start adding Tectonic tests.

Jenkins pipeline first step: run Terraform syntax checker

---

Jenkinsfile
Makefile
test/aws.tfvars

Adds AWS smoke testing to be eventually run on PRs
Creates a new folder for test configuration but we may want to get it working with the examples folder.

Jenkins AWS smoke test

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/config.yaml
modules/tectonic/resources/tectonic-rkt.sh
modules/tectonic/resources/tectonic.sh
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

modules/tectonic: add experimental flag

---

modules/aws/master-asg/elb.tf
modules/aws/master-asg/variables.tf
platforms/aws/main.tf
platforms/aws/variables.tf

This fixes https://github.com/coreos/tectonic-installer/issues/228
@Quentin-M @s-urbaniak

AWS: implement custom DNS prefixes

---

Dockerfile

Update terraform in the docker image to include tags changes from @s-urbaniak

Update terraform in Dockerfile to v0.8.8-coreos.1

---

config.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/azure/terraform.tfvars.example
platforms/azure/variables.tf

https://github.com/coreos/tectonic-installer/pull/163#pullrequestreview-32954641
@Quentin-M

platform/azure: moved tectonic_create_dns_zone

---

modules/aws/etcd/nodes.tf
modules/aws/etcd/variables.tf
modules/aws/master-asg/master.tf
modules/aws/master-asg/variables.tf
modules/aws/worker-asg/variables.tf
modules/aws/worker-asg/worker.tf
platforms/aws/main.tf
platforms/aws/variables.tf

... for masters, workers and etcd nodes.
Fixes #209

platforms/aws: configure root block device settings

---

config.tf

config.tf: restrict terraform version

---

Jenkinsfile
modules/aws/ignition/ignition.tf
modules/azure/master/ignition-master.tf
modules/azure/worker/ignition-worker.tf
modules/openstack/nodes/ignition.tf

Untested. Do NOT merge yet.
First step towards fixing #221

modules/aws: limit docker log file sizes

---

installer/.gitignore
installer/frontend/components/aws-tf-poweron.jsx

Since the open-sourcing got merged, these two commits were added. I don't think there is anything else missing?

Catchup two commits since the open-sourcing

---

installer/assets/frontend/css/styles.css
installer/frontend/components/aws-tf-poweron.jsx

Sorry, for the screenshot in failure mode, my cluster was in this weird state.

frontend: Adds styles for terraform logs on the poweron screen

---

installer/frontend/cluster-config.js

Also, fix the app id for all platforms.

frontend: Hook up experimental operators in Terraform GUI.

---

config.tf

https://github.com/coreos-inc/bridge/releases/tag/v1.4.0

frontend: Updates console to v1.4.0

---

Makefile

This integrates the new pluginin-vending installer binary into the make based workflow.
After this change, `make [apply | destroy | plan]` will ensure that terraform is run with the correct plugin configuration.
/cc: @Quentin-M

Makefile configures and uses installer plugins

---

installer/frontend/components/aws-tf-poweron.jsx

Oops, ref was in the wrong place.

frontend: Scroll to bottom of terraform output.

---

installer/frontend/cluster-config.js

I'm pretty sure the structure is right. Terraform apply runs successfully and boots a cluster.

frontend: Hook up custom subnets for AWS Terraform installer.

---

Jenkinsfile
Makefile

Fix jenkinsfile

---

Jenkinsfile

Fixes bug from #276
@Quentin-M @dghubble @sym3tri @squat  PTAL

Ensure bin directory exist before building tools

---

Documentation/variables/aws.md
Documentation/variables/azure.md
Documentation/variables/config.md
Documentation/variables/openstack-neutron.md
Documentation/variables/openstack-nova.md
Makefile
config.tf
platforms/aws/variables.tf
platforms/azure/variables.tf
platforms/openstack/neutron/variables.tf
platforms/openstack/nova/variables.tf

Documentation: version, and document configuration

---

config.tf

Update to use console v1.4.1.

---

Jenkinsfile

Destroy clusters on error

---

platforms/aws/terraform.tfvars.example

Fixes #319
/cc @alexsomesan, @yifan-gu

aws/example: add required tectonic_aws_az_count variable

---

installer/server/terraform.go

- Bubble-up errors on submission.
- Clean up messages where possible.

server: Better error messages.

---

Jenkinsfile
test/aws.tfvars

Update configuration for new testing environment

Update testing environment for AWS

---

Jenkinsfile

Until #342 is ready and merged lets go back to master passing.
I'm going to add protection to the master branch after a few stable runs.

Revert using post block until cleanup script is created

---

modules/tectonic/resources/manifests/updater/node-agent.yaml

manifests: add toleration to node-agent

---

installer/server/terraform.go

This PR introduces a new `retry` boolean to the `terraform/apply` API endpoint. When specified, the backend will try to restore the executor from the session rather than creating a new one. If there was no executor in the session, an error will be thrown.

installer/server/terraform: add an option to retry `terraform apply`

---

installer/frontend/components/success.jsx

update link and button to avoid a "this page has moved" page in k8s docs

installer/.../success.jsx: Update links to kubectl install doc

---

config.tf
modules/aws/ignition/ignition.tf
modules/aws/ignition/resources/init-assets.sh
modules/aws/ignition/resources/services/init-assets.service
modules/aws/ignition/resources/services/kubelet-env.service
modules/aws/ignition/resources/services/kubelet.service

Also make kubelet.service to use '/etc/kubernetes/kubelet.env' for
the image URL and VERSION. The '/etc/kubernetes/kubelet.env' will only
be set for the master node.

modules/aws: Add kubelet-env.service to get the kubelet image version.

---

installer/assets/frontend/css/styles.css

Fixes the common error of thinking empty fields are populated.

frontend: Make placeholder values #aaa

---

Documentation/admin/ldap-user-management.md

- performed minor edits for clarity
- added procedural flow

Documentation/admin/ldap-user-management.md: give procedure flow to the doc

---

Documentation/tutorials/creating-aws.md
Documentation/tutorials/installing-tectonic.md

I have not yet seen the Installer complete, and would like to finalize these after I do, but, other than that, these should be good to go.

doc: Updating AWS tutorials for terraform release

---

installer/examples/aws-tf.json
installer/examples/aws-vpc.json
installer/examples/tectonic-aws-tf.progress
installer/frontend/aws-actions.js
installer/frontend/aws-api.js
installer/frontend/cluster-config.js
installer/frontend/components/bm-sshkeys.jsx
installer/frontend/components/cluster-type.jsx
installer/frontend/components/k8s-cidrs.jsx
installer/frontend/components/tf-poweron.jsx
installer/frontend/platforms.js
installer/frontend/server.js
installer/frontend/trail.js
installer/server/platforms.go
installer/server/terraform/executor.go

TODO:
~~- terraform doesn't support multiple ssh keys. need to change the GUI to disallow that~~
~~- lots of copy-pasted code that can be generalized~~
~~- doesn't actually work yet. appears to be a backend bug~~

baremetal-tf GUI

---

installer/server/terraform.go

Also, don't print an error if status is 404 (user didn't run tf apply yet).
This fixes the confusing message that users see in the installer console:
`ERRO[0003] &{http: named cookie not present Could not find session data. Run terraform apply first. 404} `

server: Clean up error msgs for restoring execution session.

---

modules/aws/ignition/ignition.tf
modules/azure/master/ignition-master.tf
modules/azure/worker/ignition-worker.tf
modules/openstack/nodes/ignition.tf
modules/tectonic/resources/manifests/container-linux-updater/deployment.yaml
modules/tectonic/resources/tectonic.sh
platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl

Mask locksmithd as well.
Marked do-not-merge for now because it uses my personal test build of CLUO, pending a merge+release there.

resources: add container-linux-updater

---

config.tf

https://github.com/coreos-inc/bridge/releases/tag/v1.5.0

frontend: Bumps console to v1.5.0

---

modules/tectonic/resources/manifests/rbac/role-ingress-controller.yaml

Docs for using this are available in https://github.com/coreos-inc/tectonic/pull/1727

modules/tectonic: add ingress role

---

Makefile

Several people got confused reading this error message.. this PR aims at making it more understandable and making it suggest an action to take.

Makefile: make structure-check error clear

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md

docs: install: fix example tfvars locations

---

config.tf

Fixes minor bugs in etcd cluster details page and RBAC pages

frontend: Bump console to v1.5.1

---

Documentation/admin/workload-separation.md

Just drafted.. Sorry in advance for the poor grammar - did not really proof-read myself..

Documentation: describe workload-separation

---

installer/server/platforms.go

Fixes https://github.com/coreos/tectonic-installer/issues/456

server: Only list terraform platforms.

---

Documentation/conventions.md
Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/openstack/openstack-terraform.md

Fixes https://github.com/coreos/tectonic-installer/issues/478

docs: update locations of tfvars example files

---

modules/bootkube/resources/manifests/kube-apiserver.yaml

Use /var/log/kubernetes for apiserver audit logs hostVolume

---

.gitignore
Makefile
README.md
installer/Dockerfile
installer/Makefile
installer/README.md
modules/aws/vpc/vpc-public.tf

- Documents how to run same test as Jenkins
- Attempts to fix flaky tests (see #476)
- Minor README/Makefile cleanup

Various cleanups

---

Documentation/variables/aws.md
Jenkinsfile
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.openstack-nova
installer/examples/aws.json
installer/frontend/cluster-config.js
platforms/aws/main.tf
platforms/aws/variables.tf
test/aws.tfvars

platforms/aws: configure AWS region

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/etcd/cluster-config.yaml
modules/tectonic/resources/tectonic.sh
modules/tectonic/variables.tf
platforms/aws/tectonic.tf

... based on the master count
Fixes #448

modules/tectonic: scale self-hosted etcd nodes

---

config.tf

Fixes styling for side nav and etcd cluster labels

config.tf: Updates console

---

Documentation/install/bare-metal/index.md

* Use the matchbox releases and documentation site where possible
* Update some of the language we use for the matchbox description and PXE network description

Documentation/install: Update bare-metal GUI docs

---

config.tf

Fixes etcd cluster details bug reported by Brandon

config: Updates console to v1.5.3

---

modules/tectonic/resources/tectonic.sh

Introduced in #534, simple typo
cc @yifan-gu

modules: fix typo in CLUO resource creation

---

Documentation/variables/config.md
config.tf
installer/examples/tectonic-baremetal.progress
installer/frontend/cluster-config.js
installer/server/tectonic.go
installer/tests/scripts/aws/default.env.sh
installer/tests/scripts/aws/upgrade.sh

Currently Tectonic Update channel manifests refer to Tectonic-1.5

Bump Tectonic Update Channel

---

installer/assets/frontend/css/styles.css

frontend: Make clickable area in nav links bigger.

---

Documentation/troubleshooting/installer-terraform.md

Adds a note about a common issue, most recently in https://github.com/coreos/tectonic-installer/pull/594/files#r115368917

docs: add invalid tag node

---

installer/frontend/components/tectonic-license.jsx
installer/frontend/components/ui.jsx

frontend: Re-populate FileArea if file is the same.

---

Documentation/hack/centos-workers.md
Documentation/install/aws/index.md
Documentation/install/bare-metal/index.md
Documentation/troubleshooting/controller-recovery.md
Documentation/troubleshooting/faq.md

Docs: Bump version strings to 1.6.2-tectonic.1

---

installer/frontend/components/aws-vpc.jsx
installer/frontend/components/ui.jsx

- Use new getDefault() to prepopulate subdomain with clustername

frontend: Add support for getDefault() in Connect()

---

installer/frontend/app.jsx
installer/frontend/components/success.jsx

Don't reset when user clicks "view my console". Fixes #520.

frontend: Destroy session in window.reset()

---

modules/azure/master/master.tf
modules/azure/vnet/security-groups.tf
modules/azure/vnet/virtualnet.tf

Fixes: https://github.com/coreos/tectonic-installer/issues/596

modules/azure: remove kubernetes cluster tag

---

modules/azure/etcd/etcd.tf
modules/azure/etcd/ignition.tf
modules/azure/etcd/variables.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf

Fixes 1/2 of #464 
Also, added `tectonic_master_count` since that seems like a required variable now.

platforms/azure: added ssh key to etcd

---

platforms/openstack/nova/main.tf

Adds several required variables that were not defined
in the openstack/nova module.

platforms/openstack: Add missing variables

---

installer/assets/frontend/lib/mochi/mochi.css
installer/frontend/components/tf-poweron.jsx

restyles terraform failure btns

---

installer/assets/frontend/lib/mochi/mochi.css
installer/frontend/components/tf-poweron.jsx

Add btn-info which is blue.
Better styling of hover for buttons.

frontend: More button styling.

---

README.md

Fixes https://github.com/coreos/tectonic-installer/issues/647

readme: update platforms

---

installer/frontend/form.js

1. Emtpy arrays arent falsy (returning errors).
2. Dynamically creating React Components causes react to think you are making new components.

frontend: bug fixes for fieldlists:

---

Documentation/install/bare-metal/metal-terraform.md

for https://github.com/coreos/tectonic-installer/issues/660

docs: adding terraform get command.

---

Documentation/admin/logging.md

Adds a missing directory to the URL path.

Documentation: Fix links to logging manifests

---

installer/frontend/components/aws-cluster-info.jsx
installer/frontend/components/bm-cluster-info.jsx
installer/frontend/fields.js
installer/frontend/validate.js

...which requires sharing some Fields between AWS and BM.  This PR should introduce no new behavior.

frontend: move bm clusterinfo to framework

---

installer/frontend/__tests__/protocols.js
installer/frontend/components/bm-hostname.jsx

and uses new framework. Most of the diff is white space.

frontend: fixes master/tectonic DNS validation

---

installer/frontend/aws-actions.js
installer/frontend/components/aws-cloud-credentials.jsx

validation behavior.  Do not always hard reset state before starting validation.

frontend: fixes some non-deterministic async/xhr

---

installer/Makefile

Reverts coreos/tectonic-installer#721

Revert "Always cache go builds with -i"

---

installer/api/api.go

Before #325, debug logging logged HTTP requests as they came in. Restore this behavior.

server: Log HTTP requests.

---

installer/scripts/release/make_github_release.sh
release.groovy

Update tectonic-builder image. 
Add a Jenkins parameter to determine release type (if pre-release or not).

*: Revive release automation.

---

installer/frontend/actions.js
installer/frontend/aws-actions.js
installer/frontend/cluster-config.js
installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-submit-keys.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js
installer/frontend/reducer.js
installer/frontend/trail.js

- Port AWS SSH selection to new form stuff.
- Move Selector from AWS VPC to UI.
- Use Selector on AWS SSH page.
Depends on #713.

frontend: Follow dependencies when validating forms

---

installer/scripts/release/get_installer_bins.sh
installer/scripts/release/get_terraform_bins.sh
installer/scripts/release/make_release_tarball.sh
installer/scripts/release/upload_installer_bins.sh
installer/scripts/release/upload_release_tarball.sh

installer/scripts/release: drop Terraform binary on Windows

---

Jenkinsfile

Terraform destroy was failing in jenkins for days and we didn't notice.

Jenkinsfile: fail test if terraform destroy failed

---

Documentation/variables/azure.md
examples/terraform.tfvars.azure
platforms/azure/variables.tf

Comment out `tectonic_azure_image_reference`

---

modules/aws/etcd/nodes.tf

modules/aws: enforce "-etcd" suffix on AWS etcd nodes

---

modules/tectonic/resources/tectonic.sh

modules/tectonic: remove prometheus-k8s-confi.yaml from tectonic.sh

---

release.groovy

Keeping this script up to date. Already do this in Jenkins just keeping release.groovy in sync so its kept in source somewhere.

release.groovy: minor updates to the release script

---

modules/aws/etcd/nodes.tf
modules/aws/etcd/variables.tf
modules/aws/master-asg/elb.tf
modules/aws/master-asg/master.tf
modules/aws/master-asg/variables.tf
modules/aws/vpc/sg-elb.tf
modules/aws/vpc/sg-etcd.tf
modules/aws/vpc/sg-master.tf
modules/aws/vpc/sg-worker.tf
modules/aws/vpc/variables.tf
modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf
modules/aws/vpc/vpc.tf
modules/aws/worker-asg/variables.tf
modules/aws/worker-asg/worker.tf
modules/tectonic/output.tf
platforms/aws/main.tf
platforms/aws/route53.tf

modules/aws: enforce tectonicClusterID tag on resources

---

config.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/bootkube/resources/bootkube.sh
modules/bootkube/resources/experimental/bootstrap-manifests/bootstrap-etcd.yaml
modules/bootkube/resources/experimental/etcd/bootstrap-etcd-service.json
modules/bootkube/resources/experimental/etcd/migrate-etcd-cluster.json
modules/bootkube/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/openstack/nova/main.tf

Bump bootkube v0.4.4 & hyperkube v1.6.4_coreos.0

---

Jenkinsfile

Ensure smoke tests exit if `terraform apply` fails.
Addresses #819

Smoke test bail apply

---

.github/ISSUE_TEMPLATE.md

Similar to the [kubeadm issue template](https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md).

GitHub issue template

---

config.tf

Fixes non-atomic write:
https://github.com/kubernetes-incubator/bootkube/pull/537
Fixes #833

Pod checkpointer version to 7da334a1d768c346798601eb8387f266d15cf330.

---

config.tf

https://github.com/coreos-inc/bridge/releases/tag/v1.6.0

config.tf: Bumps console to v1.6.1

---

installer/assets/frontend/css/styles.css
installer/frontend/components/experimental-features.jsx

Implements https://github.com/coreos/tectonic-installer/issues/794

frontend: Updates text for experimental operator

---

Documentation/admin/identity-management.md
Documentation/admin/ldap-user-management.md
Documentation/admin/onboard-admin.md
Documentation/admin/onboard-service-account.md
Documentation/admin/onboard-team.md
Documentation/admin/onboard-user.md

Per @sym3tri chunking my RBAC /LDAP work. In this I am adding / fixing the broken links. Request you to review and merge so that I can push the rest before the release. Thanks in advance.

Fix broken links in the RBAC/LDAP docs

---

Jenkinsfile
test/aws.tfvars

forked from https://github.com/coreos/tectonic-installer/pull/841

Fix 838 (2)

---

Jenkinsfile
test/aws.tfvars

[WIP] Jenkinsfile: randomly select region

---

Jenkinsfile

Fixes building branches like master.

Jenkins: Fall back to build id if change id doesn't exist.

---

config.tf

Includes https://github.com/coreos-inc/bridge/pull/1526

config.tf: Bumps console v1.6.2

---

config.tf

config.tf: bump etcd operator to v0.3.0

---

installer/frontend/components/aws-submit-keys.jsx

frontend: Sort ssh keys alphabetically.

---

installer/frontend/components/aws-tags.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js

Addresses https://github.com/coreos/tectonic-installer/issues/354

frontend: Autofocuses on newly added tag input

---

installer/frontend/components/ui.jsx

frontend: Use Alert component for styling errors.

---

installer/frontend/cluster-config.js
installer/frontend/components/users.jsx

frontend: Port credentials page to new forms. Add password confirmation.

---

config.tf

config.tf: bump k8s version

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.openstack-nova

moved from https://github.com/coreos/tectonic-installer/pull/876

config.tf: add a note about max size for the service CIDR

---

config.tf

config.tf: Bumps console to v1.6.3

---

installer/frontend/components/tf-poweron.jsx

Fixes an issue where margins were different between steps.

frontend: Don't make poweron steps substeps.

---

Documentation/hack/centos-workers.md
Documentation/install/aws/aws-terraform.md
Documentation/install/aws/index.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/troubleshooting/faq.md
Documentation/tutorials/installing-tectonic.md

Updates tectonic version in docs. Does not amend config.tf or
modules/update-payload/payload.json.

Documentation/*: Update version strings to 1.6.4-tectonic.1

---

Jenkinsfile

It looks like we don't destroy clusters if we timeout?

jenkins: timeouts

---

config.tf
modules/tectonic/resources/manifests/updater/kube-version-operator.yaml
modules/update-payload/payload.json

Also generate a new update-payload.

Update KVO to v1.6.4-kvo.3

---

modules/bootkube/resources/manifests/pod-checkpointer.yaml

This reverts commit ee9842145dffaf95dcd926e86105ddcacc729d04.

Fix checkpointer container name.

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

Adding back #915 now that the release branch has been cut.

Revert "Revert "Remove flock timeout from apiserver. (#915)" (#922)"

---

config.tf

Includes fixes for atomic writes and crashlooping.

pod-checkpointer: 4e7a7dab10bc4d895b66c21656291c6e0b017248

---

modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/resources/manifests/console/service.yaml

Also make it run as non-root.
Fixes #847

Change console to serve on port 8080.

---

modules/tectonic/resources/manifests/identity/deployment.yaml

modules/tectonic/resources: updating the identity deployment to be more resilient

---

installer/frontend/__tests__/protocols.js
installer/frontend/cluster-config.js
installer/frontend/components/cluster-type.jsx
installer/frontend/components/ui.jsx

- Add support for optional errorComponent in forms to customize rendering of errors.
- Change cluster selection page to use form & Connect.
Doesn't change behavior in any way.

frontend: Move cluster-type.jsx to new Connect/Form pattern.

---

modules/aws/etcd/nodes.tf
modules/aws/vpc/vpc-private.tf
modules/aws/vpc/vpc-public.tf
modules/aws/vpc/vpc.tf
platforms/aws/s3.tf

modules/aws: add missing cluster prefixes in tags

---

installer/scripts/awsutil.sh

Not sure why this is using HTTP.

installer/scripts: Use HTTPS in awsutil.sh

---

installer/frontend/components/base.jsx

Implements https://github.com/coreos/tectonic-installer/issues/904

Send GA event for next

---

Jenkinsfile
images/tectonic-builder/Dockerfile
release.groovy

We need awscli for assuming the limited role for #974.
cc @ggreer @kans

images/tectonic-builder: add awscli to image

---

modules/aws/ignition/ignition.tf
modules/aws/ignition/resources/s3-puller.sh

We should be using a variable for the awscli container image tag.
cc @kans @Quentin-M

modules/aws/ignition: template awscli

---

platforms/openstack/neutron/dns.tf
platforms/openstack/neutron/main.tf

openstack/neutron: fix selection of net port ip addresses

---

installer/scripts/release/make_release_tarball.sh

ported from https://github.com/coreos/tectonic-installer/pull/972/files#diff-281829ed1b96045d080592f46258d975R16

building: backports bundler fix

---

modules/tectonic/resources/tectonic.sh

modules/tectonic: don't exit on failure while waiting for cluster-info

---

Documentation/install/bare-metal/metal-terraform.md

Changed _Prerequsities_ to _Prerequisites_

Fixed misspelling in metal-terraform.md

---

installer/api/handlers_containerlinux.go
installer/frontend/server.js

- Increase AMI fetch timeout from 5 seconds to 10 seconds.
- Retry if AMI fetch fails.

Retry fetching AMI list

---

modules/openstack/nodes/secgroup.tf

modules/openstack: Open NodePort range on master security group

---

Documentation/install/vmware/vmware-terraform.md
README.md

Add documentation for scaling out VMware cluster. Also update main readme with VMware link

docs: platform vmware scale out

---

modules/azure/master-as/master.tf

Fixes the syntax error currently plaguing Azure in master.
cc: @s-urbaniak

Azure: remove multiplicity of ignition config

---

README.md

- Stop using "you" https://github.com/coreos/docs/blob/master/STYLE.md#english-style
- Simplify overly complex instructions
- Add vmware to alpha list

README: follow CoreOS writing style and other cleanups

---

Documentation/install/installer-windows.md

Doc/install/installer-win: Make links relative

---

modules/aws/ignition/resources/s3-puller.sh

modules/aws/ignition/resources/s3-puller.sh: add retries to avoid races

---

modules/aws/ignition/resources/s3-puller.sh

Follow-up to https://github.com/coreos/tectonic-installer/pull/1072#pullrequestreview-43933748.

modules/aws/ignition/resources/s3-puller.sh: remove non-existing var

---

Jenkinsfile
images/tectonic-builder/Dockerfile
installer/Makefile
installer/frontend/app.jsx
installer/frontend/aws-actions.js
installer/frontend/form.js
installer/frontend/nightwatch.json
installer/frontend/tectonic-ga.js
release.groovy

This makes it so we don't need to start X, avoiding any issues with multiple xvfbs running on a single worker.

GUI tests: Use headless Chrome

---

installer/frontend/.eslintrc
installer/frontend/components/header.jsx
installer/frontend/tectonic-ga.js
installer/frontend/utils.js
installer/frontend/yarn.lock

Implements https://github.com/coreos/tectonic-installer/issues/903

frontend: Ensures that GA events are sent only for release tags

---

platforms/openstack/neutron/dns.tf
platforms/openstack/neutron/main.tf

Fix some openstack/neutron bugs

---

Documentation/tutorials/first-app.md

I am correcting the instruction to delete to newly created service. It was kubectl delete deploy/simple-service svc/simple-service but it needs to be kubectl delete deploy/simple-deployment svc/simple-service

There is a mistake in the kubectl delete line.

---

installer/frontend/components/ui.jsx

Fixed GUI Header Dropdowns Overlapping

---

platforms/vmware/tectonic.tf

platforms/vmware: make license and pull secret optional

---

installer/api/api.go
installer/api/handlers_latest_release.go
installer/frontend/components/header.jsx

Implements https://github.com/coreos/tectonic-installer/issues/364

frontend: Fetches the latest release from github to display in the header

---

Documentation/troubleshooting/etcd-nodes.md
Documentation/troubleshooting/master-nodes.md
Documentation/troubleshooting/troubleshooting.md
Documentation/troubleshooting/worker-nodes.md
tests/smoke/aws/README.md
tests/smoke/aws/vars/aws-ca.tfvars
tests/smoke/aws/vars/aws-exp.tfvars
tests/smoke/aws/vars/aws.tfvars
tests/smoke/bare-metal/README.md
tests/smoke/bare-metal/packet/main.tf

tests/smoke: document manual execution, verification and troubleshooting

---

modules/tectonic/resources/tectonic.sh

... except self-hosted etcd
Fixes #1037

modules/tectonic: remove operators from experimental flag

---

Jenkinsfile
images/tectonic-builder/Dockerfile
release.groovy

This also consolidates all of the chrome installation into one layer.
cc @kans @ggreer

Jenkinsfile,images/tectonic-builder: use upstream BOM, don't sudo install

---

modules/tectonic/resources/manifests/stats-emitter.yaml

initContainers have exited beta in 1.6.

Move stats-emitter initContainer to final field.

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
installer/frontend/components/aws-define-nodes.jsx
platforms/aws/variables.tf

frontend: Adds helper text for etcd instances

---

installer/frontend/components/etcd.jsx

frontend: Hide AWS provisioning form for metal etcd

---

modules/bootkube/resources/manifests/kube-scheduler.yaml

Move critical pod annotation to correct place.

---

installer/api/handlers_terraform.go

api: Pretty-print JSON tfvars.

---

installer/frontend/components/header.jsx

Fixes the header as seen in Version: 1.6.6-tectonic.1-rc.1

frontend: Fixes logic to determine if a new version exists

---

modules/tectonic/resources/manifests/monitoring/tectonic-monitoring-auth-alertmanager-deployment.yaml
modules/tectonic/resources/manifests/monitoring/tectonic-monitoring-auth-prometheus-deployment.yaml

Fixes #1180 
@alexsomesan @s-urbaniak @Quentin-M 
/cc @robszumski @fabxc @mxinden @gouthamve

monitoring: add security context, resource requests and limits

---

tests/conformance/conformance.sh

This script will be implemented by a Jenkins job periodically every night.

tests: add a script to implement kubernetes conformance tests.

---

Documentation/install/bare-metal/requirements.md
Documentation/install/rhel/installing-workers.md
installer/frontend/components/header.jsx
modules/tectonic/resources/manifests/monitoring/tectonic-monitoring-auth-alertmanager-deployment.yaml
modules/tectonic/resources/manifests/monitoring/tectonic-monitoring-auth-prometheus-deployment.yaml

Merges commits from #1187, #1190, #1195, & #1204 into 1.6.6.

Merge release blockers into 1.6.6 branch

---

modules/tectonic/resources/tectonic.sh

Account for the case when `kubectl` command returns no resources

modules/tectonic/resources/tectonic.sh: update wait for pods logic

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-domain-validation.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/form.js
installer/frontend/tectonic-ga.js

GA expects the values to be integers, so appending the version and platform to the labels instead
Events recorded

frontend: Adds version and platform information to labels

---

installer/assets/frontend/css/styles.css

Fixes https://github.com/coreos-inc/tectonic-issues/issues/271

frontend: Adds width for the logo

---

Documentation/troubleshooting/bootkube_recovery_tool.md

Ref: https://github.com/coreos/tectonic-installer/issues/1288

troubleshooting/bootkube_recovery_tool.md: add user documentation on using bootkube recovery tool

---

Documentation/troubleshooting/bootkube_recovery_tool.md

Cherry pick 
#1290 troubleshooting/bootkube_recovery_tool.md: add user documentation on using bootkube recovery tool

Cherry picks troubleshooting documentation

---

installer/frontend/__tests__/fields.js

Test infly

---

config.tf
modules/update-payload/payload.json

#1309 config.tf/payload.json: Bump kvo to v1.6.7.

Cherry picks Bump kvo to v1.6.7.

---

installer/frontend/__tests__/fields.js

Test field extra data

---

installer/frontend/__tests__/fields.js

Test deep validation

---

Documentation/variables/openstack-neutron.md
examples/terraform.tfvars.openstack-neutron
platforms/openstack/neutron/nodes.tf
platforms/openstack/neutron/variables.tf

platforms/openstack/neutron: Allow flavor/image to be picked by name

---

modules/aws/etcd/ignition.tf
modules/aws/etcd/variables.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/openstack/etcd/ignition.tf
modules/openstack/etcd/variables.tf
modules/vmware/etcd/ignition.tf
modules/vmware/etcd/variables.tf
platforms/aws/main.tf
platforms/openstack/neutron/main.tf
platforms/vmware/main.tf

Cherry picks 
#1337 modules/*/etcd: pass client certs to standalone etcd

Cherry pick certs to standalone etcd fix

---

Documentation/install/bare-metal/index.md

Doc/install/b-m/index: Update req'd CL version

---

Jenkinsfile

Currently we are using a custom terraform version. Among others it increases time outs in terraform itself. In order to stay in sync with upstream terraform we want to do nightly tests with vanilla terraform. In order to be able to accomplish this, we have to make the tectonic builder-image configurable.

tests: Make tectonic builder-image configurable

---

Documentation/admin/bare-metal-scale.md

tectonic_metal_worker_macs and tectonic_metal_worker_names needs to be adjusted on scale up as well. Also cleanup command for terraform plan and apply

Docs: metal-scale updates

---

installer/frontend/app.jsx
installer/frontend/components/restore.jsx

frontend: After restoring progress file, skip to next screen of wizard

---

config.tf

config.tf: update tectonic versions

---

installer/assets/frontend/css/styles.css

frontend: Remove modal outline when focussed

---

installer/scripts/release/common.env.sh
installer/scripts/release/get_terraform_resources.sh
installer/scripts/release/make_release_tarball.sh

This commit adds the Terraform license to the release tarball.
Fixes: #1207 
cc @amrutac @sym3tri @Quentin-M

installer/scripts/release: add Terraform license

---

Jenkinsfile
images/tectonic-builder/Dockerfile
images/tectonic-installer/Dockerfile
release.groovy
tests/conformance/conformance.sh

cc @ggreer @kans
fixes part of https://github.com/coreos/tectonic-installer/issues/835

Jenkinsfile,images: bump to Go 1.8.3

---

Documentation/admin/ingress.md
config.tf

Fixes NGINX [CVE-2017-7529](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7529)

Update nginx ingress controller to 0.9-beta.11

---

installer/frontend/components/restore.jsx

Also capitalized "P" of "progress" in header.

frontend: Add explanation text to restore modal

---

Jenkinsfile

* Wrap clean up steps of tests, executed by root, inside *try catch
finally* blocks. This way whenever *plan* or *apply* fails, the cleanup
steps are still executed.
* Remove `-e` (# exit immediately when a command fails) from shebang in
clean up steps, so if one clean up step fails others are still executed.

tests: Prevent *permission denied* errors

---

installer/assets/frontend/css/styles.css
installer/frontend/components/loader.jsx
installer/frontend/components/restore.jsx

frontend: Add loading spinner to restore modal

---

installer/pkg/terraform/executor.go

Remove logs directory from `assets.zip`. Logs can either be retrieved directly from the console, or from `terraform {plan,apply}` if running the installer manually.
Tests: went through installer GUI and downloaded `assets.zip` after making changes and checked absence of `logs/`
Fixes #1412

installer/pkg/terraform: remove logs dir from assets.zip

---

config.tf
modules/tectonic/resources/manifests/heapster/deployment.yaml

config.tf: bump image deps (incl. hyperkube 1.7.1)

---

Jenkinsfile
release.groovy
tests/conformance/conformance.sh

*: bump tectonic-builder to v1.35

---

config.tf

kenc: bump to 0.0.2

---

Jenkinsfile
installer/Makefile

Try to fixes the permission denied in Jenkins wiping the workspace after finish the job
* add terminal color
* Clean the work space after finish each step

tests/ci: Wipe the workspace when finish the build. to fix the permission denied issue

---

Documentation/install/aws/requirements.md
Documentation/install/aws/troubleshooting.md

Requirements and troubleshooting guidelines relating to installer connectivity to Tectonic ingress ELB causing failed installs.
\cc @robszumski @joshix

docs: provide guidance for internal VPC installs

---

changes.md

changes.md: added 1.6.4, 1.6.7, and current changes

Changelog updates

---

modules/update-payload/assets.tf

Also plans to add a check in jenkins job for each PR so 'make payload'
won't get broken.

Fix undefined variables in upload-payload/assets.tf.

---

installer/cmd/installer/platforms.go
installer/frontend/components/cluster-type.jsx
installer/frontend/platforms.js
installer/frontend/server.js

Also clean up code a bit
- Remove `isTerraform()` since everything is Terraform now.
- Remove `SELECTED_PLATFORMS` sorting since it is not used.
Fixes: #1285

frontend: Add AWS and Bare Metal options under "Advanced Installer"

---

installer/frontend/components/bm-nodeforms.jsx
installer/frontend/validate.js

- Fix duplicate MAC address validation that did not catch all cases
- Fix message for empty MAC address case
- Add duplicate hostname validation error
- Add validation error for master / worker node clashes
Before | After
--- | ---

frontend: Four Bare Metal nodes validation fixes

---

config.tf
modules/update-payload/payload.json

PR against 1.6.7 branch.
/cc @robszumski @aaronlevy @diegs @Quentin-M @rithujohn191

Bump TCO to allow minor version upgrade to 1.7.

---

modules/bootkube/assets.tf

bootkube/tls: fix bootstrap secrets for external etcd cluster

---

changes.md

changes.md: update for 1.6.7-tectonic.2

---

config.tf
modules/update-payload/payload.json

CHANGELOG:
- Add support to get a specific version of payload
- Add support to list all payloads in order
- Bump operator client
- Refactor on TCO and allow TCO to upgrade through every intermediate versions
- Allow TCO to upgrade across minor versions

config.tf, payload.json: Bump TCO to 0.4.0.

---

modules/aws/ignition/ignition.tf
modules/aws/master-asg/elb.tf
modules/aws/master-asg/master.tf
modules/aws/master-asg/outputs.tf
modules/bootkube/assets.tf
modules/bootkube/outputs.tf
modules/bootkube/tls_etcd.tf
modules/bootkube/tls_kube.tf
modules/dns/route53/tectonic.tf
modules/net/calico-network-policy/assets.tf
modules/net/calico-network-policy/outputs.tf
modules/tectonic/assets.tf
modules/tectonic/crypto.tf
platforms/aws/main.tf
platforms/aws/route53.tf
platforms/aws/s3.tf

This pull request is addressing #993

AWS - Replaced hyphens with underscores in .tf files 

---

CONTRIBUTING.md

I hit a minor bump in contributing on this PR https://github.com/coreos/tectonic-installer/pull/1449
I thought being a bit more explicit about the 2 projects you need to `go get` and what `make structure-check` does for docs and examples might be helpful to other first-time contributors.

contributing: Make the instructions a bit more explicit for docs and examples

---

Documentation/troubleshooting/bootkube_recovery_tool.md

ref: https://github.com/coreos/tectonic-installer/issues/1428

troubleshooting/bootkube_recovery_tool.md: add clean up steps

---

installer/frontend/components/tf-poweron.jsx

CSS class `wiz-launch__progress` is not defined.

frontend: Minor - Remove unnecessary div

---

installer/frontend/cluster-config.js

Fixes https://coreosdev.atlassian.net/browse/TECREL-27

frontend: Pass retry to backend.

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/metal.json

frontend: Update example files to fix frontend tests.

---

modules/update-payload/upload-payload.sh

Change from aws dev account to aws prod account.
After next release, I will recreate all old packages from omaha server to point to the [new location](https://s3-us-west-1.amazonaws.com/tectonic-update-payload-prod).

upload-payload.sh: Update S3 localtion for the payload.

---

README.md

ci/tests: fix build status in the readme.md

---

modules/azure/master-as/ignition-master.tf
modules/azure/master-ss/api-lb.tf
modules/azure/master-ss/console-lb.tf
modules/azure/master-ss/ignition-master.tf
modules/azure/master-ss/master.tf
modules/azure/vnet/lb-api.tf
modules/azure/vnet/lb-console.tf
modules/dns/azure/records.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf

Azure - Replaced hyphens with underscores for Azure

---

modules/update-payload/sign-payload.sh

Follow up with https://github.com/coreos/tectonic-installer/pull/1512.

modules/update-payload/sign-payload.sh: fix shellcheck issue

---

config.tf
modules/tectonic/resources/manifests/monitoring/prometheus-k8s.yaml
modules/update-payload/payload.json

Cherry-picks:
- https://github.com/coreos/tectonic-installer/pull/1571
- https://github.com/coreos/tectonic-installer/pull/1574
- https://github.com/coreos/tectonic-installer/pull/1572
Then need to rebase https://github.com/coreos/tectonic-installer/pull/1527 once again.

Bump KVO, TMO, Console

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx
installer/frontend/components/ui.jsx

Fixes #1514
Screenshot also shows menu item hover style (cursor not captured).

frontend: Replace Apply Succeeded info box with actions menu

---

modules/azure/master-as/ignition-master.tf
modules/azure/worker-as/ignition-worker.tf
modules/net/ignition/ignition.tf
modules/net/ignition/outputs.tf
modules/net/ignition/resources/tx-off.service

Cherry-picks https://github.com/coreos/tectonic-installer/pull/1586

modules/azure: disable TX checksum offloading

---

platforms/metal/matchers.tf

fixes: https://github.com/coreos/tectonic-installer/issues/1492
cc @coresolve @Quentin-M @alexsomesan

platforms/metal: disable etcd member when using external etcd

---

config.tf

Fixes https://coreosdev.atlassian.net/browse/CONSOLE-138

Bump Tectonic Console to v1.8.6.

---

Documentation/install/bare-metal/index.md

I'm cleaning up and clarifying the bare metal docs. This is just the first page.

docs: updating bare metal install index.

---

platforms/metal/matchers.tf
platforms/metal/profiles.tf
platforms/metal/tectonic.tf

This pull request is addressing #993

Bare metal - Replaced hyphens with underscores in .tf files

---

installer/frontend/actions.js
installer/frontend/app.jsx
installer/frontend/components/base.jsx
installer/frontend/components/restore.jsx
installer/frontend/components/submit-definition.jsx
installer/frontend/components/success.jsx
installer/frontend/components/ui.jsx
installer/frontend/nav.jsx
installer/frontend/package.json
installer/frontend/trail.js
installer/frontend/yarn.lock

Advancing to the next wizard screen when the enter key is pressed only applies to inputs of type text, password or number.
Fixes #1257

frontend: Upgrade react-router to v4, advance to next screen when enter key is pressed

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx

frontend: Start Installation screen - destroy UI changes and code cleanup

---

modules/update-payload/make-update-payload.sh
modules/update-payload/payload.json

Also makes sure kubernetes get updated first.

modules/update-payload: Make sure TCO always updates itself first.

---

modules/azure/master-as/ignition-master.tf
modules/azure/udev-rules/outputs.tf
modules/azure/udev-rules/resources/66-azure-storage.rules
modules/azure/udev-rules/udev.tf
modules/azure/worker-as/ignition-worker.tf
modules/azure/worker-as/resources/66-azure-storage.rules

Cherry-picks https://github.com/coreos/tectonic-installer/pull/1618 in the 1.7.1 release branch.

azure: add udev rules needed by k8s cloudprovider (#1618)

---

config.tf

Getting https://github.com/coreos-inc/kube-version-operator/pull/216 in.

config.tf: update node-agent to c021a49

---

config.tf
modules/update-payload/payload.json

Cherry-picking https://github.com/coreos/tectonic-installer/pull/1646

kvo: update to v1.7.1-kvo.6

---

installer/frontend/components/aws-cloud-credentials.jsx

Fixes a bug where STS tokens are marked as invalid.

frontend: AWS access keys do not always begin with AK.

---

installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx

Also clean up the progress bar CSS.

frontend: Switch progress bar to gray if Terraform apply fails

---

tests/jenkins-jobs/maintenance/tag_clean_aws_grafiti_job.groovy

Fixes some missing and wrong parameters
cc @mxinden

tests/ci: fix missing paramenters and wrong bash syntax

---

Documentation/install/azure/azure-terraform.md

(derived from Azure tutorial work in progress)

Doc/install/azure/azure-terraform: Expand azure install doc & style cleanup

---

installer/frontend/components/cluster-type.jsx

frontend: Add link to Bare Metal requirements doc

---

tests/jenkins-jobs/maintenance/tag_clean_aws_grafiti_job.groovy

tests/ci: add missing label to restrict where to run

---

config.tf

config.tf: bump hyperkube to 1.6.8

---

installer/frontend/components/cidr.jsx

Cherry-picks https://github.com/coreos/tectonic-installer/pull/1684 in 1.7.1.

frontend: Fix tooltip preventing editing of CIDR inputs

---

modules/openstack/etcd/output.tf
modules/openstack/nodes/output.tf
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/network.tf

This is a WIP associated with the issue [1071](https://github.com/coreos/tectonic-installer/issues/1071) for OpenStack provider.
@coreypobrien, @lblackstone, @jamiehannaford : would you guys be able to test the changes?

Remove extra "[]" from OpenStack templates

---

Documentation/variables/config.md
config.tf

config.tf: update update channel to tectonic-1.7-production

---

installer/assets/frontend/css/styles.css
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/base.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/tf-poweron.jsx
installer/frontend/components/ui.jsx

Lots of whitespace changes, so view with `?w=1`.
- Fix Starting Tectonic install step state on initial render
- Change install step icon for failed state
- Refactoring

frontend: Install UI fixes and clean up

---

Documentation/install/vmware/vmware-terraform.md
modules/vmware/node/variables.tf

clean node variables descriptions and update documentation to note ssh-agent setup

docs: vmware ssh-agent documentation

---

modules/update-payload/make-update-payload.sh
modules/update-payload/payload.json

Thanks @abhinavdahiya for catching this!

make-update-payload.sh Fix the payload for kubernetes desired version.

---

modules/openstack/secgroups/output.tf

modules/openstack: terraform fmt openstack

---

Documentation/platform-lifecycle.md

Co-authored with @robszumski 
Supersedes https://github.com/coreos/tectonic-installer/pull/1133 and makes additional changes to better reflect reality.

Documentation: update lifecycle doc to be more accurate

---

modules/tectonic/resources/tectonic.sh

modules/tectonic: Wait for CRD's to exist instead of TPR's

---

installer/frontend/components/tf-poweron.jsx

Previously if terraform retry failed immediately (eg a 500 came back), we would show no error message. This fixes the problem.

frontend: Show error if retry tf apply fails.

---

installer/frontend/nightwatch.json
installer/frontend/ui-tests/commands/setField.js
installer/frontend/ui-tests/pages/awsCredentialsPage.js
installer/frontend/ui-tests/pages/clusterDnsPage.js
installer/frontend/ui-tests/pages/clusterInfoPage.js
installer/frontend/ui-tests/pages/consoleLoginPage.js
installer/frontend/ui-tests/pages/matchboxAddressPage.js
installer/frontend/ui-tests/pages/matchboxCredentialsPage.js
installer/frontend/ui-tests/pages/networkConfigurationPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/platformPage.js
installer/frontend/ui-tests/tests/awsInstaller.js
installer/frontend/ui-tests/tests/bareMetalInstaller.js

First set of extra checks and clean up for Nightwatch tests. More to follow.

frontend/tests: Nightwatch tests improvements

---

Documentation/install/bare-metal/metal-terraform.md
Documentation/install/bare-metal/requirements.md

Upstream fix for coreos-inc/coreos-pages#1800 and coreos-inc/coreos-pages#1801

docs: Fix links to DNS and Matchbox

---

installer/frontend/components/cidr.jsx

frontend: Add comma thousands separators for IP address count

---

installer/frontend/components/users.jsx
installer/frontend/validate.js

Previously, we were using a regex that only allowed a subset of valid emails.
Now this will work with email addrs that are non-ascii.

frontend: Better validation of email addresses.

---

README.md

- Link to RHEL docs
- Note that Container Linux is default
- Spell out the cloud providers

README: some minor tweaks

---

modules/openstack/nodes/ignition.tf

- Disable root login
- Restrict to public key auth

modules/openstack: Create custom sshd config

---

installer/frontend/nightwatch.json
installer/frontend/ui-tests/pages/clusterDnsPage.js
installer/frontend/ui-tests/pages/consoleLoginPage.js
installer/frontend/ui-tests/pages/defineMastersPage.js
installer/frontend/ui-tests/pages/defineWorkersPage.js
installer/frontend/ui-tests/pages/keysPage.js
installer/frontend/ui-tests/pages/matchboxAddressPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/nodesPage.js
installer/frontend/ui-tests/pages/platformPage.js
installer/frontend/ui-tests/tests/awsInstaller.js
installer/frontend/ui-tests/tests/bareMetalInstaller.js
installer/frontend/ui-tests/utils/awsInstallerInput.js
installer/frontend/ui-tests/utils/terraformTfvars.js
installer/frontend/ui-tests/utils/wizard.js

Stop using the .progress input file (was only used for one value).
Add a few more checks and minor clean ups.

frontend/tests: More Nightwatch test improvements

---

installer/frontend/components/base.jsx

frontend: Fix sidebar "Boot Cluster" links for bare metal

---

installer/frontend/ui-tests/commands/setField.js
installer/frontend/ui-tests/pages/networkConfigurationPage.js
installer/frontend/ui-tests/pages/networkingPage.js

Use chaining and always clear the field value before calling setValue().

tests/frontend: Fix and simplify setField() helper

---

tests/rspec/lib/cluster.rb

Added the 3times retry statement to the apply section; this already done at the destroy section.

tests: add 3times loop at apply section

---

config.tf

* Updates CNI plugins to v0.6.0
Related:
* https://github.com/kubernetes-incubator/bootkube/pull/693
* https://github.com/coreos/flannel-cni/pull/3
* https://quay.io/repository/coreos/flannel-cni?tab=tags

config.tf: Update flannel-cni to v0.2.0

---

tests/jenkins-jobs/README.md
tests/jenkins-jobs/tectonic_coformance_tests_job.groovy

tests/ci: add tectonic-conformance-tests to jenkins code

---

installer/api/handlers_terraform.go
installer/pkg/terraform/executor.go

Regression introduced in #1660, specifically https://github.com/coreos/tectonic-installer/pull/1660/files#diff-28c6dee8dd102cf55d7b010e938c9d6aR65

Fix v1.7.3

---

Jenkinsfile
tests/jenkins-jobs/README.md
tests/jenkins-jobs/tectonic_installer_hyperkube_trigger_job.groovy

tests/ci: Add trigger and code in jenkinsfile to replace Hyperkube image

---

tests/jenkins-jobs/tectonic_installer_hyperkube_trigger_job.groovy

tests: fix hyperkube test description

---

modules/update-payload/make-update-payload.sh

Missed this spot while updating to Terraform 0.10.x

make-update-payload.sh should run init before apply

---

images/tectonic-builder/Dockerfile

Builder image - bump Go to 1.9

---

tests/jenkins-jobs/tectonic_builder_docker_image.groovy
tests/jenkins-jobs/tectonic_installer_hyperkube_trigger_job.groovy
tests/jenkins-jobs/tectonic_smoke_test_docker_image_job.groovy

fixes the issue which the job dsl complaints about the class does not exist. and should not exist because it is not class :P
I ran all the jobs in Jenkins and all are working well now. this PR is to update the repo

tests/ci: make friends with job dsl

---

config.tf
modules/update-payload/payload.json

config.tf: updated version string for 1.7.3 patch release

---

modules/aws/worker-asg/worker.tf

JIRA: https://coreosdev.atlassian.net/browse/INST-219

aws: Lock down AWS worker IAM role

---

Jenkinsfile
config.tf
platforms/aws/main.tf
platforms/azure/main.tf
platforms/openstack/neutron/main.tf
platforms/vmware/main.tf

config: pin versions of terraform modules

---

Jenkinsfile

- Saw some errors when trying to delete the workspace and fail but the tests passed. and it should not mark the build as a failure.
- Also saw some issues when checkout the repo. With his we checkout only one time and use the same files in all tests.

tests/ci: checkout just one time and changed deletedir() to cleanWS

---

config.tf
modules/update-payload/payload.json

This needs fresh install and upgrade testing. Release blocker, DO NOT SHIP WITHOUT.
cc @crawford @squat @squeed @Quentin-M

config.tf: Update tectonic-cluo-operator to v0.2.0

---

config.tf
modules/update-payload/payload.json

The usual upgrade stuff.
/cc: @sym3tri @Quentin-M

Bump Hyperkube to 1.7.5 (and all the related versions).

---

tests/conformance/conformance.sh

Could someone with Jenkins access try running this? Looked okay locally.

Upgrade tectonic-builder to v1.39 in conformance tests

---

config.tf

Cherry-picked the PR off master

config.tf: bump dex to v2.7.1

---

Jenkinsfile

tests/ci: [INST-139] GUI tests in a specific stage and run always

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/metal.json
installer/frontend/__tests__/examples/tectonic-aws.progress
installer/frontend/cluster-config.js
installer/frontend/components/etcd.jsx
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/ui-tests/pages/nodesPage.js

frontend: Remove self-hosted etcd option from GUI

---

Jenkinsfile
Makefile
README.md
images/tectonic-smoke-test-env/Dockerfile
tests/rspec/.rubocop.yml
tests/rspec/Gemfile
tests/rspec/Gemfile.lock
tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/azure_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/name_generator.rb
tests/rspec/lib/pages/base_page.rb
tests/rspec/lib/pages/login_page.rb
tests/rspec/lib/password_generator.rb
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/webdriver_helpers.rb

JIRA TICKET: https://coreosdev.atlassian.net/browse/INST-394

tests/ci: Add initial console tests

---

config.tf

cc @s-urbaniak @Quentin-M @diegs 
fixes: TECREL-94

config.tf: bump hyperkube v1.7.5_coreos.1

---

config.tf
modules/update-payload/payload.json

config.tf: kvo v1.7.5-kvo.6

---

config.tf

config.tf: bump hyperkube to 1.7.6

---

installer/frontend/components/ui.jsx

frontend: Make dropdown "placeholder" style different from normal text

---

config.tf

config.tf: bump dns

---

config.tf

config.tf: bump dns (#2004)

---

modules/aws/etcd/dns.tf
modules/aws/etcd/ignition.tf
modules/aws/etcd/variables.tf
modules/azure/etcd/ignition.tf
modules/azure/etcd/output.tf
modules/azure/etcd/variables.tf
modules/dns/route53/etcd.tf
modules/ignition/assets.tf
modules/ignition/etcd.tf
modules/ignition/outputs.tf
modules/ignition/resources/dropins/40-etcd-cluster.conf
modules/ignition/resources/services/coreos-metadata.service
modules/ignition/variables.tf
modules/openstack/etcd/ignition.tf
modules/openstack/etcd/variables.tf
modules/tls/etcd/main.tf
modules/vmware/etcd/ignition.tf
modules/vmware/etcd/variables.tf
platforms/aws/main.tf
platforms/aws/tectonic.tf
platforms/azure/main.tf
platforms/azure/tectonic.tf
platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/matchers.tf
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/network.tf
platforms/vmware/main.tf

This unifies the etcd service unit to the ignition module.
Fixes #INST-405
Side-effect of the unification: This also fixes the long-outstanding #318

modules/*: unify etcd service unit

---

installer/frontend/cluster-config.js
installer/frontend/components/certificate-authority.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/ui.jsx

This change causes the following to be added to the `.progress` file when the CA Certificate and CA Private Key fields are not set.
```
"clusterConfig": {
...
"ignore": {
...
"caCertificate": true,
"caPrivateKey": true
```

frontend: Migrate CertificateAuthority from WithClusterConfig to Connect and use Radio component

---

examples/terraform.tfvars.gcp

cc @alexsomesan here's a quick one to re-sync the docs and examples directories.

examples: run `make examples`

---

config.tf
modules/update-payload/payload.json

Also regenerate update payload.

config.tf: kvo to v1.7.5-kvo.7

---

Jenkinsfile

Bump to pick up TF 0.10.7 for CI.
/cc: @sym3tri

Bump CI images to TF 0.10.7

---

config.tf

Bump Tectonic Console to v2.1.1

---

config.tf
modules/update-payload/payload.json

Also regenerate update payload.

config.tf: update kvo to v1.7.5-kvo.10

---

config.tf

config.tf: kvo to v1.7.5-kvo.10

---

README.md
tests/README.md

- Move testing documentation into `tests/README.md`
- Extend PR trigger documentation with triggering by platform label
- Remove outdated documentation on folder structure

tests: Improve testing documentation

---

config.tf

A few bug fixes and styling tweaks. Also allows editing service monitors, filtering more resource types, and a few other UI niceties.

Bump console to v2.2.1.

---

tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy

I still had a hard coded PR id in the code. This will be fixed with this PR.

tests: Programmatically curl specific PR id

---

installer/frontend/.eslintrc
installer/frontend/__tests__/fields.js
installer/frontend/__tests__/protocols.js
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/header.jsx
installer/frontend/components/tectonic-license.jsx
installer/frontend/components/ui.jsx
installer/frontend/fields.js
installer/frontend/server.js
installer/frontend/trail.js

Also disallow any blank lines at the beginning or end of a file.

frontend: eslint - disallow multiple blank lines

---

config.tf

Fixes https://coreosdev.atlassian.net/browse/TECREL-113

Bump console to v2.2.3.

---

platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf

Report the correct platform in statistics.
cc @dcondomitti @alexsomesan

platforms/{metal,openstack}: report platform in stats

---

Jenkinsfile

We have been facing a lot of `permission denied` issues due to tests
executed as root that did not clean up after themselves before exiting.
Instead of relying on other tests to clean up, tests should clean up before
each execution to make sure this doesn't block them anymore.

tests: Clean workspace with root before any test execution

---

modules/tls/etcd/main.tf
modules/tls/identity/self-signed/main.tf
modules/tls/ingress/self-signed/main.tf
modules/tls/kube/self-signed/api.tf
modules/tls/kube/self-signed/ca.tf
modules/tls/kube/self-signed/kubelet.tf

modules/tns: extend TLS validity period to 3 yrs

---

config.tf

Fixes: INST-530
cc @s-urbaniak

config.tf: pin external provider to 1.0.0

---

tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy

In the first time build Jenkins does not know anything about which
parameters need to run. This fix is a workaround for the Jenkins issue.
JIRA: https://coreosdev.atlassian.net/browse/INST-533

test: fix first time build issue in jenkins

---

modules/azure/vnet/vnet-subnets.tf

Prevents issue where when providing an external vnet id errors are thrown

azure/vnet: custom vnet error when using module

---

installer/frontend/__tests__/examples/tectonic-aws-vpc.progress
installer/frontend/__tests__/examples/tectonic-baremetal.progress
installer/frontend/cluster-config.js

Not sure what this was being used for originally, but it appears to no longer be used.

frontend: Remove unused UPDATER field

---

config.tf

* https://github.com/coreos/container-linux-update-operator/releases/tag/v0.4.0
* https://github.com/coreos-inc/tectonic-cluo-operator/releases/tag/v0.2.2
cc @sudhaponnaganti

config.tf: Update tectonic-cluo-operator to v0.2.2

---

tests/rspec/lib/cluster.rb

In the loop of checking masters to complete the bootstrapping process,
this patch adds a simple log of the master ip addresses that are being
checked. In addition it removes the final `elapsed` reference which was
not defined in that scope.
@kalmog Thanks for pointing this out to me.

tests: Log master ip addresses while checking for cluster bootstrapping

---

config.tf

cc @aaronlevy @s-urbaniak @alexsomesan @sym3tri

config.tf: bump hyperkube to 1.7.9

---

modules/bootkube/resources/manifests/kube-dns.yaml
modules/bootkube/resources/manifests/pod-checkpointer.yaml
modules/net/calico/resources/manifests/kube-calico.yaml
modules/net/canal/resources/manifests/kube-calico.yaml
modules/tectonic/resources/manifests/heapster/deployment.yaml

Removing the CriticalAddonsOnly toleration as it isn't being used.

Removed the CriticalAddOn toleration as it is not used

---

Jenkinsfile

test: pin container_linux_version with 1520.6.0 for now

---

tests/rspec/lib/cluster.rb

JIRA: https://jira.prod.coreos.systems/browse/INST-231

tests: enable TF_LOG when retrying apply or destroy

---

Jenkinsfile

test: remove hard coded CL version

---

config.tf

Fixes https://github.com/coreos-inc/bridge/pull/1847

Bump console to v2.3.2.

---

config.tf

Cherry-pick the version bump from 1.7.9 branch to master.

config.tf: Bump kvo to the latest.

---

config.tf

Apply the change to master as well.

config.tf: Bump kvo to bump console.

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/aws_support.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/ssh.rb
tests/rspec/lib/with_retries.rb

fixes: https://jira.prod.coreos.systems/browse/INST-544

tests: add with_retry and small refactor

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

as per https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use
Fixes INST-526
Blocked by CORS-342

modules/bootkube: update admission-control to recommeded set

---

installer/assets/frontend/css/styles.css
installer/frontend/cluster-config.js
installer/frontend/components/aws-define-nodes.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/ui.jsx
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/validate.js

For both AWS and bare metal.
---

frontend: Change etcd address field from host input to URL input

---

Jenkinsfile

Need an overview of all te environment variables for the logstash project.

tests: get overview of all env variables

---

installer/assets/frontend/css/styles.css
installer/frontend/cluster-config.js
installer/frontend/components/aws-define-nodes.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/ui.jsx
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/validate.js

Cherry pick 3 related frontend changes for external etcd.

Cherry pick #2253, #2270 and #2301

---

config.tf

Hides ALM menu and has a couple bug fixes.

Bump console to v2.3.4.

---

Jenkinsfile

The `reportStatusToGithub` step relies on a script inside the
repository. This patch makes sure, the repository is checked out at the
point of execution.
`printLogstashAttributes` relies on `checkout scm` as well as
`printLogstashAttributes` accesses scm related variables like
`env.CHANGE_ID`.

tests: Checkout scm before reporting to Github and log vars

---

platforms/vmware/main.tf

`etcd_initial_cluster_list` and `etcd_tls_enabled ` vars were missing.

platform/vmware: Add missing ignition variables for etcd

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Added the feature to upload the consoleText to the S3 bucket.

tests: added the logstash upload feature

---

tests/jenkins-jobs/tectonic_installer_multibranch_job.groovy

Testing out whether this fixes some of our git issues on our multibranch project.

tests: Decrease periodic trigger for multibranch pipeline

---

config.tf

This contains the new console (v2.3.4)

config.tf: Bump kvo to v1.7.9-kvo.5

---

Documentation/variables/config.md
config.tf
examples/terraform.tfvars.aws
examples/terraform.tfvars.azure
examples/terraform.tfvars.gcp
examples/terraform.tfvars.metal
examples/terraform.tfvars.openstack-neutron
examples/terraform.tfvars.vmware
modules/tls/etcd/signed/main.tf
modules/tls/etcd/signed/variables.tf
modules/tls/identity/self-signed/main.tf
modules/tls/identity/self-signed/variables.tf
modules/tls/ingress/self-signed/main.tf
modules/tls/ingress/self-signed/variables.tf
modules/tls/kube/self-signed/api.tf
modules/tls/kube/self-signed/ca.tf
modules/tls/kube/self-signed/kubelet.tf
modules/tls/kube/self-signed/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/gcp/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

module/tls: Make TLS validity period configurable

---

tests/rspec/lib/cluster.rb

tests: Retry plan 3 times

---

Jenkinsfile
tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/metal_support.rb

fixes: https://jira.prod.coreos.systems/browse/INST-622

tests: add docker logs

---

tests/jenkins-jobs/scripts/report-status-to-github.sh

tests: change reported spec names

---

config.tf

Adds a fix for a javascript error when editing/duplicating role bindings: https://github.com/coreos-inc/bridge/pull/1885

Bump console to v2.3.5.

---

Jenkinsfile
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/metal_support.rb

and also fix the error: cant modify frozen strings and change the logs folder

test: fix typo / some error in frozen strings and save archiveArtifacts

---

config.tf

Many improvements: https://github.com/coreos-inc/bridge/compare/v2.3.4...v2.4.0, including support for some k8s v1.8 stuff like cron jobs.

Bump console to v2.4.0.

---

config.tf

* Update tectonic-torcx to v0.2.0
* Add Docker runtime mappings

config.tf: Update tectonic-cluo-operator to v0.2.5

---

modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-proxy.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

This makes the annotations consistent for the various components.

bootkube: fix up managed-by annotations.

---

modules/ignition/resources/kubernetes/runtime-mappings.yaml

modules/ignition: remove comments to make user-data fit

---

modules/dns/designate/etcd.tf
modules/dns/designate/master.tf
modules/dns/designate/tectonic.tf
modules/dns/designate/variables.tf
modules/dns/designate/worker.tf
modules/dns/route53/etcd.tf
modules/dns/route53/master.tf
modules/dns/route53/tectonic.tf
modules/dns/route53/variables.tf
modules/dns/route53/worker.tf
platforms/aws/main.tf
platforms/openstack/neutron/main.tf
tests/rspec/lib/aws_cluster.rb

sync var names for better coherency

---

config.tf

Cherry-pick the latest 1.7.9 version bump into master branch

config.tf: Bump kvo and kubernetes version.

---

Jenkinsfile

we observed some issues in the initial steps of the Jenkins pipeline regarding the stash the original commit. since this is just a hash and not a file or other thing it is easier to create a variable and use that.

test/ci: replace stash with env variable

---

Jenkinsfile
tests/rspec/lib/cluster.rb
tests/rspec/lib/k8s_conformance_tests.rb
tests/rspec/lib/shared_examples/build_folder_setup.rb
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/tfvars_file.rb
tests/rspec/spec/aws/vpc_internal_spec.rb
tests/rspec/spec/azure/private_external_spec.rb
tests/rspec/spec/metal/basic_spec.rb

* test: add tests to check scale worker node
* test: remove scaleup tests for azure

test: add tests to check scale worker node (#2305)

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Put all the information in the filename and let Logstash parse through the filename

tests: change logstash logic

---

modules/bootkube/resources/manifests/cluster-config.yaml
modules/tectonic/resources/manifests/cluster-config.yaml
modules/tectonic/resources/tectonic.sh

This reverts commit 81001cfc6671c94c161363a89d80a8ad0f62144c.

Revert "bootkube/tectonic: remove cluster-config."

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh
tests/rspec/lib/cluster.rb

Added the feature that Terraform logs are uploaded to S3 as well.
All files are temporary stored in the 'templogfiles' directory.

tests: log upload feature

---

config.tf
modules/tectonic/resources/manifests/updater/operators/kube-version-operator.yaml

Also update KVO manifest to use YAML upgrade spec.

1.8.2: kvo to v1.8.2-kvo.2

---

tests/rspec/lib/metal_support.rb
tests/rspec/spec/metal/basic_spec.rb

tests/ci: wait for terraform provide the ipxe and then start the nodes

---

tests/jenkins-jobs/tectonic_installer_nightly_trigger.groovy
tests/jenkins-jobs/tectonic_installer_nightly_trigger_with_gcp.groovy

tests/ci: remove gcp tests from nightly but add in a stand alone job

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Solves the problem of empty branch names.

tests: change jenkins git sb variable

---

modules/update-payload/assets.tf

Reverts coreos/tectonic-installer#2475

Revert "modules/update-payload: fix payload gen failure introduced by #2465"

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/azure_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/gcp_cluster.rb
tests/rspec/lib/metal_cluster.rb
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/ssh.rb
tests/smoke/bare-metal/vars/metal.tfvars.json

tests: add ssh proxy to be able to collect logs from workers and other instances

---

config.tf

Bump console to v2.6.1.

---

tests/rspec/lib/pages/login_page.rb

my proposed changes here: https://github.com/coreos-inc/bridge/pull/1940 will fix this issue

tests: fix console tests

---

config.tf

Fixes the Firefox dropdown bug (https://jira.coreos.com/browse/TECREL-132)

Bump console to v2.6.2.

---

tests/README.md

@sym3tri can you please review? thanks 😄

tests: add doc to describe how to run conformance tests in a running cluster

---

tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_support.rb

tests: save kubectl get ev logs

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-alm.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml
modules/tectonic/resources/tectonic.sh
modules/update-payload/assets.tf
tests/rspec/lib/pages/login_page.rb

I haven't tested this because I do not know how.

operators: Install the tectonic-alm-operator under TVO management

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/azure_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/gcp_cluster.rb
tests/rspec/lib/metal_cluster.rb
tests/rspec/lib/tfstate_file.rb

tests: collect etcd logs

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
modules/aws/etcd/nodes.tf
modules/aws/etcd/variables.tf
platforms/aws/main.tf
platforms/aws/variables.tf

aws: add etcd iam custom role

---

installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/aws.progress
installer/frontend/ui-tests/output/aws-custom-vpc.tfvars
installer/frontend/ui-tests/pages/clusterInfoPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/tests/aws.js
installer/frontend/ui-tests/tests/metal.js
installer/frontend/ui-tests/utils/terraformTfvars.js

This change is needed to allow the GUI tests and smoke tests to be unified.
Also changes a couple of GUI test inputs to bring them a little closer to the smoke tests.

tests/frontend: Support multiple GUI end-to-end tests runs

---

tests/rspec/lib/cluster.rb

before: [0m[1mDownloading modules...[0m
after: Downloading modules...

tests: set output to not use color

---

tests/rspec/lib/cluster.rb
tests/rspec/lib/shared_examples/k8s.rb

We have a test that checks the idempotency but I will disable the test because today we are not idempotency 😢. we can enable that when we start to work on INST-287

tests: add idempotency tests

---

config.tf

/cc @ggreer @diegs @Quentin-M @sudhaponnaganti

config.tf: Bump console, kvo for the 179-3 release.

---

config.tf

Bump kvo to v1.8.4-kvo.3
Bump console to v2.6.3
/cc @ggreer

config.tf: Bump kvo/console in 184 branch.

---

tests/rspec/lib/metal_support.rb

removing the assets, and adding sudo to get he journals

tests: small fixes

---

MAINTAINERS

MAINTAINERS: add alberto

---

.github/PULL_REQUEST_TEMPLATE.md

This template should help remind contributers to add labels to their
PRs.

Add pull request template to .github folder

---

tests/README.md

Before testing any changes on a PR, the proposed changes are merged into
the target branch. This should be reflected in the `tests/README.md`.

tests: Extend ReadMe to mention merge into target branch

---

installer/frontend/components/aws-cloud-credentials.jsx

Cherry picks #2572 to `track-1`

frontend: Fix display of error message when AWS credentials are invalid

---

modules/update-payload/assets.tf

- Logs: https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-release-automation/job/build-tectonic/job/master/68/console
- Introduced: #2486

modules/update-payload: repair payload generation after #2486

---

config.tf

Fixes https://jira.coreos.com/browse/TECREL-140

Bump console to v2.6.4.

---

modules/aws/vpc/master-elb.tf
modules/aws/vpc/sg-master.tf
modules/azure/vnet/lb-api.tf
modules/azure/vnet/nsg-master.tf
modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/gcp/master-igm/master.tf
modules/gcp/network/firewall-master.tf
modules/gcp/network/loadbalancer.tf
modules/openstack/secgroups/rules/k8s/secgroup.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/metal/tls.tf
tests/smoke/azure/fixtures/external-dns/main.tf
tests/smoke/azure/fixtures/external-vnet/main.tf
tests/smoke/azure/fixtures/private-cluster/private-vnet-vpn.tf

Move apiserver to 6443.
Fixes: INST-640 and INST-788

modules/platforms: move api to 6443

---

installer/frontend/ui-tests/output/aws-custom-vpc.tfvars
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/utils/terraformTfvars.js

Adds a test that would have caught this bug: #2620

tests/frontend: Add a page refresh on the last wizard page

---

installer/frontend/app.jsx

This try / catch looks unnecessary and has the wrong error message anyway.

frontend: Remove unnecessary try / catch

---

config.tf

Includes fix for missing dex TPR.

config.tf: tco to 0.6.2.

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
platforms/aws/variables.tf

Add an example for the `tectonic_aws_extra_tags` variable

examples: Provide tectonic_aws_extra_tags example

---

Jenkinsfile
tests/rspec/lib/metal_support.rb
tests/rspec/lib/test_container.rb
tests/rspec/utils/rkt-auth.json

tests: fix container tests in metal

---

config.tf

Follow up of #2560 to update track-1.
@alexsomesan @sym3tri @cpanato 
/cc @pst @sichvoge @ant31

Bump Tectonic Monitoring to 1.9

---

modules/aws/etcd/nodes.tf

When providing a etcd IAM role do not create a new one.

Do not create etcd roles if one is provided

---

installer/frontend/components/aws-vpc.jsx

- Add `isSelected()` helper.
- Remove `AWS_CONTROLLER_SUBNET_IDS` and `AWS_WORKER_SUBNET_IDS` conditions, which are not required in addition to the `isSelected()` check.
- Remove redundant condition for `AWS_VPC_CIDR`, which is actually handled by the standard form validation.

frontend: Simplify AWS_VPC.canNavigateForward

---

installer/frontend/components/aws-tags.jsx
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/ui.jsx

This seems to no longer do anything useful.

frontend: Remove "blurry" property

---

Jenkinsfile

This PR will call the script that sends log files to S3 for the bare-metal tests.

tests: add bare-metal log files to ELK

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Set the platform and spec value for the bare-metal tests.

tests: Set platform and spec for bare-metal

---

modules/aws/vpc/outputs.tf
platforms/aws/main.tf
platforms/govcloud/main.tf

(In case you don't have permissions to add labels, please ask a
[Maintainer](../MAINTAINERS).)

Fix spelling of console zone id output

---

tests/rspec/lib/govcloud_vpc.rb

cherry-picks https://github.com/coreos/tectonic-installer/commit/ba521a4a63dfd5b1f1c46db5a6ecd29d856b27c8

govcloud: update terraform -auto-approve

---

modules/tectonic/resources/manifests/updater/operators/kube-version-operator.yaml
modules/tectonic/resources/manifests/updater/operators/kubernetes-addon-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-cluo-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-etcd-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-prometheus-operator.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-utility-operator.yaml

Also reorder the yaml manifest fields lexicographically.
https://jira.coreos.com/browse/CORS-459

operators: Pin operators to master nodes.

---

Jenkinsfile

tests: Comment out GCP Jenkins parameter to reduce confusion

---

Jenkinsfile

cherry pick: https://github.com/coreos/tectonic-installer/pull/2599

cherry pick to track1: disable GCP tests

---

config.tf
modules/bootkube/assets.tf
modules/bootkube/resources/manifests/app-version-tectonic-tno.yaml
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/updater/app_versions/app-version-kubernetes-addon.yaml
modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-utility.yaml
modules/update-payload/assets.tf

some manifests don't have associated versions. Removing the placeholder version and updating their appversions to facilitate the install

removed version from operators that are unversioned

---

config.tf

fixes: INST-798
cc @enxebre @alexsomesan

config.tf: bump k8s to 1.8.6

---

platforms/aws/main.tf
platforms/govcloud/main.tf

bump tf aws provider to 1.7.0

---

installer/frontend/components/aws-vpc.jsx

frontend: Fix AWS VPC validation when no subnets are selected

---

tests/rspec/lib/cluster.rb

Cherry-pick from https://github.com/coreos/tectonic-installer/pull/2670

tests: collect logs when timeout waiting for service (#2670)

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf
modules/govcloud/etcd/nodes.tf
modules/govcloud/master-asg/master.tf
modules/govcloud/worker-asg/worker.tf

cherry pick from https://github.com/coreos/tectonic-installer/pull/2745

aws: remove ecr permissions

---

platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl

fix var typo in matchbox templates (see #2748)

platforms/metal: fix iscsi variable in Matchbox templates

---

config.tf

config: bump k8s to 1.8.7

---

modules/govcloud/etcd/ignition.tf
modules/govcloud/etcd/variables.tf
modules/govcloud/master-asg/ignition.tf
modules/govcloud/master-asg/variables-ignition.tf
modules/govcloud/worker-asg/ignition.tf
modules/govcloud/worker-asg/variables-ignition.tf

reconcile govcloud modules inputs

reconcile govcloud modules inputs

---

config.tf

* Update CLUO to v0.5.0
* Add support for Kubernetes v1.9

Update tectonic-cluo-operator to v0.3.0

---

installer/frontend/.eslintrc
installer/frontend/components/base.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/header.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js
installer/frontend/readfile.js
installer/frontend/reducer.js
installer/frontend/trail.js
installer/frontend/ui-tests/commands/expectNoValidationError.js
installer/frontend/ui-tests/commands/expectValidationErrorContains.js
installer/frontend/ui-tests/commands/selectOption.js
installer/frontend/ui-tests/commands/setField.js
installer/frontend/ui-tests/pages/awsCredentialsPage.js
installer/frontend/ui-tests/pages/certificateAuthorityPage.js
installer/frontend/ui-tests/pages/clusterDnsPage.js
installer/frontend/ui-tests/pages/clusterInfoPage.js
installer/frontend/ui-tests/pages/consoleLoginPage.js
installer/frontend/ui-tests/pages/defineMastersPage.js
installer/frontend/ui-tests/pages/defineWorkersPage.js
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/ui-tests/pages/keysPage.js
installer/frontend/ui-tests/pages/matchboxAddressPage.js
installer/frontend/ui-tests/pages/matchboxCredentialsPage.js
installer/frontend/ui-tests/pages/networkConfigurationPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/nodesPage.js
installer/frontend/ui-tests/pages/platformPage.js
installer/frontend/ui-tests/pages/sshKeysPage.js

Makes space character before function parameters consistent.

frontend: Add space-before-function-paren eslint rule

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/aws_support.rb
tests/rspec/lib/cluster.rb

fixes: https://jira.coreos.com/browse/INST-811 for aws for now

tests: collect machine console logs (aws)

---

BUILD.bazel
WORKSPACE
bazel-rules/gen_test.bzl

Before adding all other format checkers I would like to propose this patch for early feedback. I will follow up with the others once this is merged.
Let me know what you think? Happy for any feedback.

 Add terraform fmt test rule to bazel

---

Documentation/dev/govcloud/README.md
modules/govcloud/etcd/ignition_s3.tf
modules/govcloud/master-asg/ignition_s3.tf
modules/govcloud/worker-asg/ignition_s3.tf
platforms/govcloud/s3.tf
tests/smoke/govcloud/vars/govcloud-vpc-internal.tfvars.json

Add s3 support included in CL alpha https://coreos.com/releases/#1662.0.0

platforms/govcloud: add s3 support include in CL alpha

---

config.tf

Closes TECREL-148.
@alexsomesan @sym3tri 
/cc @pst @sichvoge @robszumski

monitoring: Fix grafana image

---

tests/rspec/lib/cluster.rb
tests/rspec/lib/govcloud_cluster.rb

tests: make optional the tf-trace / fix govcloud to get ips and other refactors

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh
tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/metal_support.rb
tests/rspec/lib/shared_examples/k8s.rb

Add the Logstash project to the track-1 branch.

tests: add logstash project to track1

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml

This is a cherry-pick of
* #2773 
* #2782 
into `master`.
@alexsomesan @sym3tri

Bump monitoring

---

modules/dns/designate/outputs.tf

I don't have permission to add labels. Tested on OpenStack.

modules/dns/designate: Flatten output lists

---

Documentation/variables/govcloud.md
contrib/govcloud/vars.tf
examples/terraform.tfvars.govcloud
modules/dns/powerdns/records.tf
modules/dns/powerdns/variables.tf
platforms/govcloud/main.tf
platforms/govcloud/tectonic.tf
platforms/govcloud/tls.tf
platforms/govcloud/variables.tf
tests/rspec/lib/govcloud_vpc.rb

move dns api key to a variable for govcloud https://github.com/coreos/tectonic-installer/pull/2836

move dns api key to a variable for govcloud

---

config.tf

Bumping kvo version 
(In case you don't have permissions to add labels, please ask a
[Maintainer](../MAINTAINERS).)

kvo version bump

---

modules/ignition/resources/services/k8s-node-bootstrap.service

Fixes: INST-897
cc @alexsomesan @brianredbeard @enxebre @coresolve

modules/ignition: torcx respect proxy

---

Documentation/variables/govcloud.md
examples/terraform.tfvars.govcloud
platforms/govcloud/main.tf
platforms/govcloud/tectonic.tf
platforms/govcloud/tls.tf
platforms/govcloud/variables.tf

Addresses https://github.com/coreos/tectonic-installer/pull/2834#discussion_r164132465

remove unnecessary ternaries

---

Jenkinsfile
installer/scripts/maintenance/clean-aws.sh
installer/scripts/maintenance/tag-aws.sh
tests/jenkins-jobs/maintenance/tag_clean_aws_grafiti_job.groovy
tests/rspec/Gemfile
tests/rspec/Gemfile.lock
tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/aws_iam.rb
tests/rspec/spec/aws/vpc_internal_spec.rb
tests/rspec/spec/meta-tests/aws_vpc_spec.rb

Fixes: https://jira.coreos.com/browse/INST-417

tests: change the user on aws and start using role

---

installer/frontend/ui-tests/pages/awsCredentialsPage.js

We are using the role of Jenkins and the UI tests start failing. this fix the issue.

tests/frontend: fix ui tests. to use the session role in aws

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

Field validation branch PR for setting `--kubelet-preferred-address-types` on the API servers
rel: 
- #2777
- https://jira.coreos.com/browse/TECREL-150
/cc: @robszumski / @sudhaponnaganti / @coverprice / @tonytcampbell / @metral / @coresolve

Field Validation: API server kubelet preferred address types flag

---

Jenkinsfile
tests/jenkins-jobs/tectonic_installer_nightly_trigger.groovy
tests/jenkins-jobs/tectonic_installer_nightly_trigger_with_k8s_conformance.groovy

tests: not fail the post operations and send slack notifications

---

Documentation/dev/govcloud/README.md
contrib/govcloud/resources/powerdns.service
contrib/govcloud/services.tf
contrib/govcloud/vars.tf
tests/rspec/lib/govcloud_vpc.rb

set powerdns api key at runtime

contrib/govcloud: set pdns api key at runtime

---

config.tf

master pr: https://github.com/coreos/tectonic-installer/pull/2851
https://github.com/coreos-inc/tectonic-cluo-operator/releases/tag/v0.3.1

config.tf: Update tectonic-cluo-operator to v0.3.1 - lithium

---

installer/api/handlers_terraform.go
installer/pkg/terraform/executor.go

api: Remove support for Terraform versions below 10

---

tests/rspec/lib/shared_examples/k8s.rb

it is causing some invalid results. Will investigate the cause.

tests: disable for now Console tests

---

config.tf

https://github.com/coreos-inc/tectonic-cluo-operator/releases/tag/v0.3.1

config.tf: Update tectonic-cluo-operator to v0.3.1

---

config.tf

console v3.0.8
(In case you don't have permissions to add labels, please ask a
[Maintainer](../MAINTAINERS).)

bumped kvo version

---

Jenkinsfile

fixes the issue that the pipeline was not sending the notification to the channel

tests: fix slack notification and make the login more readable

---

installer/assets/frontend/css/styles.css
installer/frontend/__tests__/cidr.js
installer/frontend/cidr.js
installer/frontend/components/cidr.jsx
installer/frontend/components/k8s-cidrs.jsx

frontend: Add IP range start and end addresses to CIDR tooltip

---

tests/rspec/lib/metal_support.rb
tests/smoke/aws/vars/aws-ca.tfvars.json
tests/smoke/aws/vars/aws-exp.tfvars.json
tests/smoke/aws/vars/aws-net-flannel.tfvars.json
tests/smoke/aws/vars/aws-vpc-internal.tfvars.json
tests/smoke/aws/vars/aws.tfvars.json
tests/smoke/azure/vars/basic.tfvars
tests/smoke/azure/vars/dns.tfvars
tests/smoke/azure/vars/example.tfvars
tests/smoke/azure/vars/external.tfvars
tests/smoke/azure/vars/private-cluster.tfvars
tests/smoke/bare-metal/vars/metal.tfvars.json
tests/smoke/gcp/vars/gcp.ha.tfvars.json
tests/smoke/gcp/vars/gcp.tfvars.json
tests/smoke/govcloud/vars/govcloud-vpc-internal.tfvars.json

fixes: https://jira.coreos.com/browse/INST-911

tests: using CL beta in master branch

---

platforms/aws/main.tf
platforms/azure/main.tf
platforms/govcloud/main.tf

aws/azure: bump terraform provider

---

buildvars.sh

buildvars: BUILD_TIME in ISO 8601 format

---

modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml

Proposed fix for https://jira.coreos.com/browse/TECREL-165
Regression introduced by
https://github.com/coreos/tectonic-installer/pull/2814

Upgrade fix for CA certs

---

Jenkinsfile
installer/cmd/installer/platforms.go
installer/frontend/ui-tests/pages/platformPage.js

See ticket INST-933
cc: @sym3tri, @robszumski

frontend & tests: Disable metal GUI option

---

installer/frontend/components/tf-poweron.jsx

The implementation of `estimateTerraformProgress()` will need to change for the new CLI, but the other logic and the UI should remain valid.

frontend: Add progress bar for Terraform destroy actions

---

modules/aws/vpc/outputs.tf
steps/bootstrap/outputs.tf
steps/joining/ncg.tf

fix mixed vars

---

installer/frontend/components/aws-cloud-credentials.jsx

Move the AWS region dropdown / region load error message to a separate
component.
Don't display the AWS regions dropdown if there was a load error. This
fixes a situation where the error was displayed both as a regions field
error and as a general form error.
Display a loading indicator instead of the regions dropdown while the
request is pending.

frontend: Fix AWS regions duplicated error and add loading indicator

---

installer/frontend/components/aws-vpc.jsx

Use `Subnets` component to DRY similar code for controller & worker subnet dropdowns.

frontend: Add loading indicator for AWS VPC subnets and clean up

---

Documentation/dev/build.md

Added some things I noticed when trying this out.

build doc updates

---

installer/pkg/config-generator/BUILD.bazel
installer/pkg/config-generator/generator.go

cli: add missing tectonic config

---

BUILD.bazel

bazel: ensure incremental changes to Terraform config bust cache

---

Jenkinsfile

fixes: https://jira.coreos.com/browse/INST-879

bazel/build/ci: add terraform fmt check

---

tests/smoke/cluster_test.go

This is blocked by: https://jira.coreos.com/browse/ALM-423

tests: all pods should be in running and none in crashloopbackoff

---

config.tf

Cherry-pick: https://github.com/coreos/tectonic-installer/pull/2904
Fixes; TECREL-172
cc @brancz

monitoring: Fix migration and insecure image org

---

installer/frontend/components/aws-cloud-credentials.jsx

Also add check to prevent "undefined" string appearing for unknown regions.

frontend: Add AWS Paris (eu-west-3) region option

---

steps/assets/ignition-bootstrap.tf
steps/assets/ignition-etcd.tf
steps/assets/outputs.tf
steps/bootstrap/inputs.tf
steps/bootstrap/main.tf
steps/bootstrap/s3-assets.tf

Ensure terraform works on second destroy

Ignition as data

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

change igintion kubelet config resource name

platform/aws: change duplicated resource name

---

config.tf
modules/ignition/ca_certs.tf
modules/ignition/resources/services/k8s-node-bootstrap.service
platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl
platforms/metal/cl/custom-ca.yaml.tmpl
platforms/metal/matchers.tf
platforms/metal/profiles.tf

Cherry-picks: https://github.com/coreos/tectonic-installer/pull/2825
Fixes: TECREL-181
Cherry-picks: https://github.com/coreos/tectonic-installer/pull/2839
Fixes: TECREL-178
cc @alexsomesan @coverprice

Cherry-pick offline changes

---

config.tf
modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml

I forgot to apply my changes in https://github.com/coreos/tectonic-installer/pull/2954 to master

Cherry pick PR 2954

---

config.tf

Bump prometheus to 1.9.4  (fix upgrade)

*: bump Tectonic Monitoring to 1.9.4

---

buildvars.sh

Debug flag cleanup from buildvars.sh

Build: remove +x flag from buildvars.sh

---

installer/frontend/aws-actions.js
installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/form.js

Several related fixes for handling async API calls.
Also prevents some unnecessary API calls.

frontend: Async fixes and improvements

---

installer/frontend/__tests__/fields.js

Also remove some unnecessary `resetCC` calls.

tests/frontend: Add more checks to deep field dependency unit test

---

Documentation/variables/govcloud.md
Jenkinsfile
contrib/govcloud/main.tf
contrib/govcloud/vars.tf
examples/terraform.tfvars.govcloud
platforms/govcloud/main.tf
platforms/govcloud/variables.tf
tests/rspec/lib/govcloud_cluster.rb
tests/rspec/lib/govcloud_vpc.rb
tests/rspec/spec/govcloud/vpc_internal_spec.rb

tests: update govcloud to use roles and the new aws govcloud account

---

installer/assets/BUILD.bazel

Revert a change in UT2 that broke compiling bindata
cc @spangenberg @mxinden

installer: revert change that broke bindata

---

BUILD.bazel
Jenkinsfile
installer/BUILD.bazel
installer/pkg/config-generator/BUILD.bazel

Enable cli go unit tests to be run by bazel and the cli

add bazel test suite for cli units

---

installer/frontend/server.js

The server actions to update the commitPhase in Redux were not being called correctly.
Bug was introduced by #3019

frontend: Fix final Submit button to disable after being clicked

---

modules/tls/etcd/signed/main.tf
modules/tls/identity/self-signed/main.tf
modules/tls/ingress/self-signed/main.tf
modules/tls/kube/self-signed/aggregator_ca.tf
modules/tls/kube/self-signed/ca.tf

Fixes #INST-896
rebase of pull #3031

modules/tls: add uuid function to created certs

---

Jenkinsfile

In order for the release automation pipeline to consume the results of
the Tectonic installer pipeline, we have to ensure, that both are
configured with the same Tectonic installer git ref (commit).
This patch adds a Jenkins pipeline parameter to the Tectonic installer
pipeline to trigger a build with a specific git ref.

tests: Optionally trigger pipeline with specific git ref

---

Jenkinsfile

Bazel also prints out color codes. This patch extends the scope of the
ansiColor function to the entire first stage.

tests: Wrap entire first stage with ansiColor tag

---

installer/vendor/github.com/shirou/gopsutil/process/BUILD.bazel

bazel: ensure gazelle does not error

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

With the new Tectonic cli flow, the cluster build folder does not
exist anymore. Instead the cli creates a folder on the top level with
the name of the cluster, containing all relevant files.
For now we need to support both flows. For AWS the Tectonic CLI is used.
For Azure and all other platforms we still use plain terraform.
Similar to #3063

tests: Adjust log-analyzer-copy to missing build folder

---

Jenkinsfile

More in depth cleanup will happen in PR 3067 [1]. This quick-fix
unblocks current master failures.
[1] https://github.com/coreos/tectonic-installer/pull/3067

tests: Remove GUI tests

---

installer/cmd/tectonic/main.go

cli: change default log level to info

cli: change default log level to info

---

.gitignore
bazel-bin
bazel-genfiles
bazel-out
bazel-tectonic-installer
bazel-testlogs

cc @ggreer @crawford 
related: #3129 #3130

bazel: remove symlinks

---

Documentation/dev/bazel-in-depth.md

Documentation: add bazeless docs

---

config.tf
installer/pkg/config-generator/ignition.go
modules/aws/etcd/ignition.tf
modules/bootkube/resources/manifests/tectonic-node-controller.yaml
steps/bootstrap/s3-assets.tf

Diff between the old and new tnc:
https://github.com/coreos-inc/tectonic-operators/compare/f6d5e710a97a8cd6f4cd2963f4426131f854a869...master

config.tf: Bump tnc version, also update the ignitoin endpoint URL.

---

Jenkinsfile

From quay.io/coreos/kube-conformance:v1.8.4_coreos.0
To quay.io/coreos/kube-conformance:v1.9.1_coreos.0

Bump kube conformance

---

config.tf

Bump Tectonic version to 1.7.14-tectonic.2

---

config.tf

Bumped Tectonic version

---

Documentation/variables/config.md
config.tf

config.tf: bump default channel to 1.9-production

---

images/kubernetes-e2e/Dockerfile

also bump the conformance test image

tests: add parameter to -v and update jenkinsfile

---

tests/rspec/lib/name_generator.rb

using the same name generator that we have currently in `master`

Fix cluster name when testing in Branches

---

Jenkinsfile
images/kubernetes-e2e/Dockerfile
images/kubernetes-e2e/build.sh

Cherry-pick of #3180. Bump 1.9.6 K8s conformance tests to 1.9.6.

Bump 1.9.6 K8s conformance tests to 1.9.6

---

installer/pkg/config-generator/BUILD.bazel
installer/pkg/config/BUILD.bazel
installer/pkg/config/types.go
installer/pkg/validate/BUILD.bazel
installer/pkg/workflow/BUILD.bazel
installer/pkg/workflow/fixtures/aws.basic.yaml
installer/pkg/workflow/fixtures/terraform.tfvars

add yaml2json support for admin vars

---

config.tf

Bump Tectonic Console to v6.0.1.

---

config.tf

- tco: 0.6.4
- kvo: v1.8.9-kvo.4
- console: v5.0.6
- tcluo: v0.3.2

config.tf: 1.8.9-tectonic.3, bump tco, kvo, console and tcluo

---

config.tf

Bump kvo to v1.9.6-kvo.3, tco to 0.6.4, tcluo to v0.3.2

config.tf: Bump kvo, tco, tcluo for 1.9.6

---

config.tf

Cherry-pick of #3195 from 1.9.6 to track-1

config.tf: Bump kvo to v1.9.6-kvo.3, tco to 0.6.4, tcluo to v0.3.2

---

config.tf

Bump KVO to 196-4 to support Console 6.0.5

---

config.tf
modules/tectonic/manifests.tf
modules/tectonic/resources/manifests/updater/app_versions/app-version-kube-addon.yaml
modules/tectonic/resources/manifests/updater/operators/kube-addon-operator.yaml
modules/tectonic/resources/tectonic.sh
tests/rspec/lib/operators.rb

Fixed the out dated repo path.

config.tf: Change kube-addon-operator repo.

---

installer/pkg/workflow/utils.go
modules/ignition/resources/services/rm-assets.service
steps/assets/resources/rm-assets.sh
tests/rspec/lib/cluster.rb

Cleanup bootstrap node
Fixes: INST-956
cc @enxebre @squeed

steps: bootstrap cleanup

---

config.tf

Updates OLM for 1.9 support and updates x-operator

bump olm to 0.4.0

---

config.tf

Updates OLM for 1.9 support and updates x-operator

bump alm to 0.4.0

---

examples/tectonic.aws.yaml

Some required variables are missing from the example yaml file. Add them.

examples: add missing required variables

---

config.tf

cc @alexsomesan @enxebre 
fixes: https://github.com/coreos/tectonic-installer/issues/3109

config.tf: bump tls provider to fix CA

---

BUILD.bazel
installer/BUILD.bazel
installer/cmd/tectonic/BUILD.bazel

Fix INST-1060. Add gazelle idempotency

Gazelle cmd

---

Jenkinsfile

Some simplification to Jenkinsfile. Should also provide a small change to how messages are displayed in slack channel.

Jenkinsfile: remove wrapper around slackSend

---

Jenkinsfile

Disable slack notifications from PRs

---

Jenkinsfile

Do not show every removed file in logs

---

installer/pkg/config/validate.go
installer/pkg/workflow/fixtures/aws.basic.yaml
installer/pkg/workflow/fixtures/terraform.tfvars

Perform basic validation of the admin credentials.
Addresses: INST-1115
cc @enxebre @trawler

installer: validate admin

---

.gitignore
.rspec
.rubocop.yml
spec/aws/basic_spec.rb
spec/support/bazel.rb
spec/support/cluster.rb
spec/support/config.rb

This is an experimental branch for the moment where we test the new test suite.
cc: @paulfantom

RSpec test suite v2

---

.travis.yml
installer/pkg/config/libvirt/libvirt.go

intaller/pkg/config/libvirt: fix lint errors

---

.travis.yml
installer/pkg/config/libvirt/libvirt.go
installer/pkg/validate/validate.go
installer/pkg/workflow/init_test.go
installer/pkg/workflow/utils.go

Fix several Go vet warnings.
cc @enxebre @alexsomesan @trawler @paulfantom

installer/pkg: vix govet errors

---

installer/pkg/config/aws/aws.go
installer/pkg/config/cluster.go
installer/pkg/config/validate.go
installer/pkg/config/validate_test.go
installer/pkg/workflow/fixtures/aws.basic.yaml
steps/variables-aws.tf
tests/smoke/aws/vars/aws-basic.yaml

add new validation for AWS vpc cidr block.

installer/pkg/config: validate aws vpc cidr block

---

modules/ignition/variables.tf
modules/tectonic/manifests.tf
modules/tectonic/resources/manifests/secrets/tnc-tls.yaml
modules/tectonic/resources/tectonic.sh
modules/tectonic/variables.tf
modules/tls/ca/assets.tf
modules/tls/ca/outputs.tf
modules/tls/tnc/assets.tf
modules/tls/tnc/main.tf
modules/tls/tnc/outputs.tf
modules/tls/tnc/variables.tf
steps/assets/base/ignition-bootstrap.tf
steps/assets/base/ignition-tls.tf
steps/assets/base/inputs.tf
steps/assets/base/outputs.tf
steps/assets/base/tectonic.tf
steps/tls/main.tf

TNC needs this key/cert pair in order to secure HTTPS traffic.

modules/tectonic/resources: add TNC key/cert pair

---

Documentation/dev/libvirt-howto.md

Update console path

---

installer/BUILD.bazel
installer/pkg/tls/BUILD.bazel
installer/pkg/tls/tls.go
installer/pkg/tls/tls_test.go

installer/pkg/tls: tls package for creating and signing certs

---

tests/README.md

Update readme document to reflect current CI and test status

Update tests readme

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Update the templates to let people know not to submit feature requests here.

update issue templates
