modules/aws/etcd/nodes.tf

This fixes an idempotency issue where even though the `iops` parameter is not used when the volume type is anything other than `io1`, Terraform will report a diff forcing recreation of the instance(s) because the reported `iops` parameter does not match the value specified in the module.
The calculation comes from the AWS docs at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html, specifically:
>Between a minimum of 100 IOPS (at 33.33 GiB and below) and a maximum of 10,000 IOPS (at 3,334 GiB and above), baseline performance scales linearly at 3 IOPS per GiB of volume size.
Related to / supersedes #896

Calculate root_block_device.iops for gp2 volumes

---

installer/api/api.go
installer/api/handlers_tectonic.go
installer/assets/frontend/css/styles.css
installer/frontend/components/tf-poweron.jsx
tests/rspec/lib/aws_iam.rb
tests/rspec/lib/aws_region.rb
tests/rspec/lib/aws_vpc.rb
tests/rspec/lib/grafiti.rb
tests/rspec/lib/name_generator.rb
tests/rspec/lib/operators.rb
tests/rspec/spec/aws_vpc_internal_spec.rb
tests/rspec/spec/meta-tests/aws_vpc_spec.rb
tests/rspec/spec/meta-tests/tfvars_file_spec.rb

Add Tectonic Console Failed alert box, which includes
- Output failure message if we have one
- kubeconfig download button
- kubectl commands for debugging with the actual pod names and namespaces
Fixes #356, but doesn't add the "Save log" download links from the mocks because it would be too much work at this time.

Improve UI for Tectonic Install failed case

---

installer/pkg/terraform/executor.go

Since we completed the move to TF 0.10, this is no longer needed.

Don't export TERRAFORM_CONFIG anymore - deprecated

---

installer/pkg/terraform/executor.go

Once we updated Jenkins images to TF 0.10.4 we started seeing this failure.
It's caused by Terraform trying to determine the HOME folder to look for 3rd party plugins (default behaviour). Since there is no home set, it falls back to shelling out to `getent` POSIX tool which is not available.
This fixes current build step test failures similar to:
```
?   	github.com/coreos/tectonic-installer/installer/api	[no test files]
?   	github.com/coreos/tectonic-installer/installer/assets	[no test files]
?   	github.com/coreos/tectonic-installer/installer/cmd/installer	[no test files]
ok  	github.com/coreos/tectonic-installer/installer/pkg/aws	0.004s	coverage: 40.8% of statements
?   	github.com/coreos/tectonic-installer/installer/pkg/containerlinux	[no test files]
? …
```

Always set HOME env when running Terraform

---

installer/frontend/ui-tests/commands/expectNoValidationError.js
installer/frontend/ui-tests/commands/expectValidationErrorContains.js
installer/frontend/ui-tests/pages/awsCredentialsPage.js
installer/frontend/ui-tests/pages/clusterInfoPage.js
installer/frontend/ui-tests/pages/consoleLoginPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/nodesPage.js
installer/frontend/ui-tests/pages/platformPage.js
installer/frontend/ui-tests/tests/awsInstaller.js
installer/frontend/ui-tests/tests/bareMetalInstaller.js

Test each of the platform options on the first page.
Add AWS credentials page validation error tests.
Add basic tests for AWS Define Nodes page etcd options.
Run pod / service range tests for each VPC option.
Add Console Login page validation error tests.

tests/frontend: Add more Nightwatch tests for AWS

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
modules/aws/worker-asg/variables.tf
modules/aws/worker-asg/worker.tf
platforms/aws/main.tf
platforms/aws/variables.tf

Adds support for attaching worker instances to Elastic Load Balancers.
This is useful for exposing `NodePort` services via load-balancers with
life-cycles managed separately from the cluster.  A common example is
ingress controllers.

platforms/aws: Support attaching workers to ELBs

---

tests/rspec/.rubocop.yml
tests/rspec/lib/aws_vpc.rb

This fixes the fixture VPC creation using Terraform 0.10.x

RSpec AWS VPC fixture - run Terraform init

---

modules/bootkube/assets.tf
modules/bootkube/resources/manifests/01-tectonic-namespace.yaml
modules/bootkube/resources/manifests/kvo-config.yaml
modules/bootkube/variables.tf
modules/tectonic/resources/manifests/namespace.yaml
modules/tectonic/resources/tectonic.sh
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

Create kvo config configmap when the cluster starts.
The kvo config contains install time options, it will be consumed by kvo during upgrade.

Add kvo config configmap

---

installer/frontend/components/submit-definition.jsx

After the cluster definition is successfully submitted to the server,
the wizard will always redirect to the Start Installation page, so this
render logic is never used.

frontend: Remove SubmitDefinition's render state that is never executed

---

installer/frontend/package.json
installer/frontend/yarn.lock

Remove babel-jest from `package.json` because it is now automatically loaded by Jest.
Upgrade Jest to v21.x
Upgrade chromedriver to v2.32.2
Upgrade selenium-server to v3.5.x

frontend: Upgrade GUI test dependencies

---

installer/assets/frontend/css/styles.css

For all `textarea` fields.
Before | After
--- | ---

frontend: Remove gap between <textarea>s and their validation errors

---

modules/bootkube/resources/bootkube.sh
modules/net/calico-network-policy/assets.tf
modules/net/calico-network-policy/outputs.tf
modules/net/calico-network-policy/variables.tf
modules/net/flannel-vxlan/assets.tf
modules/net/flannel-vxlan/outputs.tf
modules/net/flannel-vxlan/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

... to prevent conflicts with the bootkube module and idempotency
issues.
Fixes #1446
/cc @mxinden

modules/bootkube: generate flannel manifests in its own directory

---

Documentation/variables/config.md
config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/identity/configmap.yaml
modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml
modules/tectonic/variables.tf
modules/update-payload/payload.json
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

What this PR does:
- bump TPO/AppVersion to latest `v1.6.0`
- remove residue of the recent removal of the monitoring manifests, that are now fully mananged by the TPO, and instead of maintaining a list of container images including versions, now only base images are maintained
- add Grafana OIDC callback for Dex (respective PR for the KVO https://github.com/coreos-inc/kube-version-operator/pull/260)
I already tested bringing up a fresh cluster with this and will now also test the upgrade from the september (`1.7.3-tectonic.2`) release.
@s-urbaniak @alexsomesan

Bump monitoring

---

installer/frontend/ui-tests/commands/expectValidationErrorContains.js
installer/frontend/ui-tests/pages/certificateAuthorityPage.js
installer/frontend/ui-tests/pages/clusterDnsPage.js
installer/frontend/ui-tests/pages/defineMastersPage.js
installer/frontend/ui-tests/pages/defineWorkersPage.js
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/ui-tests/pages/matchboxAddressPage.js
installer/frontend/ui-tests/pages/matchboxCredentialsPage.js
installer/frontend/ui-tests/pages/networkConfigurationPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/sshKeysPage.js
installer/frontend/ui-tests/utils/wizard.js

Bare metal tests now run at least some basic tests for every screen. (Edit: Except for the Starting Installation and Installation Complete screens, which currently have no Nightwatch tests.)

tests/frontend: Add more Nightwatch tests for bare metal

---

images/tectonic-smoke-test-env/Dockerfile.builder
images/tectonic-smoke-test-env/Dockerfile.runtime
images/tectonic-smoke-test-env/Makefile

This is a minimal runtime environment for the smoke tests that uses a two-stage build to keep build dependencies away from the runtime image.

Ruby/RSpec image based on Alpine + rbenv

---

Jenkinsfile
modules/azure/master-as/outputs.tf
modules/bootstrap-ssh/variables.tf
platforms/azure/bootstrap.tf
tests/rspec/Gemfile
tests/rspec/Gemfile.lock
tests/rspec/lib/azure_cluster.rb

With this change we ensure that the bootstrapping process has completed before we run tests on Azure clusters.

Rspec azure wait for cluster

---

installer/api/handlers_terraform.go

Currently we create `terraform.d/plugins` and place the symlink to
custom plugins there.
Terraform expectes them in `terraform.d/plugins/$GOOS_$GOARCH` though.
This fixes it.
@kyoto @alexsomesan PTAL

installer/api: add runtime info to cluster plugin dir

---

modules/azure/etcd/output.tf
modules/azure/master-as/outputs.tf
modules/bootstrap-ssh/main.tf
modules/bootstrap-ssh/variables.tf
platforms/azure/bootstrap.tf

With this change we make sure that the bootstrapping module kicks off only after all it's dependencies have been created.
Previously this was accomplished by a 'depends_on' keyword but since the bootstrapper has now been moved to it's own module, that approach no longer works (Terraform limitation).

Consolidate Azure bootstrapper dependencies

---

installer/frontend/components/tf-poweron.jsx

Remove "Terraform" so that the text fits.
Before | After
--- | ---

frontend: Fix Terraform destroy error message being too long

---

installer/frontend/components/tf-poweron.jsx

Reflects changes introduced in #1910.
Switch from a list of modules to ignore, to a list of modules to include.
Now also ignores the 2 `aws_s3_bucket_object` resources.

frontend: Fix AWS Terraform apply progress bar heuristic

---

modules/bootkube/resources/manifests/cluster-config.yaml

In the future we will put other configs under a different key,
e.g. 'tuo-config'.
Having them in one configmap helps when we want to update different
configs atomically.

bootkube: Rename kvo-config.yaml to cluster-config.yaml.

---

config.tf

New things added since v1.9.3:
- Graphs that show cluster health.
- Show CRDs.
- Support latest operators (TCO, etcd, KVO, prom).
- Better messages for cluster settings that users don't have access to.
- Creating Network policies now shows a sidebar with helpful examples.
- Split up initial JavaScript bundle for faster loading.
- Support for creating/listing/editing Resource Quotas.
- Support for creating/listing/editing Persistent Volumes & PVCs.
Bug fixes include:
- RBAC namespace filters now work.
- Fixes for Microsoft Edge.

Upgrade Console to v2.0.0

---

config.tf
modules/update-payload/payload.json

* Adds master toleration to the `update-operator` to fix issue where Container Linux updates get stalled on clusters with one worker
* Updates the tectonic-torcx image with minor fixes
* See https://github.com/coreos-inc/tectonic-cluo-operator/pull/12

config.tf: Update tectonic-cluo-operator from v0.2.0 to v0.2.1

---

modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-proxy.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

This marks the objects that are (and will continue to be) managed by the
KVO as such. This uses the standard `managed-by` annotation that is
declared in the x-operator.

modules/bootkube: add managed-by annotations.

---

config.tf

The features of Dex v.7.0 is listed here: https://github.com/coreos/dex/releases/tag/v2.7.0

config.tf: bump dex to v2.7.0

---

modules/bootkube/resources/manifests/kube-apiserver.yaml

One of the labels added in #1934 was added as annotation by mistake.

bootkube: fix misplaced managed-by label.

---

Documentation/variables/openstack-neutron.md
examples/terraform.tfvars.openstack-neutron
platforms/openstack/neutron/main.tf
platforms/openstack/neutron/network.tf
platforms/openstack/neutron/nodes.tf
platforms/openstack/neutron/variables.tf

For context, a production OpenStack cluster would be expected to use some combination of Ingress and LoadBalancer resources rather than NodePorts to access Services. Assigning a public IP address to every worker is redundant in this case.

platforms/openstack/neutron: Add flag to disable worker floating IPs

---

installer/frontend/package.json
installer/frontend/yarn.lock

Fixes https://coreosdev.atlassian.net/browse/TECREL-85
Previously the command run to get tag for displaying the version was `git describe`, which was only returning annotated tags and require tags to signed. This new build of the plugin runs `git describe --tags` which should return an unsigned tag.
https://github.com/coreos/babel-plugin-git-version-build/commit/3f828164febc6b2f486f043fef75157989e97315

frontend: Upgrades plugin used to get the version of installer

---

config.tf

Release notes for Dex v2.7.1: https://github.com/coreos/dex/releases/tag/v2.7.1

config.tf: bump dex to v2.7.1

---

modules/aws/master-asg/resources/init-assets.sh
modules/vmware/node/ignition.tf
platforms/vmware/main.tf
platforms/vmware/provider.tf

- AWS still provisioned kubelet.env in init-assets.sh
- VMware had stale references to the old kubelet env service
Fixes #INST-112

modules/aws,vmware: finalize unified kubelet version bootstrapping

---

Jenkinsfile

Temporarily disabled for consolidation
Fails very often due to Packet flakiness
/cc: @sym3tri

Temporarily disable bare metal smokes

---

tests/jenkins-jobs/tectonic_coformance_tests_job.groovy
tests/jenkins-jobs/tectonic_installer_multibranch_job.groovy

Also update the time in the multibranch job to scan the repository, reduce the time, because saw some issues in Jenkins when checkout branches for tests. and this 30 minutes scan is already in place.

tests/ci: update jenkins job to send slack messages

---

installer/frontend/ui-tests/tests/awsInstaller.js
installer/frontend/ui-tests/tests/bareMetalInstaller.js

Because we now include some Terraform plugins in the build dir / assets.zip, this step now takes longer.

frontend: Increase GUI test timeout to allow time for generating assets

---

modules/aws/worker-asg/worker.tf

This uses standalone resources to attach extra ELBs to workers rather
than doing it inline on the ASG resource.  Attaching the ELBs inline
means it isn't possible to configure other attachments outside the ASG
definition.
I haven't actually had time to test this yet. Will do that soon.

platforms/aws: Use separate ELB attachment resources

---

Makefile
images/kubernetes-e2e/Dockerfile
tests/conformance/conformance.sh

This PR:
* Adds Dockerfile and make recipe for building an image that contains the Kubernetes E2E and required dependencies. The Dockerfile defaults to a specific commit but can be overwritten with `--build-arg`.
* Bumps conformance test script to uses tests from v1.7.5+coreos.0

Automate e2e image building and bump conformance test version

---

config.tf

Contains fixes for Edge, some prettier graphs, and more sidebars with helpful examples.
If a release branch for the installer has already been cut, this should get merged into it.

Bump console to v2.0.1

---

modules/aws/master-asg/resources/init-assets.sh
modules/vmware/node/ignition.tf
platforms/vmware/main.tf
platforms/vmware/provider.tf

- AWS still provisioned kubelet.env in init-assets.sh
- VMware had stale references to the old kubelet env service
Fixes #INST-112
/cc @Quentin-M @sym3tri

modules/aws,vmware: finalize unified kubelet version bootstrapping 

---

config.tf

Fixes include:
- Updating Tectonic License works.
- Loads in Safari.

Bump Tectonic Console to v2.0.2

---

config.tf

This fixes a few minor things the TPO deploys (alerting rules, dashboards, etc).
If possible I would like to get this into the October release as it's just a few bug fixes.
I just successfully tested an upgrade and will now also test bringing up a fresh cluster.
@alexsomesan @s-urbaniak @Quentin-M 
/cc @robszumski If this does get merged, the typo in the Grafana dashboard url will disappear and have the correct spelling, so the console team will have to adapt that link.

monitoring: update TPO and AppVersion

---

examples/terraform.tfvars.gcp

Looks like we forgot to run `make examples` at some point.
cc @s-urbaniak @alexsomesan

examples: run make examples

---

config.tf

Includes:
- Fix styling for cluo update.
- More accurate queries for some gauge graphs on the front page.
This should get merged into the release branch.

Bump Tectonic Console to v2.0.3

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf

It seems these property names were changed recently which causes a breakage when setting the master/worker IAM Role overrides in 1.7.5-RC4
```
$ terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws
There are warnings related to your configuration. If no errors occurred,
Terraform will continue despite these warnings. It is a good idea to resolve
these warnings in the near future.
Warnings:
* module.masters.data.aws_iam_role.master_role: "role_name": [DEPRECATED] Use `name` instead
* module.workers.data.aws_iam_role.worker_role: "role_name": [DEPRECATED] Use `name` instead
2 error(s) occurred:
* module.masters.data.aws_iam_role.master_role: "name": required field is not set
* module.workers.data.aws_iam_role.worker_role: "name": required field is not set
```

aws: fix deprecated property name for iam roles

---

modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-proxy.yaml
modules/bootkube/resources/manifests/kube-scheduler.yaml

Remove the critical pod annotation and toleration from the
controller-manager and scheduler, since this can result in dangerous
behavior as discussed in
https://github.com/kubernetes-incubator/bootkube/issues/519.
fixes: #734 
cc @aaronlevy

modules/bootkube: remove critical pod annotation

---

modules/tectonic/assets.tf
modules/tectonic/resources/manifests/cluster-config.yaml
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/gcp/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

This fixes a regression introduced in #2014.
Additionally:
platforms/gcp: replace admin_password_hash with admin_password
bcrypt support landed in #1771 but the change was not promoted to GCP.
This fixes it.

 modules/tectonic: add kube_dns_service_ip variable

---

Documentation/dev/gcp/README.md
config.tf
images/tectonic-builder/Dockerfile
images/tectonic-installer/Dockerfile
images/tectonic-smoke-test-env/Dockerfile
tests/smoke/bare-metal/smoke.sh

As part of this bump I've also flipped the TF download location back to the official upstream release. 
We used to maintain a CoreOS fork with specific tweaks for overriding some tight timeouts to help our smoke tests. Those changes were actually isolated to the AWS provider which got split out into it's own repo. Also, with the recent improvements to the test framework we're not being blocked by those particular flakes anymore.
/cc: @sym3tri

Bump Terraform to 0.10.7

---

config.tf

Changes include:
- Only show Network Policies in sidebar if the cluster has Calico.
- Fix styling for nodes without CLUO (mostly RHEL workers).
- Support cascading deletes ([example screenshot](https://user-images.githubusercontent.com/523368/30987565-599d0ac0-a44c-11e7-98e0-ae47fa2ae8b9.png))
- Support zooming & panning in line graphs.
- Update API success gauge on dashboard to use a query that's more likely to return useful data.
- Allow downloading a kubeconfig for a given Service Account.
- Various bug fixes & styling tweaks.

Bump Tectonic Console to v2.1.1

---

modules/bootkube/resources/manifests/cluster-config.yaml

There was a typo in "initialConfig" and other objects should not be
marked as strings.

modules/bootkube: Fix cluster-config object

---

images/kubernetes-e2e/Dockerfile
images/tectonic-builder/Dockerfile
images/tectonic-installer/Dockerfile

1.9.1 fixes the recent vulnerabilities in go, see:
https://groups.google.com/forum/m/#!topic/golang-nuts/sHfMg4gZNps
I would like to put these changes up for discussion. Should we fix our Dockerfile base images to specific patch versions, or just pin the minor version?

Bump to go 1.9.1 in Dockerfiles

---

tests/jenkins-jobs/tectonic_builder_docker_image.groovy

The tectonic builder does not default to the CoreOS terraform version
anymore since #2041. This updates the documentation of the parameter.

Update tectonic builder Jenkins job parameter description

---

Makefile

The `e2e-docker-image` make target does not work with Linux and GNU
Make 4.2.1 because `E2E_IMAGE` variable is not passed to both following
commands. This patch exports it, before using it later.
Not sure if this is a idiomatic approach. Happy for any suggestions. 
@ethernetdan @alexsomesan Could you try this out? As far as I know you are both running on Mac?!

Fix Makefile target e2e-docker-image for linux

---

modules/aws/vpc/sg-master.tf
modules/aws/vpc/sg-worker.tf
modules/gcp/network/firewall-master.tf
modules/gcp/network/firewall-worker.tf

Correct default node port range is 30000 - 32767 per:
https://git.io/vd0v3
This fixes the range we probably need to think about how to address this
for existing clusters.

Fix Security Groups to correct node port range

---

modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml

This is because tco replies on ssl certs path that doesn't exist on rhel nodes.

updater: Add toleration and node selector for tco to schedule it to master

---

modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml
modules/update-payload/payload.json

This is because tco replies on ssl certs path that doesn't exist on rhel nodes.

updater: Add toleration and node selector for tco to schedule it to master.

---

Jenkinsfile
tests/conformance/conformance.sh

With 41906a25 we bumped the go version in our Docker images. This
updates the tags in our test automation Jenkins jobs to the newest
images on quay.

Bump docker image versions in Jenkins jobs

---

config.tf
modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml
modules/update-payload/payload.json

Otherwise, if the workers are all rhel nodes, then it will have an issue
finding ssl certs that are required for hitting the core update server.

payload.json: Add node selector and toleration for tco so it runs on master node.

---

config.tf

- Fix API version for service monitor & alert manager templates. (https://github.com/coreos-inc/bridge/pull/1798)
- Fix infinite loop when filtering pods for a given node. (https://github.com/coreos-inc/bridge/pull/1801)
- Fix memory leak on logs page. (https://github.com/coreos-inc/bridge/pull/1800)
- Fix https://coreosdev.atlassian.net/browse/TECREL-113

Bump console to v2.2.3.

---

installer/frontend/components/cluster-type.jsx

Handle the case where AWS is disabled with the command line option.

frontend: Fix platform dropdown default value when AWS is disabled

---

config.tf

**Image:**  `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15`
*New Features:*
- Opentracing support for NGINX
- Setting upstream vhost for nginx
- Allow custom global configuration at multiple levels
- Add support for proxy protocol decoding and encoding in TCP services
- Add OCSP support
- Configurable ssl_verify_client
Complete changelog [here](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/Changelog.md)

Update nginx ingress controller to 0.9-beta.15

---

config.tf
modules/update-payload/payload.json

Fixes upgrades failing from as-yet-unreleased `1.7.3+tectonic.4`.
Also bumps console to `v2.2.3`

kvo: bump to v1.7.5-kvo.12

---

modules/ignition/assets.tf
modules/ignition/resources/services/kubelet.service

The default behavior of the kubelet's `--cloud-provider` flag is
changing in the upcomint k8s releases:
* v1.8 - auto detection of cloud provider using cAdvisor is deprecated but
still remains the default.
* v1.9 - auto detection of cloudprovider is still supported but no longer
the default, the new default will be no provider.
* v1.10 - auto detecting cloud provider is removed
For consistent non-autodetection behavior we need to ensure that we
always set the cloud-provider flag, even if it is explicitly set to no
provider.
cc @s-urbaniak @aaronlevy

modules/ignition: ensure --cloud-provider is set

---

installer/frontend/actions.js
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/ui.jsx

Add `configActions.set()` and use where possible.
Change `Deselect` component to use `configActions.setIn()`.
Rename `setField()` to `updateField()` to show that it is different from the other `setField()` functions defined in the same file.

frontend: Clean up use of configActions' set() and setIn()

---

installer/frontend/__tests__/examples/tectonic-baremetal.progress
installer/frontend/actions.js
installer/frontend/reducer.js

This appears to no longer be doing anything useful.

frontend: Remove unused "sequenceActionTypes"

---

installer/frontend/.eslintrc
installer/frontend/yarn.lock

Upgrade Jest, immutable, eslint and eslint-plugin-react. Includes Jest and immutable switching to the MIT license.
Also add eslint rule to disallow direct mutation of a React component's state.

frontend: Upgrade some dependencies

---

tests/rspec/lib/container_linux.rb
tests/rspec/lib/ssh.rb
tests/smoke/aws/vars/aws.tfvars.json

Make the Container Linux version getter resistant to races against CLUO.
By reading /var/lib/update_engine/prefs/aleph-version, we can be sure
that no matter if CLUO runs before or after the SSH command, we will
always know the version of the OS at installation time.
This commit also adds rescues to the SSH commands to ensure that the
executions will be retried if the node is rebooted by CLUO during the
test.
cc @alexsomesan

tests/rspec: re-factor cl version

---

installer/api/api.go
installer/api/handlers_containerlinux.go
installer/api/handlers_tectonic.go
installer/frontend/actions.js
installer/frontend/components/aws-cluster-info.jsx
installer/frontend/components/bm-cluster-info.jsx
installer/frontend/components/tectonic-license.jsx
installer/frontend/reducer.js
installer/frontend/server.js
installer/frontend/ui-tests/pages/clusterInfoPage.js

Replaces the `/containerlinux/images/amis` API endpoint with a `/tectonic/facts`, which includes all of the initial data needed by the GUI.
Also removes the `textarea`s for the license and pull secret inputs.
The license file / pull secret directory will be made configurable via a command line option / environment variable in a future PR.
Values in state override those returned by `/tectonic/facts`, so
- Uploading a progress file can override any license / pull secret files on disk
- Uploading a different file, then refreshing the page will keep the uploaded file

frontend: Automatically load Tectonic license / pull secret if they exist on disk

---

modules/tectonic/resources/tectonic-rkt.sh

Recently we started seeing clusters failing to come up because the
tectonic.service systemd unit did not run correctly. The journal would
show that rkt had failed to mount resolv.conf into the container and
thus failed to run the container but still systemd showed that
tectonic.service has completed successfully. This caused clusters to
show their bootstrapping as "complete" even though none of the Tectonic
manifests had been submitted to the API. The cause of this mistake is
two-fold:
1. rkt is failing to bind mount a file for some reason; and
2. systemd is marking the unit as successful.
This commit fixes issue number 2 by ensuring that if rkt fails to fun,
the `tectonic-rkt.sh` script exits with a non-zero exit status and
systemd will correctly mark the unit as failed.
cc @cpanato

modules/tectonic: ensure tectonic.service fails

---

tests/rspec/lib/ssh.rb

@cpanato this commit adds `Errno::ETIMEDOUT` to the list of caught exceptions as observed here: https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-2107/5/pipeline#step-378-log-233

tests/rspec/lib: retry if ssh times out

---

Makefile
tests/README.md
tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/azure_cluster.rb
tests/smoke/aws/vars/aws-ca.tfvars.json
tests/smoke/aws/vars/aws-exp.tfvars.json
tests/smoke/aws/vars/aws-net-canal.tfvars.json
tests/smoke/aws/vars/aws-vpc-internal.tfvars.json
tests/smoke/aws/vars/aws.tfvars.json
tests/smoke/azure/vars/basic.tfvars
tests/smoke/azure/vars/example.tfvars
tests/smoke/azure/vars/experimental.tfvars
tests/smoke/azure/vars/external-experimental.tfvars
tests/smoke/azure/vars/external.tfvars

A user should be able to configure the tectonic_base_domain variable
via environment variables without touching the tfvars files. E.g.
external contributors do not have access to the
`tectonic.dev.coreos.systems` domain.
//CC @coresolve @derekparker

tests: Make cluster base domain configurable

---

Makefile

`/bin/smoke` represents an actual file which is compiled with this
recipe. Removing the `PHONY` flag enables Make to decide on its own when
to rebuild. If the source files are less recent than the compiled
binary, there is no need to rebuild the binary, thereby saving time for
local and CI test execution.
@cpanato @squat What do you think?
See
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

tests: Remove PHONY flag from bin/smoke Make target

---

tests/rspec/lib/cluster.rb

The bootkube and tectonic systemd services can take up to 10 minutes to
start. This patch bumps the retry value to prevent timeouts in our CI.
@squat We have seen multiple timeouts like [this](https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-2137/10/pipeline/). I guess the machines are restarting during `wait_for_bootstrapping`. Bumping the timeout might be a quick fix. What do you think?

tests: Bump wait_for_bootstrapping timeout

---

modules/tectonic/resources/manifests/updater/operators/tectonic-cluo-operator.yaml

Today we ran  into an issue where the `tectonic-cluo-operator` was requesting `80Mi` and kept OOMing due to memory limits. Increasing the limit to `100Mi`allowed the `tectonic-cluo-operator` pod to start and after a few moments the memory limit dropped down to `40Mi`.
It might be worth increasing the hard limits just to account for any overhead.

Increase Memory Limits

---

Makefile

1. Mount the hosts ssh key into the correct home folder inside the
Docker container.
2. Pass tectonic_admin_email and tectonic_admin_password into the Docker
container.

tests: Fix ssh mount and pass tectonic email + password

---

tests/smoke/cluster_test.go

This PR changes the order of the smoke test execution.
1. Check if all nodes are running
2. Check if all resources got created
3. Check if all pods are running
----
6. Kill the API server
We are not running the golang smoke tests in parallel (See [smoke-tests.rb](https://github.com/mxinden/tectonic-installer/blob/f67aec72e82bc2befb031f6e8a0faae32a34e1ed/tests/rspec/lib/smoke_test.rb#L16) `-test.parallel=1`).

tests: run kill-api-server test last

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/azure_cluster.rb
tests/rspec/lib/cluster.rb

The Tectonic installer CI had repeatedly failed with timeouts waiting
for the bootkube and tectonic service to finish.
This patch includes the following improvements:
- The bootkube and tectonic systemd unit is only deployed on one master
node. Instead of relying on the fact, that we choose the right master
node to check if the services finished, we check all of them and return
true if the services succeeded on one of them
- Instead of checking for success via:
`systemctl is-active <service>`, we check whether the
`init_<service>.done` file exists. `is-active` returns non zero when the
bootstrap succeeded but the node restarted in the meantime. The
`init_<service>.done` file is only written when the service exits with a
non-zero exit code [1]
[1] See `ExecStartPost` …

tests: Improve wait_for_bootstrapping

---

installer/api/api.go
installer/api/handlers_tectonic.go
installer/cmd/installer/main.go

If present, this directory will be searched for the Tectonic license and pull secret files to auto-load into the GUI. Otherwise, the installer executable directory will be used.

frontend: Add command line option to specify the secrets directory

---

installer/frontend/components/base.jsx

Clone state before saving it so that `clusterConfig.extra` doesn't get unset in the original state object.

frontend: Fix to not modify state when saving progress

---

config.tf

This PR bump the Tectonic Monitoring stack to version 1.7.0 for the November release.
@alexsomesan @s-urbaniak 
/cc @fabxc @pst @robszumski

*: bump tectonic monitoring to 1.7.0

---

installer/frontend/__tests__/protocols.js
installer/frontend/actions.js
installer/frontend/cluster-config.js
installer/frontend/reducer.js

The `Field` constructor adds the field's default value to `DEFAULT_CLUSTER_CONFIG`, so we don't need to also define those defaults when `DEFAULT_CLUSTER_CONFIG` is initialized.
Some fields remain for several different reasons. They should be refactored away over time.

frontend: Remove most DEFAULT_CLUSTER_CONFIG initial entries

---

Documentation/dev/node-bootstrap-flow.md

This clarifies some details regarding the node-bootstrapping service and docker. Those questions came up from @colemickens and @coresolve, so it's better to have this info in the devdocs.

docs/bootstrap: clarify docker details

---

modules/bootkube/resources/manifests/pod-checkpointer.yaml

In the pod-checkpointer manifest the updateStrategy is defined twice.
This patch removes one definition.
@alexsomesan am I overlooking something here?

Remove duplicate updateStrategy

---

installer/frontend/components/ui.jsx

This removes the CSS class `undefined` that was being output for certificate and private key inputs and also cleans up the code a bit.

frontend: Remove "undefined" CSS class

---

installer/frontend/components/cluster-info.jsx

These can't be React elements because they get written to state, which meant the whole React object would be dumped into the .progress file if these fields failed validation.

frontend: Fix Tectonic license and pull secret errors to be strings

---

tests/rspec/lib/cluster.rb
tests/rspec/lib/shared_examples/k8s.rb

If bootkube or Tectonic failed to start we abort the test execution but before that, we run forensics script to get some information.
cc @squat

Add check for see if bootstrap failed and then run Forensic script

---

tests/rspec/lib/container_linux.rb

This change ensures that a Container Linux version will be reported even
if update-engine has not finished running and creating an
`aleph-version' file. If this is the case, we will simple read the
version from the canonical location, /usr/share/coreos/release.
cc @cpanato @enxebre

tests/rspec/lib: ensure CL version is available

---

tests/rspec/lib/ssh.rb

sometimes we receive the same IP for the machines we created and if it runs in the same slave if can throw this exception: Net::SSH::HostKeyMismatch to avoid that we are not checking the key
solution: clean the know_hosts in the end of the test
Jira: https://jira.prod.coreos.systems/browse/INST-552

tests: do not check the host key when ssh 

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/server.js

We only actually use the region names from the "amis" API call result, so we can simplify the code a bit by storing just the names in redux.

frontend: Clean up AWS regions

---

modules/dns/designate/etcd.tf
modules/dns/designate/master.tf
modules/dns/designate/tectonic.tf
modules/dns/designate/worker.tf

The DNS zone was incorrectly specified as data rather than a resource,
which prevented it from being created. Changed to resource and updated
related references.
See https://github.com/coreos/tectonic-forum/issues/197#issuecomment-338516712

modules/dns/designate: Fix buggy zone creation

---

platforms/openstack/neutron/main.tf

Every OpenStack cluster gets a master load balancer, so use that IP address to advertise the apiservers.

platforms/openstack: Set apiserver advertise address to master LB FIP

---

installer/frontend/components/users.jsx

With the `Connect` component, `validator` is specified when creating the `Field`, not passed as an attribute to `Connect`.

frontend: Remove 3 unused "validator" attributes

---

installer/frontend/components/cluster-info.jsx

Fixes the Cluster Info page's next button enabled / disabled state.
The problem only occurred if you completed the install, then clicked Start Over and went through the wizard again. In that case, the Next Step button would stay disabled even after filling in the name field. You needed to upload the license and pull secret again to enable the button.

frontend: Fix Cluster Info page's next button after Start Over

---

config.tf
modules/dns/ddns/main.tf
platforms/aws/main.tf
platforms/azure/main.tf
platforms/vmware/provider.tf
tests/rspec/lib/cluster.rb
tests/rspec/lib/ssh.rb

We were lagging quite a few versions behind on some of the providers.
This means we're not incorporating potentially critical fixes from upstream. 
This is especially relevant in the light of the recently occurring Azure DNS API errors.
/cc: @sym3tri

Terraform providers: bump versions to latests releases

---

tests/rspec/lib/cluster.rb

... in case of failure.
Currently we print only the service log of the offending service, but
for debugging this might not be enough.
/cc @cpanato @alexsomesan

tests/cluster: print logs of all relevant services

---

modules/bootkube/resources/bootkube.service
modules/tectonic/resources/tectonic.service

bootkube.service and tectonic.service are meant to be path activated
only.
On nodes not being the bootstrap masters, they are being activated
nevertheless, because the are wanted by multi-user.target.
This fixes it by removing the dependency.
Fixes INST-436

modules/[bootkube,tectonic]: remove dependency multi-user.target

---

config.tf

This is a placeholder so that the [release automation job](https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-release-automation/) can generate
a new payload, which will be used by [nightly upgrade test job](https://jenkins-tectonic-installer.prod.coreos.systems/job/upgrade-test/).
Ideally this could be done automatically when we cut a release branch.

config.tf: Bump tectonic version to 1.8.

---

modules/bootkube/resources/manifests/kube-dns.yaml
modules/tectonic/resources/manifests/identity/services.yaml

This fixes the patch merge conflict because the upstream patch
merge code can't handle targetPort well.

kube-dns.yaml, identity/services.yaml: Add targetPort parts.

---

config.tf

Fixes https://jira.prod.coreos.systems/browse/CONSOLE-221 and adds some more menus to ALM stuff (https://github.com/coreos-inc/bridge/pull/1841)

Bump console to v2.3.1.

---

README.md

The documentation files were moved to a different repository, so point this link at the official installation document web page.

README: Fix RHEL link

---

modules/bootkube/resources/manifests/01-tectonic-namespace.yaml

I erroneously assumed that there was still another one in the tectonic
module, and merged it because the smoke tests passed.

1.7.9: restore tectonic-namespace.yaml.

---

installer/frontend/components/etcd.jsx
installer/frontend/ui-tests/pages/etcdConnectionPage.js

`tectonic_etcd_servers` shouldn't include a port number, so the UI shouldn't be asking for it.
---

frontend: Fix etcd address field to not ask for a port number

---

installer/frontend/cluster-config.js
installer/frontend/components/bm-matchbox.jsx

Removes `bootCfgInfly` hack.
Clears `osToUse` (`BM_OS_TO_USE`) and `matchboxHTTP` at the same time, which I think is better to ensure they are consistent.
This causes the spinner to start when you being typing rather than when the API call actually starts, which I think is better since otherwise the call can be so fast that the spinner doesn't visibly animate, giving no visual feedback.

frontend: Improve bare metal Matchbox Address page spinner

---

Jenkinsfile

The container linux version parameter was removed recently. This
reference has to be removed as well. Otherwise, the wanted container
linux version will be an empty string which results in:
```
module.workers.data.aws_ami.coreos_ami: data.aws_ami.coreos_ami: Your
query returned no results. Please change your search criteria and try
again.
```

tests: Remove unused param reference

---

modules/dns/designate/etcd.tf
modules/dns/designate/master.tf
modules/dns/designate/tectonic.tf
modules/dns/designate/worker.tf

Reverts coreos/tectonic-installer#2201
Realized today that the previous behavior was intentional. The DNS zone is expected to exist already, and is therefore referenced as a `data` type rather than `resource`. This allows multiple clusters to use the same zone.
This also matches the behavior of the [Route53 provider](https://github.com/coreos/tectonic-installer/blob/master/modules/dns/route53/tectonic.tf#L1)

Revert "modules/dns/designate: Fix buggy zone creation"

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/etcd/nodes.tf
modules/vmware/etcd/variables.tf
modules/vmware/node/nodes.tf
modules/vmware/node/variables.tf
platforms/vmware/main.tf
platforms/vmware/variables.tf

Currently, Tectonic clusters are restricted to using a single VMWare
cluster.  VMware clusters allow HA behavior at the VM level.  This change
will allow virtual machines to be mapped to VMware clusters.
Jira issue: https://jira.prod.coreos.systems/browse/FR-363

platforms/vmware: Add ability to span VMware clusters

---

installer/frontend/components/k8s-cidrs.jsx
installer/frontend/ui-tests/pages/networkConfigurationPage.js
installer/frontend/ui-tests/pages/networkingPage.js

This just adds a warning message. It is still possible to ignore the warning and continue with the installation.
Also changes the other alert message titles on the same page to sentence case.
Shown here along with the separate "IP range too small" warning.

frontend: Add warning if pod IP range might conflict with Docker Bridge

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/etcd/nodes.tf
modules/vmware/etcd/variables.tf
modules/vmware/node/nodes.tf
modules/vmware/node/variables.tf
platforms/vmware/main.tf
platforms/vmware/provider.tf
platforms/vmware/variables.tf

Currently, Tectonic clusters must reside entirely within a virtual
datacenter.  This change will allow the virtual machines to be mapped to
the virtual datacenters.
Jira issue: https://jira.prod.coreos.systems/browse/FR-361

platforms/vmware: Add ability to span virtual datacenters

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/etcd/nodes.tf
modules/vmware/etcd/variables.tf
modules/vmware/node/nodes.tf
modules/vmware/node/variables.tf
platforms/vmware/main.tf
platforms/vmware/variables.tf

Currently, all VMs in a cluster must be assigned to a single VMware
resource pool.  This change allows VMs to be assigned to different
resource pools so that, for example, master nodes won't run into a
resource contention with worker nodes.
Jira issue: https://jira.prod.coreos.systems/projects/FR/issues/FR-364

platforms/vmware: Add ability to assign VMs to resource pools

---

README.md

Update links to openstack and vmware terraform install docs, and make them reference format, too.
Ref: https://coreos.slack.com/archives/C2ZA5QGMV/p1509456941000394

README: Fix broken links to openstack and vmware

---

installer/frontend/actions.js
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/ui.jsx

Remove unused `autoClean` `Field` attribute.
Add `dirtyActions` and use to simplify marking fields as dirty:
- Remove `markIDDirty()` helper.
- Rename `markDirty()` and `markDirtyUpload()` to `makeDirty()` to since they are all identical.
Remove now unused `makeClean()`. If in the future a component needs to mark a field as "clean", it can define its own `makeClean()` action.

frontend: Clean up "dirty" / "clean" actions

---

tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy

GitHub by default does not return all repository labels, but uses
pagination. This patch bumps the limit to 100 which we will hopefully
never reach.
Thanks @cpanato for uncovering this.

tests: Request all repository labels on PR trigger

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/etcd/ignition.tf
modules/vmware/etcd/variables.tf
modules/vmware/node/ignition.tf
modules/vmware/node/variables.tf
platforms/vmware/main.tf
platforms/vmware/variables.tf

Currently, all nodes of a given role (etcd, master, worker) need to
share a common network gateway.  This change will allow network gateways
to be assigned to nodes individually to support nodes being spread
across subnets with different gateways in a multi-az kind of approach.
Jira issue: https://jira.prod.coreos.systems/projects/FR/issues/FR-369

Add ability to map VMs to network gateways

---

installer/scripts/maintenance/clean-aws.sh
installer/scripts/maintenance/tag-aws.sh

The grafiti container is started with the `--rm` flag. Thereby the
following `docker rm` step is not needed and fails as there is no
container to delete. This patch removes the second step.

tests: Remove redundant container removal step

---

config.tf

This bumps the TPO and Tectonic Monitoring to `v1.7.1`.
@sudhaponnaganti @s-urbaniak @alexsomesan

monitoring: bump tectonic monitoring to v1.7.1

---

config.tf

Updates node-agent to cd69b4a0f65b0d3a3b30edfce3bb184fd2a22c26. This
is to add support for tectonic-torcx updating the docker image at the
same time as the kubelet.

config.tf: update node-agent.

---

images/tectonic-smoke-test-env/Dockerfile

In order to trigger the conformance tests from rspec, the docker client
needs to be installed. This patch adds the install instructions to the
docker file.
This is needed for the conformance tests. Once they are approved, this can be merged, the image can be build via Jenkins, the conformance tests PR will be updated to contain the new image tag and then that PR can be merged as well.

tests: Add docker client to tectonic-smoke-test-env image

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
platforms/vmware/provider.tf
platforms/vmware/variables.tf

Change datacenter to datacenter_id. Updated provider.tf and variables.tf to reflect changes.
Default variable to be "vm" since this will primarily be used to create VMs.
See https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/CHANGELOG.md
Breaking changes presented in 0.4.0 to vsphere_folder that require updating.

update vsphere arguments to reflect changes in 0.4.2 provider

---

installer/frontend/components/header.jsx

[Pod-proxy](https://github.com/coreos-inc/pod-proxy/) assigns a Pod per user session with a cookie. 
Sending cookies with the modified request to prevents an unnecessary Pods from being spawned with Pod Proxy.

Send credentials when checking release version

---

config.tf

Fixes an issue where the alertmanager wasn't shown on the cluster settings page.

Bump console to v2.3.3.

---

platforms/vmware/provider.tf

The necessary changes for the vsphere provider upgrade have not been
completed so reverting to old provider version for 1.7.9 release.

platforms/vmware: Revert vsphere provider version

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/__tests__/examples/aws.json
installer/frontend/__tests__/examples/metal.json
installer/frontend/ui-tests/output/aws.tfvars
installer/frontend/ui-tests/output/metal.tfvars
installer/frontend/ui-tests/tests/awsInstaller.js
installer/frontend/ui-tests/tests/bareMetalInstaller.js
installer/frontend/ui-tests/utils/terraformTfvars.js

Instead of comparing against the unit test example JSON files, diff the generated tfvars files against what we expect them to be. This means we can diff against several additional vars and also allows us to simplify the test code a bit.

tests/frontend: Change Nightwatch tests to output tfvars files

---

installer/frontend/components/aws-vpc.jsx
installer/frontend/components/cidr.jsx

Increase subnet label column width that was not large enough for some region labels.
Decrease DNS label column width to give those input fields a little more space.
cc @tlwu2013 
Before | After
--- | ---

frontend: Improve Networking page column sizes

---

config.tf

* Updates tectonic-torcx which sets the docker versions to install for Kubernetes 1.8 and 1.9

config.tf: Update tectonic-cluo-operator to v0.2.4

---

installer/frontend/aws-actions.js
installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/make-node-form.jsx
installer/frontend/form.js

Also fixes a bug where Next Step button on AWS Credentials page could be incorrectly disabled after restoring a progress file.
Field validators were being used to trigger the loading of extra data. This PR refactors the code to do that in `getExtraStuff()` callbacks instead, which is what `getExtraStuff()` is intended for.
Changes `getDefaultSubnets()` to not try to read subnet IDs from the `/aws/default-subnets` response. That API endpoint actually only returns default subnet CIDRs, not existing subnet IDs.
Hardcode `Region` value in `getRegions()` because `getRegions()` is called before the user has picked a region (user can't pick a region until we get the list of regions to pick from!).

frontend: Stop using field validators to achieve side effects

---

modules/gcp/etcd/etcd.tf
modules/gcp/master-igm/iam.tf
modules/gcp/master-igm/master.tf
modules/gcp/worker-igm/iam.tf
modules/gcp/worker-igm/worker.tf

Started by using ```resource_google_project_iam_policy``` https://github.com/terraform-providers/terraform-provider-google/pull/691
But ```google_project_iam_member``` gives more granular control and no race problems

platform/gcp: add iam support with service accounts and scopes

---

platforms/openstack/neutron/main.tf

platforms/openstack/neutron: Bump openstack provider to 1.0.0

---

Documentation/variables/vmware.md
examples/terraform.tfvars.vmware
modules/vmware/node/variables.tf
platforms/vmware/variables.tf

Error getting plugins: module root:
module masters: required variable "vm_network_label" not set
module workers: required variable "vm_network_label" not set
Fix examples:
var.tectonic_vmware_etcd_networks
Terraform map of etcd node(s) vSphere network portgroups, Example:
tectonic_vmware_etcd_ip = {
"0" = "mynet-0"
"1" = "mynet-1"
"2" = "mynet-2"
}

Fix variable naming for vmware networks, remove unused variable vm_network_label left over from PR #2282

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/make-node-form.jsx
installer/frontend/form.js

3 related fixes for validation on the AWS Credentials page.
- Fix `getExtraStuff()` to always return a promise. Looks like this was an old bug that only recently became visible due to AWS Credentials page changes.
- Add `asyncValidator()` for AWS regions field. Needed so that the containing form
notices when the API call fails and the field is therefore invalid.
- Delay `/aws/iam-roles` API call until AWS Credentials page form has been completed. We don't need a region to call `/aws/iam-roles`, so the call we being made as soon as the AWS id and secret key were provided. Unfortunately, that could result in lots of unnecessary API calls as the values are entered. To avoid this, wait until the whole form (include the region dropdown) is completed.

frontend: AWS Credentials page validation fixes

---

modules/gcp/master-igm/iam.tf
modules/gcp/worker-igm/iam.tf

We use the branch name on the temporary cluster_name for testing which make us suffering this issue https://github.com/terraform-providers/terraform-provider-google/issues/671
This should restrain it

platform/gcp: reduce service account name terraform google provider #671

---

Jenkinsfile
tests/jenkins-jobs/scripts/report-status-to-github.sh

Using the second last commit sha is not proficient, as master might be
ahead of the PR, thereby reporting a status of a commit on master and
not the HEAD of the PR.

tests: Choose right commit sha

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/form.js

This makes `Field`'s `isValid()` also check for "extra data" errors.
This allows the AWS region field's `asyncValidator()` to be removed since it was just checking for the existence of an "extra data" error.

frontend: Check for "extra data" errors when doing field validation

---

installer/frontend/form.js

Not sure why this line ever existed, but dependencies will flip between invalid and valid, so it doesn't make sense to clear a field's "extra data" just because a dependency becomes invalid.

frontend: Fix to not clear "extra data" when dependencies are unsatisfied

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/cluster.rb
tests/rspec/lib/tfstate_file.rb

For better upstream Terraform debugging we would like to log the network
interfaces related to the VPC. For further details see:
https://github.com/terraform-providers/terraform-provider-aws/pull/1051
@erikkn This change will add something along the lines of this to the test log:
``` json
{
"NetworkInterfaces": 
...
}
```
The goal would be to be able to analyse this with the Elastic search project. Should I log any particular keyword before or after so we can extract it from the logs?

tests: Log network interfaces before and after destroy

---

installer/frontend/ui-tests/utils/terraformTfvars.js

This variable no longer exists in the generated tfvars file.

tests/frontend: Remove redundant tectonic_admin_password_hash deletes

---

modules/bootkube/resources/manifests/pod-checkpointer.yaml

Removes -v=4 because it is very noisy and will fill logs unnecessarily.

bootkube/pod-checkpointer: remove -v=4

---

installer/frontend/components/base.jsx

We shouldn't be relying on any of these entries when restoring progress, and removing them ensures that we are not.
`error`, `error_async`, `extraError` and `ignore` don't need to be saved because validation is run on all fields when the progress file is loaded, which recalculates all of these values.
`inFly` and `extraInFly` indicate whether an API is in progress, which doesn't make sense to store in the progress file.

frontend: Remove unnecessary entries when saving progress file

---

installer/assets/frontend/css/styles.css
installer/frontend/components/ui.jsx

`wiz-invalid` and `wiz-dirty` are only ever used together, so we only need one.

frontend: Remove redundant CSS class "wiz-dirty"

---

installer/frontend/components/aws-define-nodes.jsx

If `/aws/iam-roles` returned an error, that error case was not being handled, resulting in a JS error.

frontend: Fix handling of errors when loading IAM roles from AWS API

---

modules/aws/master-asg/resources/detect-master.sh
modules/aws/master-asg/resources/init-assets.sh
modules/ignition/resources/bin/s3-puller.sh

This commit makees several modifications to ensure the init-assets
service will retry any network operations, e.g. wget, curl, aws etc.
Rather than adding individual retries for each of the dozens of
operations that could fail, this commit adds retries to the docker
commands that encompass those operations.
Fixes: INST-341, INST-574
cc @s-urbaniak

modules: retry init assets

---

platforms/aws/tectonic.tf

Currently provisioning TLS certificates fails if the internal DNS zone
is disabled.
This fixes it.
/cc @squat @soggiest

platforms/aws: set fqdns correctly if internal zone is disabled

---

installer/frontend/cluster-config.js
installer/frontend/components/aws-vpc.jsx
installer/frontend/form.js

Drop `extraData` param because that data is already available via the `clusterConfig` param.

frontend: Remove validator extraData param

---

installer/frontend/__tests__/examples/aws.json
installer/frontend/cluster-config.js
installer/frontend/server.js

Don't include `tectonic_aws_master_custom_subnets` or `tectonic_aws_worker_custom_subnets` in the generated tfvars file unless one of those subnet fields was edited. This will also work when
restoring .progress files since those files include the `dirty` fields.
Note that currently, just opening the advanced VPC options is enough to mark the subnet fields as `dirty`.
Also removes the `progress` attribute that was being passed to `toAWS_TF()` / `toBaremetal_TF()` because they don't use it.

frontend: Don't set custom subnets unless those fields have been edited

---

installer/frontend/components/aws-vpc.jsx

This fixes a bug where resetting the subnet IDs in Redux (e.g. by selecting a different VPC), did not reset the dropdowns to the default "Select a subnet" option.
If there was only one subnet in the dropdown, this bug stopped you selecting that single subnet. Clicking / changing any other form element on the page reset the subnet dropdowns, fixing the problem.

frontend: Fix resetting the AWS existing subnet dropdown

---

Documentation/variables/aws.md
examples/terraform.tfvars.aws
platforms/aws/main.tf
platforms/aws/variables.tf

Allow specifying the AWS credentials profile to use with the AWS platform. As far as I can tell this should work fine, it's useful to me as I juggle different AWS profiles.

Allow specifying of AWS profile

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

We made the effort to disable alpha API groups in Tectonic clusters, but
we do not explicitly set the --runtime-config to "". "" is the default
setting for the --runtime-config flag, but setting it explicitly, as
@diegs explains, allows us to detect conflicts on updates.
fixes INST-321

modules/bootkube: be explicit about runtime

---

tests/rspec/lib/k8s_conformance_tests.rb

With the new 1.82 conformance test image, run time went up. This patch
adjusts the conformance test timeout accordingly to 2 h.

tests: Bump conformance test timeout

---

installer/frontend/__tests__/protocols.js
installer/frontend/server.js

This param is no longer used by `toAWS_TF()` or `toBaremetal_TF()`.

frontend: Remove commitToServer()'s unused "opts" parameter

---

installer/frontend/cluster-config.js
installer/frontend/components/aws-vpc.jsx

Replace the almost identical `toVPCSubnet()` and `toVPCSubnetID()` functions with a single `selectedSubnets()` function.

frontend: Combine toVPCSubnet() and toVPCSubnetID()

---

installer/frontend/components/aws-vpc.jsx

Oops, shouldn't use `selected` with React. Fixes a JS warning.

frontend: Remove <option> "selected" attribute

---

config.tf

This change most prominently ships Prometheus 2.0 as the Tectonic
Monitoring Prometheus instance.
@s-urbaniak @alexsomesan 
/cc @robszumski @rezaloo @pst @ant31

*: Upgrade Tectonic Monitoring to 1.8

---

platforms/metal/profiles.tf

Fixes #2345
Solution as described here: https://github.com/coreos/docs/commit/3c4bcacd0081e534c5b4943afde5cf1c0a7753a6
Relevant links:
coreos/bugs#1239
http://ipxe.org/appnote/debian_preseed

platforms/metal: Add initrd argument to kernel cmdline

---

modules/bootkube/variables.tf
platforms/aws/tectonic.tf

Pass the variable `tectonic_self_hosted_etcd` to the bootkube module, as this is currently omitted. BTW, why is there a default value for `tectonic_self_hosted_etcd` in bootkube? If there were no default, this omission would be detected.

platforms/aws: Pass tectonic_self_hosted_etcd variable to bootkube module

---

modules/aws/master-asg/ignition.tf
modules/aws/master-asg/resources/detect-master.sh
modules/aws/master-asg/variables.tf
modules/tectonic/variables.tf
platforms/aws/main.tf

This commit fixes issue #2419.
This issue occurs because we recently added -o pipefail to the
detect-master.sh script. This causes a previously undetected issue to
surface and break bootstrapping for clusters with no private-endpoints.
API_HEALTHY=$(aws elb describe-instance-health --region="$REGION"
--load-balancer-name "$CLUSTER_NAME-int" | jq -r '[ .InstanceStates[] |
select(.State | contains("InService")) ] | length > 1')
is hardcoded to use the internal loadbalancer. Without pipefail, this
aws command would 404 and the error would get swallowed by the pipe.
API_HEALTHY would never be true, even if the API was actually healthy,
so the rest of the script would run.
Now, since the pipefail option is set, that command correctly errors out
and the script execution is aborted.
We simply …

modules/aws: detect-master assumes lb

---

Jenkinsfile
tests/rspec/lib/name_generator.rb
tests/rspec/spec/meta-tests/name_generator_spec.rb

Doing that because in some tests (in azure e.g.) the test name is big and we don't have the PR-number in the cluster name, then we don't know which resource group belongs to which PR

test: doing some crazy naming :smile:

---

modules/net/canal/resources/manifests/kube-flannel.yaml
modules/net/flannel_vxlan/resources/manifests/kube-flannel.yaml

Edit flannel configmap to enable hairpin mode
Hairpin mode is needed to allow pods to communicate with themselves via Service IP. This change is required as the kubelet --hairpin-mode flag is not supported when CNI is being used.

kube-flannel-cfg: enable hairpin mode

---

tests/rspec/lib/azure_vpn.rb

The index in rubys `each` iterator is zero indexed. Previously
`create_resource` would never raise an error if the last retry fails,
because `MAX_RETRIES > count` was always true. This patch makes sure
`create_resource` properly raises an error in case the last iteration
fails.

tests: Make sure `create_resource` raises error on failure

---

tests/rspec/lib/shared_examples/k8s.rb

- Retry via `with_retries` lib
- Surfacing `stderr`
- Raising exception on failure
https://github.com/coreos/tectonic-installer/pull/1938#pullrequestreview-73712368

tests: Addressing testing related cleanups from k8s 1.8 merge

---

tests/rspec/lib/shared_examples/k8s.rb

Replace `fin` with `exit_code` as discussed in [1].
[1]
https://github.com/coreos/tectonic-installer/pull/2436/files#r152238782

Tests: Refactor var naming

---

tests/rspec/lib/k8s_conformance_tests.rb
tests/rspec/lib/shared_examples/k8s.rb

in our packet.net configuration, we don't provision the machine with `docker`, only with `rkt`. To run the conformance tests on this platform we need to do a small adjustment in our RSpec framework

test: using rkt in metal platform to run conformance tests

---

installer/frontend/app.jsx
installer/frontend/components/cluster-info.jsx
installer/frontend/server.js

Delay initial field validation until `facts` API call has completed.
The `facts` response contains initial values for the Tectonic license and pull secret, so making this change allows us to remove the `ClusterInfo.canNavigateForward()` hack.

frontend: Remove ClusterInfo.canNavigateForward hack

---

modules/bootkube/self-hosted-etcd.tf

most of the counts depend on `self_hosted_etcd != ""`, while one depends on `self_hosted_etcd == "enabled"`. We should normalize this.
cc @s-urbaniak

modules/bootkube: unify self-hosted etcd

---

modules/net/calico/resources/manifests/kube-calico.yaml
modules/net/canal/resources/manifests/kube-calico.yaml

1) Disable termination grace period to account for Kubernetes v1.8 changes to DaemonSet behavior ([projectcalico/calico#1293](https://github.com/projectcalico/calico/pull/1293))
2) Fix IPIP mode casing [projectcalico/calico#1233](https://github.com/projectcalico/calico/pull/1233)
This has already been patched in bootkube: https://github.com/kubernetes-incubator/bootkube/pull/772

modules/net: Disable Calico termination grace period

---

images/tectonic-smoke-test-env/Dockerfile

We were facing issues running `bundle install` with different `bundler` versions. This patch specifies the bundler version inside the Dockerfile.

tests: Specify bundler version in smoke test env docker image

---

tests/jenkins-jobs/tectonic_smoke_test_docker_image_job.groovy

Extending the Jenkins job to build the smoke test env image without any
previously cached docker image layers.
As suggested by @erikkn, we should add this.

tests: Build smoke test env image without cache

---

modules/container_linux/main.tf
modules/container_linux/outputs.tf
modules/container_linux/variables.tf
platforms/aws/main.tf
platforms/azure/main.tf
platforms/gcp/main.tf
platforms/metal/matchers.tf

Terraform minor version 0.11.0 contains improved module support,
with real support for pinning module versions using the `version`
directive, e.g.:
```hcl
module "foo" {
source = "bar"
version = "baz"
}
```
Unfortunately, this directive clashes with a variable in the
`container_linux` module by the same name; Terraform is unable to
handle variables and directives with the same name in a given module
block, so the `version` _variable_ is never passed to the module.
Fixes: https://github.com/coreos/terraform-aws-kubernetes/issues/10
cc @s-urbaniak @enxebre

modules,platforms: variables cannot be "version"

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

This PR adds the source & target Git branch to the log file name, which is used by Logstash to add those values to the document as attributes.

tests: add git branches as attributes

---

installer/frontend/__tests__/examples/aws-vpc.json
installer/frontend/cluster-config.js

Unit test expected output was also incorrect.
This appears to have been the case since `tectonic_aws_worker_root_volume_iops ` was first added by https://github.com/coreos/tectonic-installer/commit/03fadb2e692f41913e3ea34f9a6ed3dd2a5ac19d.

frontend: Fix bug where master's volume IOPS was also used for workers

---

modules/update-payload/assets.tf

The [Latest nightly release build](https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-release-automation/job/build-tectonic/job/master/34/) revealed that the payload generation broke after #2465:
```
* resource 'template_dir.payload_appversions' config: unknown variable referenced: 'versions'. define it with 'variable' blocks
```
```
* template_dir.payload_appversions: failed to render ../tectonic/resources/manifests/updater/app_versions/app-version-kubernetes-addon.yaml: 9:21: unknown variable accessed: kubernetes_addon_operator_version
```
The fixes it and re-enables building releases of master.

modules/update-payload: fix payload gen failure introduced by #2465

---

Jenkinsfile
tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/metal_support.rb
tests/rspec/lib/shared_examples/k8s.rb

This patch adds the log files to the `build` folder instead of the
`tests` folder. By doing so, we limit the mutability of the repo to the
`build` folder.

tests: Move logs to build folder

---

modules/tls/kube/self-signed/outputs.tf

The collection of ids being joined was not explicitly
defined as a list, which is an error in Terraform 0.11.0.

modules/tls/kube/self-signed: Make list explicit

---

config.tf

Changes include:
- Adds lots of ALM stuff (and shows ALM by default now)
- Bug fixes.
- Namespaces are shown in list views.
- Support for k8s 1.8 objects such as CronJobs.
- Better graphs.
- "n crash looping pods" on front page now links to the Pods list, filtered to only show crashlooping pods.
- "n alerts firing" now links to alertmanager UI
- If multi cluster CRD is installed, cluster picker & cluster manager are shown.
See https://github.com/coreos-inc/bridge/compare/v2.5.3...v2.3.4 for the full list of commits.
This should go in the 1.8 release candidate.

Bump console to v2.5.3.

---

tests/rspec/lib/metal_support.rb
tests/rspec/spec/metal/basic_spec.rb

tests/ci: wait for terraform provide the ipxe and then start the node…s (#2476)
This is needed for https://github.com/coreos/tectonic-installer/pull/2503

Cherry-pick bare metal test into 1.8.2 branch

---

modules/tls/kube/user-provided/outputs.tf

This commit is a follow up of the changes made in #2494 and converts the
user-provided certs to an explicit Terraform list for compatibility with
Terraform 0.11.x.
Related:
https://github.com/coreos/terraform-aws-kubernetes/issues/13
https://github.com/coreos/tectonic-installer/pull/2494
https://github.com/coreos/tectonic-installer/pull/2502

modules/tls: make certs a list

---

platforms/gcp/tectonic.tf

tectonic_etcd_count has to be set explicitly to something different than "0" for deploying GCP. This fixes it

platform/gcp: fix ectonic_etcd_count=0

---

tests/jenkins-jobs/tectonic_installer_nightly_trigger_with_k8s_conformance.groovy

So far conformance tests were only run on bare-metal nightly. This PR
includes all remaining platforms (AWS, Azure, GCP) as well.

tests: Run conformance tests on all platforms nightly

---

modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

In order to install the operator for old clusters during upgrade,
'CreateOrUpgrade' annotation is required for the operator's deployment
manifest.
Also the "managed-by-channel-operator" label is necessary as well.

operators: Add necessary annotation for alm-operator.

---

installer/frontend/components/aws-define-nodes.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/make-node-form.jsx
installer/frontend/ui-tests/pages/nodesPage.js
installer/frontend/validate.js

Also change validation error wording from e.g. "Provide a value less than 11" to "Cannot be greater than 10".
cc: @robszumski

frontend: Fix max value validation for instance count fields

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh
tests/rspec/lib/cluster_support.rb

We want to use the Logstash KV plugin (https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html). This plugin parses through the log files, looking for key=value expressions. The KV filter uses the '=' and uses the ',' character as split field.

tests: change logic for the kv filter

---

config.tf

That be should all? However, there is no KVO image available yet for it.
/cc @sudhaponnaganti

config.tf: bump Kubernetes to 1.8.4

---

modules/azure/vnet/lb-console.tf
modules/azure/vnet/lb.tf

This is a small change to clarify the primary purpose for the load balancer in Azure i.e., to front Tectonic Console and Tectonic Identity.
Originally, the name of the load balancer was `${var.cluster_name}-api-lb` which is misleading, especially in Azure private implementation instances (where the load balancer is not used to front the Kubernetes API).

azure/vnet: Update Ingress LB name to `<cluster>-tectonic-lb`

---

config.tf

This is to make upgrade test pass as it's trying to upgrade from
179-3, which the current kvo in the config.tf doesn't know about.

config.tf: Bump KVO to v1.8.4-kvo.3

---

modules/ignition/resources/services/kubelet.service

Picked up from https://github.com/coreos/bugs/issues/2074
Need to add a wants here so that using nfs persistent volumes work as
intended on tectonic.
Without this change you see an error like:
```
Mounting arguments: 192.168.1.2:/mnt/user/tectonic /var/lib/kubelet/pods/6961c181-9d79-11e7-abdc-005056a6ea29/volumes/kubernetes.io~nfs/nfs nfs []
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```

Adds Wants=rpc-statd.service to kubelet

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Get the build job status and add it to the document file name.The value is used by Logstash to add this as as an attribute to all the documents.

tests: add jenkins build status

---

installer/frontend/components/aws-cloud-credentials.jsx

This error was already rendered as a field validation error on the
regions dropdown, but that meant it was only shown if the dropdown was
marked as "dirty" in Redux, which doesn't happen until its value is
first set.
Explicitly rendering the AWS API error solves this problem, but it does
mean that the error message can now possibly be displayed twice. Solving
that will require a larger code change, so this is an initial quick fix.

frontend: Fix display of error message when AWS credentials are invalid

---

platforms/vmware/provider.tf

The latest version 0.4.2 is causing mysterious errors - like preventing
the CA cert from being generated on self-signed installs.  Reverting
until the new version can be properly tested.

platform/vmware: Revert vsphere provider version to 0.2.2

---

modules/ignition/resources/services/kubelet.service

Picked up from https://github.com/coreos/bugs/issues/2074
Need to add a wants here so that using nfs persistent volumes work as
internded on tectonic.
Without this change you see an error like:
```
Mounting arguments: 192.168.1.2:/mnt/user/tectonic /var/lib/kubelet/pods/6961c181-9d79-11e7-abdc-005056a6ea29/volumes/kubernetes.io~nfs/nfs nfs []
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```
(In case you don't have permissions to add labels, please ask …

Adds `Wants=rpc-statd.service` to kubelet (#1943)

---

config.tf

The new tco will remove any TPRs when upgrade across the 1.8 boundry.

config.tf: Bump TCO to 0.6.1

---

tests/smoke/aws/vars/aws-vpc-internal.tfvars.json

This var doesn't appear to do anything.

tests: Remove unused tectonic_aws_az_count var from smoke test input

---

installer/frontend/cluster-config.js
installer/frontend/components/aws-vpc.jsx

Because of the way we validate all field when the page is reloaded, it's
possible to end up calling `getZoneDomain()` when the platform is bare
metal, but this is harmless so let's just remove the exception.
Also rename to `getAwsZoneDomain()` to show it is AWS specific.

frontend: Remove unneeded exception when getting AWS hosted zone domain

---

installer/frontend/components/tf-poweron.jsx

Normally we expect to only have an `apply` or `destroy` action in progress, that is not actually true 100% of the time.

frontend: Fix TF action title when action is neither apply nor destroy

---

images/tectonic-builder/Dockerfile

this fixes a change introduced in this PR: https://github.com/coreos/tectonic-installer/pull/2537 which add the tectonic-installer repo inside the image.
Also, remove some layers and bump terraform to 0.11.1

tests/ci: fix dockerfile and remove some layers

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/bm-credentials.jsx
installer/frontend/components/bm-hostname.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/bm-sshkeys.jsx
installer/frontend/components/certificate-authority.jsx
installer/frontend/components/cluster-info.jsx
installer/frontend/components/etcd.jsx
installer/frontend/components/k8s-cidrs.jsx
installer/frontend/components/users.jsx

Generally, if the first field on a page is a `text` or `textarea` input, it should be focused.
- Add `autoFocus` to first input on Console Login page.
- Remove `autoFocus` from AWS VPC field that is actually half way down the page.
- Consistently use `autoFocus={true}` syntax rather than `autoFocus="true"` or just `autoFocus`.
cc @tlwu2013

frontend: Make autoFocus use more consistent

---

installer/frontend/__tests__/fields.js
installer/frontend/actions.js
installer/frontend/cluster-config.js
installer/frontend/components/aws-define-nodes.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js
installer/frontend/reducer.js
installer/frontend/utils.js

Big form code clean up, mostly related to field validation.
- Remove `asyncValidator()`, which was only used by the AWS VPC form, but added significant complexity to `form.js`. Instead modify the AWS VPC form's `validator()` function to handle the async API call.
- Remove `ignore` from Redux. Instead just re-evaluate whether a field should be ignored when necessary.
- Simplify `promisify()` and `Node.validate()`. This simplifies the logic following a field update, which triggers validation on that field and any dependent fields.
- Simplify `isNow` logic to only increment `this.clock` when a field update begins.
- Stop passing `oldData` and `oldCC` to field `validator()` functions.
- Change `isValid()` to allow empty values. If a field can't be empty, that should be enforced using the …

frontend: Major Form / Field clean up

---

installer/frontend/__tests__/examples/metal.json
installer/frontend/cluster-config.js
installer/frontend/ui-tests/output/metal.tfvars
installer/frontend/ui-tests/utils/terraformTfvars.js

We don't set this field for the bare metal, so it was always "".
This also means we no longer need to ignore `tectonic_dns_name` in the GUI tests.

frontend: Don't output tectonic_dns_name TF var for bare metal

---

installer/frontend/components/dry-run.jsx
installer/frontend/components/tf-poweron.jsx

Also capitalize "Assets" in button text.
This text was in the mocks (see https://github.com/coreos/tectonic-installer/issues/356#issuecomment-317838399), but seems to have been overlooked.

frontend: Add help text for Download Assets button

---

installer/frontend/ui-tests/tests/aws.js
installer/frontend/ui-tests/tests/metal.js
installer/frontend/ui-tests/utils/terraformTfvars.js

- Some tests don't output TF vars for smoke tests, so they don't need to ignore any TF vars.
- Some TF vars are specific to a single platform, so only the tests for that platform need to ignore them.

tests/frontend: Ignore fewer TF vars

---

installer/frontend/aws-actions.js
installer/frontend/reducer.js

If we already have subnet values, they should not be overwritten by default values.

frontend: Fix AWS VPC subnets resetting to defaults after page refresh

---

config.tf
modules/tectonic/resources/manifests/cluster-config.yaml

Have addon-operator track the cloud provider: CORS-389 
For future addition of adding a default storage class.
Related tectonic-operators PR: https://github.com/coreos-inc/tectonic-operators/pull/148

Added cloud provider to addon-operator config

---

Jenkinsfile
Makefile
tests/README.md
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/test_container.rb
tests/rspec/spec/spec_helper.rb

- Generalize conformance test container runner to run arbitrary images
- Add `RUN_COMPONENT_TESTS` Jenkins pipeline parameter and make RSpec
aware of option
- Add array to specify component test images
- Iterate over component test image array and generate rspec examples
(`it`)
Missing:
- Authentication to download component images from Quay
//CC @sudhaponnaganti @cpanato @Quentin-M (Please mind *work in progress* status, feel free to comment)

tests: Enable teams to run component tests via provided containers

---

config.tf

This bump the Tectonic Monitoring stack + Tectonic Prometheus Operator to `v1.9.0`.
@alexsomesan @s-urbaniak 
/cc @pst @sichvoge @ant31

*: bump Tectonic Monitoring to 1.9

---

tests/rspec/lib/test_container.rb

TestContainer'd better pull the component test image before running it.
Otherwise it could run a local out of date cache.
ref: https://github.com/coreos/tectonic-installer/pull/2490/files#r158543036

rspec/lib: pulls test image before running it

---

tests/rspec/lib/cluster.rb

When a timeout in RSpec happen during the bootstrap we now collect the logs to analyze later

tests: call forensic to collect the logs when timeout happen during start

---

examples/terraform.tfvars.govcloud
modules/dns/powerdns/variables.tf
platforms/govcloud/main.tf
platforms/govcloud/tectonic.tf
tests/rspec/lib/govcloud_vpc.rb

remove obsolete vanilla kubernetes and self hosted etcd variables from govcloud

remove vanilla kube and self hosted etcd from govcloud

---

config.tf

- console
- kvo
- kubernetes
- tectonic

config.tf: bump versions for 1.7.9-tectonic.4

---

tests/rspec/lib/cluster.rb

when using "command 1 | tee bla.log" if the command 1 fails it will return always 0 if tee did not fail. 
using -o pipefail will return the correct error code.
I observed some errors in the tests when the terraform fail but the execution continues. using this it will not continue and fail properly.

tests: set bash as shell and set -o pipefail to return the correct error code

---

installer/frontend/components/base.jsx
installer/frontend/components/dry-run.jsx
installer/frontend/components/tf-poweron.jsx
installer/frontend/trail.js

The Start Over button doesn't cancel any Terraform apply / destroy that is currently running, so hide it until the Terraform step completes.

frontend: Hide Start Over button until Terraform step completes

---

installer/frontend/trail.js

If a running install is detected when the app starts, then `clusterConfig`
won't be populated, so `clusterConfig[DRY_RUN]` will always be falsey.
Solve the problem by also checking the Terraform action type since a
`show` action indicates that it is a dry run install.

frontend: Fix detection of an in progress install in Trail logic

---

installer/frontend/components/aws-define-nodes.jsx
installer/frontend/components/bm-hostname.jsx
installer/frontend/components/bm-sshkeys.jsx

These are only useful if the `Form` can have validation errors separate
from the `Field` validation, so remove for forms that have no `Form` level
validators.

frontend: Remove unnecessary Errors tags

---

installer/frontend/components/base.jsx

This should no longer be true. If the user does enter a URL of an
existing page, they will be automatically redirected back to the correct
trail based on the Redux state.

frontend: Remove out of date comment

---

installer/frontend/__tests__/reducer.js
installer/frontend/reducer.js

This data should not be saved because when we restore state, we go
through all fields validating them and fetching any extra data anyway.
Also changed the state save / restore unit test to diff the state
objects themselves rather than JSON so that the property order doesn't
matter.

frontend: Filter out some Redux state when saving to sessionStorage

---

installer/frontend/reducer.js

This function was only used by the unit tests, but has little value because `DEFAULT_CLUSTER_CONFIG` now only contains a few values, and those will probably be removed in the future.

frontend: Remove filterClusterConfig()

---

images/tectonic-builder/Dockerfile

This bumps yarn and node version. When we merge this we will generate the new tectonic-builder docker image

tests: update yarn and node

---

modules/bootkube/resources/manifests/cluster-config.yaml

The operator that manages the control plane is going to be called the
KubeCoreOperator, not the KubeVersionOperator.

bootkube: change cluster config component name.

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Remove the 'baremetal-smoke-test-logs' argument, because this makes no sense. The logic of the script stays the same, so we can just use the smoke-test-logs argument.

tests: optimize logstash upload script

---

tests/smoke/aws/vars/aws.tfvars.json

@arithx is using the Tectonic installer to test nightly Container Linux
AMIs. They are only present in `us-west-2`.
Terraform lets values in the tfvars file take precedence over
environment variables. To easily configure the regoin for the aws basic
tests, this patch removes the specification. The other smoke test tfvars
files don't have a region specified.
@cpanato @alexsomesan @squat Do you know of a particular reason, why the region is specified here?

Remove region specification in aws basic smoke test

---

installer/frontend/ui-tests/tests/aws.js

We remove the harcoded aws region from the tfvars used in one of our tests. however the UI tests check the aws region, and now it is not there. This PR remove the check against aws region

tests: ignore was region in the UI tests

---

installer/frontend/cluster-config.js
installer/frontend/components/tf-poweron.jsx

This happens if the app detects that an installation is already in progress and jumps to the Start Installation page.
Hide the Terraform actions menu and the Tectonic domain since they will not work without the cluster state data. The UI will still allow you to download assets to destroy the cluster manually.

frontend: Handle case where cluster state data is not populated

---

installer/frontend/app.jsx
installer/frontend/components/base.jsx
installer/frontend/trail.js

Combine some navigation logic that was split between `Trail`, `app.jsx` and `Base`.
- Refactor away `Trail.canNavigateForward()` method.
- Merge `fixLocation()` and `fixPath()` and move to `Base`.
- Remove unused `Trail.cmp()` method.
- Remove unnecessary `Trail.navigable()` method. This was only used by the sidebar and the sidebar should be able to assume that all pages in the current `Trail` section are navigable.

frontend: Combine some navigation logic

---

installer/frontend/components/dry-run.jsx
installer/frontend/components/success.jsx
installer/frontend/components/tf-poweron.jsx

Chrome was already defaulting to `assets.zip`, but Firefox was defaulting to just `assets`.

frontend: Set the default assets download filename to "assets.zip"

---

installer/frontend/app.jsx
installer/frontend/components/base.jsx
installer/frontend/trail.js

Fix `Page Navigation Next` Google Analytics event.
Clean up `Base`, `Wizard` and `NavSection`.
- Modify `Wizard` so we don't need the whole state object as a property.
- Remove `Wizard.navigate()` by moving the `history.push()` action to `NavSection` and moving the Google Analytics event to `app.jsx`.
- Remove unnecessary `withNav()` wrapper from `Wizard`.

frontend: Fix Google Analytics Next event and clean up Base / Wizard

---

modules/tectonic/assets.tf
modules/tectonic/resources/manifests/cluster-config.yaml
modules/tectonic/variables.tf
platforms/aws/tectonic.tf
platforms/azure/tectonic.tf
platforms/gcp/tectonic.tf
platforms/govcloud/tectonic.tf
platforms/metal/tectonic.tf
platforms/openstack/neutron/main.tf
platforms/vmware/tectonic.tf

The tectonic-network-operator ended up in modules/bootkube, so remove
all irrelevant code from modules/tectonic.

modules/tectonic: clean up unused variables.

---

modules/aws/master-asg/master.tf
modules/aws/worker-asg/worker.tf
modules/govcloud/etcd/nodes.tf
modules/govcloud/master-asg/master.tf
modules/govcloud/worker-asg/worker.tf

Fixes: https://jira.coreos.com/browse/INST-773
If the end-user need ecr permission, he can create the role/policy and attach to in the bootstrap.

aws: remove ecr permissions

---

platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl

Looks like this variable was typo'd in the iscsi PR.

platforms/metal: fix iscsi variable in Matchbox templates

---

installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/nodes.jsx
installer/frontend/ui-tests/pages/nodesPage.js

Leave a limit of 100 in place just as a sanity check.
Also fixes bare metal to use the same limit as AWS (was 9 for metal and 10 for AWS).

frontend: Remove 10 master nodes limit

---

modules/bootkube/resources/manifests/tectonic-network-operator.yaml

When trying to deploy a single node cluster, bootkube hangs on trying to deploy the controller-manager and the scheduler as the single node is on "not ready" status because no network config. This allows the network operator to run on master, hence node gets "ready" status and the bootstrap process can move forward

Pin and add master toleration for tno

---

installer/frontend/components/cluster-info.jsx
installer/frontend/components/ui.jsx

Add a new component `FileInput` to extract out the file upload handler logic from `FileArea` and `cluster-info.jsx`.
Also clean up `FileArea` a bit.

frontend: Merge file upload handlers

---

installer/frontend/.babelrc
installer/frontend/package.json
installer/frontend/yarn.lock

Switch from `babel-preset-es2015` to `babel-preset-env`.
Sets the targeted browsers to `["defaults", "not ie < 11"]`. Currently that equates to:
```
"chrome": "62",
"android": "4.4.3",
"edge": "15",
"firefox": "52",
"ie": "11",
"ios": "10.3",
"safari": "10.1"
```
Upgrade browserify from 13.0.x to 15.2.x and a couple of other minor dependency upgrades.
cc @sym3tri

frontend: Switch to babel-preset-env and upgrade browserify to v15.2

---

installer/frontend/actions.js
installer/frontend/components/aws-cluster-info.jsx
installer/frontend/components/aws-tags.jsx
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js
installer/frontend/ui-tests/pages/clusterInfoPage.js

Add `FieldRowList` component, which replaces `ConnectedFieldList` and `InnerFieldList_` and also handles the add and remove buttons.
Greatly simplify `FieldList` class.
This makes the `autoFocus` behavior consistent for the 3 field lists (AWS Tags, BM master nodes, BM worker nodes).
Make `appendField` and `removeField` only available to field lists instead of to any component wrapped by `Connect` because they are only applicable to field lists.
Merge `TagsWithPlaceholder` functionality into `AWS_Tags`.
Also fixes the AWS tags validation:
- Fixes a bug where the `Tag keys must be unique` error was only displayed if the first tag row contained one of the duplicate values.
- Allow the `Both fields are required` error to be displayed on either the key input or the value input, rather than …

frontend: Clean up FieldList and fix AWS tags validation

---

modules/aws/master-asg/ignition_s3.tf
modules/aws/master-asg/variables.tf
modules/aws/worker-asg/ignition_s3.tf
modules/aws/worker-asg/variables.tf
modules/ignition/resources/services/kubelet.service
platforms/aws/main.tf

I was pulling the kubeconfig through s3 with a hacked domain into the ncg kubelet service.
Let's do this for now so we can collaborate.
This auth should be handled by TLS bootstrapping and bootstrap tokens eventually

Inject kubeconfig file from ignition

---

BUILD.bazel
WORKSPACE
installer/cmd/installer/BUILD.bazel

This commit adds tarball targets for Bazel.
We can now create tarballs using:
```sh
bazel build tarball
```
This will create a gzip compressed tarball named tectonic.tar.gz. The
contents of the tarball will be nested in a directory named `tectonic`.
To create a tarball with a version string in the directory name, we can
build the tarball using:
```sh
export VERSION=<some version>
bazel build tarball --action_env=VERSION
```
In this case, the file structure will be nested in a directory called
`tectonic_<some version>`.
This commit also makes the installer binaries pure go so that they are
statically linked, which is nicer for containers.
cc @alexsomesan

bazel: create tarball target

---

config.tf
modules/tectonic/assets.tf
modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml

This bumps Tectonic Monitoring to `v1.9.1`.
This is primarily important to land in track-1 for the Lithium release. For track-2 this can be handled next week.
@alexsomesan @sym3tri 
/cc @ant31 @pst @sichvoge

*: bump Tectonic Monitoring to v1.9.1

---

tests/README.md
tests/rspec/lib/cluster.rb
tests/rspec/lib/cluster_factory.rb
tests/rspec/lib/cluster_support.rb
tests/rspec/lib/shared_examples/k8s.rb
tests/rspec/lib/ssh.rb
tests/rspec/spec/existing_cluster_spec.rb

fixes: https://jira.coreos.com/browse/INST-520

tests: run tests on a running cluster

---

installer/frontend/actions.js
installer/frontend/reducer.js

This Redux action is now specifically for removing a row from a field
list, so rename it to make that clear.
Simplify the reducers by assuming they take a field list id and an
index, not an arbitrary path. Also stop clearing any associated error
data, since a `REMOVE_FIELD_LIST_ROW` action will need to trigger a
re-validation of the field list anyway.

frontend: Rename REMOVE_AT action to REMOVE_FIELD_LIST_ROW and simplify

---

installer/frontend/components/aws-vpc.jsx

This fixes a bug where the `Private Route 53 Zones must use an existing private VPC.` error was not cleared when switching to a valid hosted zone.
This approach should be less error prone and easier to maintain.

frontend: Fix AWS VPC skip validation optimization

---

tests/jenkins-jobs/scripts/log-analyzer-copy.sh

It happens sometimes that log files are extremely large, which causes Logstash to crash. This could happen due Jenkins failure, infinite loop or something else. A typical log files is less than a GB, so this PR adds this check. If the file is bigger, just remove it and continue.

tests: add max log file size (1GB) feature

---

installer/frontend/cluster-config.js

The TODO is unnecessary because `hostedZoneID` is actually included in the value of `tectonic_base_domain`.

frontend: Remove 3 unnecessary comments

---

config.tf

This updates tectonic-torcx container image to v0.2.1, which contains
a few bugfixes discovered by nightly tests.
Full changelog at https://github.com/coreos/tectonic-torcx/releases/tag/v0.2.1
Closes https://jira.coreos.com/browse/OST-139
Closes https://jira.coreos.com/browse/OST-140

config: update tectonic-torcx to v0.2.1

---

Jenkinsfile

These tests have failed on unrelated PRs. I am disabling them for now. I will try to debug the issue further tomorrow.

tests: Temporarily disable bazel tests

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/bootstrap-manifests/bootstrap-controller-manager.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml
modules/bootkube/resources/manifests/kube-controller-manager.yaml
modules/bootkube/resources/manifests/kube-proxy.yaml
modules/ignition/resources/services/k8s-node-bootstrap.service
modules/tectonic/resources/manifests/console/deployment.yaml
modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml

This PR changes the ca-certificates mounts for:
* k8s-node-bootstrap.service; and
* tectonic-channel-operator.yaml
Rather than rely on /usr/share/ca-certificates/ca-certificates.crt they
should be using /etc/ssl/certs/ca-certificates.crt since this will
actually include admin-installed certs.
Fixes: INST-886
cc @brianredbeard @coresolve @alexsomesan

modules: fix ca-certificates mount src

---

config.tf
modules/ignition/ca_certs.tf
platforms/metal/cl/bootkube-controller.yaml.tmpl
platforms/metal/cl/bootkube-worker.yaml.tmpl
platforms/metal/cl/custom-ca.yaml.tmpl
platforms/metal/matchers.tf
platforms/metal/profiles.tf

This commit un-bundles the custom CA certificates that are passed to the
Tectonic Installer. This is needed for OpenSSL certificate hashing to
work. Without this, CAs cannot be anchored. This commit adds an
intermediate templating step to the Matchbox profile generation where
custom CA certs are inserted. Because of the fact that the Tectonic
Installer modifies the `update-ca-certificates.service` unit via a
drop-in, certificates are rehashed on every reboot so the custom CA
certs are rehashed automatically and are avaiable on the first boot to
programs compiled against OpenSSL.
Fixes: INST-885
cc @brianredbeard @coresolve @alexsomesan @sym3tri 
Related: https://github.com/coreos/tectonic-installer/pull/2813, https://github.com/coreos/tectonic-installer/pull/2814

platforms/metal: unbundle custom certs

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-domain-validation.jsx
installer/frontend/components/aws-submit-keys.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/cluster-info.jsx
installer/frontend/components/cluster-type.jsx
installer/frontend/components/dry-run.jsx
installer/frontend/components/footer.jsx
installer/frontend/components/header.jsx
installer/frontend/components/nodes.jsx
installer/frontend/components/submit-definition.jsx
installer/frontend/components/ui.jsx
installer/frontend/platforms.js
installer/frontend/ui-tests/utils/wizard.js

Create `A` and `DocsA` components to wrap links in order to
- Send Google Analytics docs events for all docs links
- Stop littering the code with `eslint-disable-next-line react/jsx-no-target-blank` comments
- Make the `rel="noopener"` / `rel="noopener noreferrer"` attributes easier to get right
Also adds Nightwatch tests for the `rel` attributes, fixes the `rel` attribute of one header link and renames `Dropdown` to `MenuDropdown` and moves it to `header.jsx` because it is actually specific to the header menus.

frontend: Add Analytics events for all docs links, make target="_blank" links easier to maintain

---

installer/frontend/cluster-config.js
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/ui.jsx

It used to be that `AWS_CONTROLLER_SUBNETS` and `AWS_WORKER_SUBNETS` were
marked as dirty as soon as the Advanced Networking section was opened,
but that stopped being the case due to AWS VPC and forms changes. We
should therefore track the dirtiness of `AWS_ADVANCED_NETWORKING` itself
and use that to decide whether to output master and worker custom
subnet tfvars.

frontend: Output custom subnet tfvars if Advanced Networking is opened

---

installer/assets/frontend/css/styles.css
installer/frontend/cluster-config.js
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/nodes.jsx
installer/frontend/ui-tests/pages/etcdConnectionPage.js
installer/frontend/ui-tests/pages/nodesPage.js

Changes the etcd address input to assume a `https://` prefix and to just store the host address without a protocol in Redux.
Also changes the external etcd GUI tests to run for both AWS and metal (was just being run for metal).
--
cc: @sym3tri

frontend: Remove non-TLS etcd support from GUI

---

installer/frontend/components/cluster-type.jsx

When all supported platforms are disabled, default to the first enabled
(unsupported) platform. This fixes a bug where the Next button was
enabled even if both AWS and bare metal platforms were disabled.

frontend: Fix default platform when all supported platforms are disabled

---

installer/frontend/components/cluster-type.jsx
installer/frontend/platforms.js

Change `platformForm`'s validator error message to `'unused'` to make it more obvious that the message is not actually displayed.
Move `isEnabled` to `cluster-type.jsx`.

frontend: Small Platform field clean up

---

installer/pkg/terraform/executor.go

This function is unused and since it is specifically for loading tfvars
files, I don't think it will be needed in the foreseeable future.

frontend: Remove LoadVars function

---

Documentation/dev/frontend.md
installer/frontend/components/aws-submit-keys.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js

Switch single use of the old `AsyncSelect` to use `Selector` instead. Then rename `Selector` to `AsyncSelect`.

frontend: Remove old AsyncSelect component

---

modules/openstack/nodes/ignition.tf

@squat I don't have permission to set labels. Tested on OpenStack.

modules/openstack/nodes/ignition: Remove deprecated sshd option

---

Documentation/variables/govcloud.md
contrib/govcloud/vars.tf
examples/terraform.tfvars.govcloud
modules/dns/powerdns/records.tf
modules/dns/powerdns/variables.tf
platforms/govcloud/main.tf
platforms/govcloud/tectonic.tf
platforms/govcloud/tls.tf
platforms/govcloud/variables.tf
tests/rspec/lib/govcloud_vpc.rb

Move dns api key to a variable for govcloud https://github.com/coreos/tectonic-installer/pull/2834
Remove unnecessary ternaries https://github.com/coreos/tectonic-installer/pull/2838

move dns api key to a variable

---

Jenkinsfile
tests/rspec/lib/name_generator.rb

followup of: https://github.com/coreos/tectonic-installer/pull/2816
master will fail now because the env variable is not defined. was my fault. I thought we send logs only in the end. this fixes the issue.

tests: add logic to not fail when trying to send the logs to s3

---

installer/frontend/__tests__/examples/aws-custom-vpc-out.json
installer/frontend/__tests__/examples/aws-existing-vpc-out.json
installer/frontend/__tests__/examples/metal-out.json
installer/frontend/cluster-config.js

`clusterKind` was passed from the frontend to the backend, but the backend doesn't actually use it.

frontend: Remove unused clusterKind option

---

config.tf
modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

This release includes subscriptions (OCS Updating) and chargeback, as well as the latest versions of Vault, Etcd, and Prometheus OCS.

config.tf: Update tectonic-alm-operator to v0.3.0

---

installer/frontend/cluster-config.js

`getControllerDomain()` was only used by `toBaremetal_TF()`, so it's simpler to just use `cc[CONTROLLER_DOMAIN]`.

frontend: Remove getControllerDomain()

---

config.tf

module/tls creates certificates with invalid distinguishedName attributes for Subject and Issuer causing certificate validation issues.
Upstream Fix: terraform-provider-tls [#10](https://github.com/terraform-providers/terraform-provider-tls/pull/10)
Fixes: #2189
Verified Fix 2018-01-26
* Tectonic: 1.8.4-tectonic.2
* Terraform: v0.11.1
* Platforms: AWS, DigitalOcean
Thanks to @seslattery for helping debug, @SpencerBrown for the upstream
fix.

bump tls provider to 1.0.1 to fix ca cert subject

---

installer/frontend/components/make-node-form.jsx
installer/frontend/components/nodes.jsx

Fix nodes form error (currently just the `IOPS can't be larger than ### (50 IOPS/GiB)`) to use the form error style (`Alert`) instead of the field error style.
Also rename `toKey()` to `toId()` because we use "id" to refer to field IDs everywhere else and rename a couple of variables too.

frontend: Fix style of nodes form error

---

images/kubernetes-e2e/Dockerfile
images/tectonic-builder/Dockerfile
images/tectonic-installer/Dockerfile

Trying to get the master / 1.8.7 + release-automation repo Golangs in sync.
(This is for the Li release branch 1.8.7)
Ref: https://jira.coreos.com/browse/TECREL-156

Bumped Golang version to 1.9.2

---

platforms/metal/matchers.tf
platforms/metal/profiles.tf

The installer currently overrides the Matchbox profile and groups from previously installed clusters. This makes it difficult to use for multiple clusters and simultaneous installs impossible with the same Matchbox instance.
This change prefixes Matchbox profile and group names with the cluster name to support installing multiple clusters with the same Matchbox instance.
/cc @dghubble

Support multiple clusters per Matchbox

---

installer/frontend/yarn.lock

Regenerate yarn.lock to get latest package versions.
Top level package upgrades were:
```
chromedriver:        2.34.1 -> 2.35.0
eslint:              4.15.0 -> 4.17.0
eslint-plugin-react: 7.5.1  -> 7.6.1
jest-cli:            22.1.1 -> 22.1.4
watchify:            3.9.0  -> 3.10.0
```

frontend: Minor dependency upgrades

---

config.tf

This closes TECREL-160 (release blocker for Lithium).
@alexsomesan @cpanato @sym3tri 
@pst @fabxc @ant31 
@coresolve @justaugustus could you test to make sure the reported issue on your providers disappears? I tried on a new AWS cluster, there everything seems fine and in general the bug should be provider independant, but let's make double sure.

monitoring: Fix migration and insecure image org

---

modules/bootkube/resources/manifests/01-tectonic-namespace.yaml

NetworkPolicy can only select external namespaces by labels, not by name. So add a `name` label.

Add a simple label to the `tectonic-system` namespace for NetworkPolicy

---

BUILD.bazel
Documentation/dev/build.md
examples/BUILD.bazel
installer/cmd/installer/BUILD.bazel
tarball

Notable changes:
- bazel: add terraform examples to tarball
- installer: refactor so binaries do not have platform suffix
- tarball: add helper to build tarball with darwin bin
- Documentation: add docs for building with bazel
fixes: INST-747
cc @alexsomesan @mxinden

Bazel docs

---

installer/assets/frontend/css/styles.css

frontend: Remove CSS rule that actually makes vertical alignment worse

---

modules/bootkube/resources/bootkube.sh

In the case that bootkube is able to start between k8s-node-bootstrapper finishing and the machine going down for reboot, bootkube will create some static manifests in /etc/kubernetes/manifests then be interrupted and never bring up a full control plane. The existence of these manifests will prevent bootkube from running successfully on the next reboot due to errors like:
```
Feb 02 21:14:56 node001.metal.k8s.work systemd[1]: Stopped Bootstrap a Kubernetes cluster.
-- Reboot --
Feb 02 21:15:18 node001.metal.k8s.work systemd[1]: Starting Bootstrap a Kubernetes cluster...
Feb 02 21:15:25 node001.metal.k8s.work bash[5768]: Starting temporary bootstrap control plane...
Feb 02 21:15:25 node001.metal.k8s.work bash[5768]: Error: open /etc/kubernetes/manifests/bootstrap-apiserver.yaml: file …
```

Hack to allow interrupted bootkube to restart after torcx reboot

---

modules/bootkube/resources/bootstrap-manifests/bootstrap-apiserver.yaml
modules/bootkube/resources/manifests/kube-apiserver.yaml

Explicitly sets `--kubelet-preferred-address-types=InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP` on the apiserver.
This allows API --> kubelet communication to succeed in instances where a DNS search domain is not present in `/etc/resolv.conf`
Fixes: https://jira.coreos.com/browse/TECREL-150

Explicitly set `kubelet-preferred-address-types` flag for apiserver

---

platforms/vmware/tectonic.tf

Currently, the VMware platform uses a HostPort service for the tectonic
ingress controller which exposes port 443 on all worker nodes.  This
change will route https traffic to port 32000 for tectonic ingress.

platforms/vmware: Use NodePort for tectonic-lb service

---

installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/cluster-type.jsx
installer/frontend/components/dry-run.jsx
installer/frontend/components/success.jsx
installer/frontend/components/ui.jsx

Consistently use the external link icon for non coreos.com links and don't use it for coreos.com links. The only exception is the on the first wizard page (select platform page).
Add `ExternalLinkIcon` component.
cc @robszumski 
Before | After
--- | ---

frontend: Use external link icons more consistently

---

installer/frontend/ui-tests/utils/terraformTfvars.js

The next test was starting before the diff completed, which could cause the failure to go unreported if the diff was the final test step.

tests/frontend: Fix GUI tfvars test to wait until diff is complete

---

installer/frontend/components/submit-definition.jsx
installer/frontend/components/ui.jsx
installer/frontend/ui-tests/pages/defineMastersPage.js
installer/frontend/ui-tests/pages/defineWorkersPage.js
installer/frontend/ui-tests/pages/downloadAssetsPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/submitPage.js
installer/frontend/ui-tests/utils/terraformTfvars.js

Along with #2926, this removes the need for xpath selectors in Nightwatch.

tests/frontend: Add "id" attributes to simplify Nightwatch tests

---

.bazelrc
buildvars.sh
installer/api/BUILD.bazel
installer/api/api.go
installer/api/handlers_latest_release.go
installer/version/BUILD.bazel
installer/version/version.go

this will add a new endpoint `/releases/current` to the API
which will fetch TECTONIC_VERSION from the build environment
and displays the build time in a JSON format.

Installer API: Add buildTime and tectonicVersion

---

config.tf

Fixes an issue with error-server always responding with HTTP 200 codes.

config.tf: Update tectonic-error-server to 1.1

---

modules/bootkube/resources/manifests/02-ingress-namespace.yaml

The 'tectonic-ingress' namespace is needed for ingress operator.
/cc @diegs @abhinavdahiya

bootkube: Add ingress namespace creation.

---

CONTRIBUTING.md

As per https://github.com/coreos/docs/pull/1142, coreos golang code style has been removed from cores/docs. This PR rewrites the code style recommendation to link to the one maintained by the go community.

contributing: rewrite code style recommendation

---

platforms/azure/variables.tf

Set the default fault domain count for Germany
Although not documented in  https://docs.microsoft.com/en-us/azure/virtual-machines/windows/manage-availability, I faced the same problems as in #2211.
```
az account list-locations
[
{
"displayName": "Germany Central",
"id": "/subscriptions/xxxxxxxxx/locations/germanycentral",
"latitude": "50.117",
"longitude": "8.683",
"name": "germanycentral",
"subscriptionId": null
},
{
"displayName": "Germany Northeast",
"id": "/subscriptions/xxxxxxxxx/locations/germanynortheast",
"latitude": "51.333",
"longitude": "12.383",
"name": "germanynortheast",
"subscriptionId": null
}
]
```
Fixes #2211

Azure: add German locations to fault domain map

---

installer/api/handlers_aws.go
installer/assets/frontend/css/styles.css
installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/cidr.jsx
installer/frontend/components/ui.jsx
installer/pkg/aws/getters.go

For VPCs, add CIDR to dropdown labels and add CIDR tooltip with number of IP addresses and address range.
For subnets, add Name (from AWS tag) to dropdown labels and add CIDR tooltip with number IP addresses, address range and number of available addresses.
Change label format of both dropdowns to `<CIDR> (<NAME> | <ID>)`, which matches the format in AWS Console.
Change `Select` to accept an `options` array instead of an `availableValues` object.
Change `Deselect` to also output the field label, which makes things easier because the deselect checkbox is expected to be rendered alongside the label and it's easier to ensure they use matching `id` / `htmlFor` attributes if they are rendered together.
Rename `fieldName` to `deselectId` and change `CIDRRow` to take `deselectId` instead of a …

frontend: Add additional info for AWS VPCs and subnets

---

installer/cmd/tectonic/main.go
installer/pkg/tectonic/buildstate.go
installer/pkg/workflow/destroy.go
installer/pkg/workflow/install.go
installer/pkg/workflow/terraform.go
installer/pkg/workflow/utils.go
installer/pkg/workflow/workflow.go
installer/pkg/workflow/workflow_test.go

Add support for deploying using a cluster the cli:
`cli install --config=terraform.tfvariables`
cluster-name and platform are currently hardcoded

add multistep support for the cli - WIP - DO NOT MERGE

---

installer/api/api.go
installer/api/handlers_latest_release.go
installer/api/handlers_tectonic.go

This commit moves the `tectonicVersion and` `buildTime` build facts to `/tectonic/facts`.

Installer: Move tectonicVersion and buildTime to /tectonic/facts

---

config.tf
modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml

The alert manager ingress config expects both the host and the port.
Previously we only provided the host. This can break on some platforms
where the port is required to access Tectonic ingress.

modules/tectonic: fix alertmanager ingress config.

---

installer/assets/frontend/css/styles.css

Terraform log output area now uses the same font-family rule as the textarea inputs.
cc @robszumski, @tlwu2013 
Before | After
--- | ---

frontend: Use monospace font for Terraform log output

---

installer/frontend/app.jsx

This debug statement was being output regardless of whether the state was actually restored or not.

frontend: Fix state restore console.debug statement

---

config.tf
modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

0.3.1 contains fixes for CRD validation on k8s 1.9
The corresponding e2e test container for this release is here:  `quay.io/coreos/alm-e2e:v0.3.1`

Bump ALM to 0.3.1

---

steps/assets/ignition-bootstrap.tf
steps/assets/resources/rm-assets.sh

overwrite bootstrap ignition as part of rm-assets service

remove bootstrap ignition as part of rm-assets

---

Jenkinsfile

This patch archives the Tectonic installer build tarball from Bazel as a
Jenkins artifact to be consumed by e.g. the release automation pipeline.
@coverprice Would this be a possible solution for the release pipeline to consume build artefacts from the Tectonic installer pipeline? I would imagine a workflow like:
1. Release automation triggers Tectonic installer pipeline
2. Once Tectonic installer pipeline finishes and build result is green
- Retrieve tarball artefact from Tectonic installer build
- Release tarball artefact e.g. as a nightly
@cpanato This might result in a high number of tarballs, that we persist. The [`buildDiscarder`](https://github.com/coreos/tectonic-installer/blob/master/Jenkinsfile#L81) should take care of that, right?

tests: Archive tarball for release automation to consume

---

installer/frontend/components/base.jsx
installer/frontend/components/ui.jsx

Isolate the main wizard area so that an error leaves the header (including version info) and footer visible.
Isolate the header area so an error keeps the wizard functional.

frontend: Add React Error Boundaries to handle errors more gracefully

---

installer/pkg/config-generator/generator.go

This fills unpopulated core config fields

cli: populate core config

---

installer/pkg/terraform-generator/tectonic.go
installer/pkg/workflow/destroy.go
installer/pkg/workflow/install.go
installer/pkg/workflow/terraform.go
installer/pkg/workflow/utils.go

This change fixes destroy steps on incomplete builds. 
In cases where a user does a `tectonic install assets...` and then attempts a `tectonic destroy ...` the tool will fail with an error. The error is caused by the destroy operations that don't have a preceding initialized state. In this case, all destroy steps after `assets` don't have their modules and state initialized and will fail.
It also enables the CLI executable to determine its location and extrapolate the locations of other resources as per expected tarball layout.

Some CLI fixes

---

installer/assets/BUILD.bazel

Ensure that the frontend files generated by Bazel override any files
that may already exist in the `installer/assets` directory to ensure that
the final `bindata.go` contains the expected assets.
fixes: INST-939
cc @sym3tri @cpanato

installer: ensure reproducible build of bindata

---

installer/frontend/components/tf-poweron.jsx

The case where the app detects that an install is already in progress when the app loads is potentially confusing, so add a message to explain why it skipped to the Start Installation page.

frontend: Add message when in progress install is detected

---

installer/frontend/components/aws-vpc.jsx
installer/frontend/form.js

Instead validators that actually need to set `inFly` (currently just the AWS VPC validator) should do so themselves. This is much more efficient.

frontend: Remove inFly updates from validate()

---

installer/frontend/__tests__/examples/aws-custom-vpc-in.json
installer/frontend/__tests__/examples/aws-external-etcd-in.json
installer/frontend/__tests__/examples/aws-in.json
installer/frontend/ui-tests/output/aws-external-etcd.tfvars
installer/frontend/ui-tests/pages/certificateAuthorityPage.js
installer/frontend/ui-tests/pages/clusterInfoPage.js
installer/frontend/ui-tests/pages/consoleLoginPage.js
installer/frontend/ui-tests/pages/networkingPage.js
installer/frontend/ui-tests/pages/nodesPage.js
installer/frontend/ui-tests/tests/aws.js

Adds some AWS GUI checks not included in our other tests:
- External etcd input fields
- Custom CA input fields
- Variety of different valid input values for other fields

tests/frontend: Add AWS GUI test for external etcd and custom CA

---

installer/assets/frontend/css/styles.css
installer/frontend/.babelrc
installer/frontend/components/header.jsx
installer/frontend/package.json
installer/frontend/reducer.js
installer/frontend/server.js
installer/frontend/tectonic-ga.js
installer/frontend/utils.js
installer/frontend/yarn.lock

Fetch current version info from `/tectonic/facts` API endpoint instead of
using `babel-plugin-git-version`.
`isReleaseVersion()` (used to determine whether to send Google Analytics
events) will now return `true` if the value of `tectonicVersion` is a valid
semver string that doesn't contain the substring `-rc.`.
If `buildTime` is set, use it as the version info's `title` attribute.
Simplify `hasNewVersion()` by using the fact that our version strings are
now defined such that determining which is greater should just be a case
of comparing them lexicographically.
Slightly simplify version info CSS.
cc: @kalmog, @robszumski, @tlwu2013

frontend: Get current version info from /tectonic/facts

---

installer/frontend/actions.js

Remove pointless `splice()`. We don't use payload after this command, so
the only purpose of this would be to alter the passed in array, which is
not something we should be doing.
Remove unused return of `values`.

frontend: Clean up batchSetIn() action

---

modules/aws/master-asg/resources/init-assets.sh

If the assets zip is 0 bytes, then this means that the cluster already
bootstrapped once and the assets bundle was cleaned. In this case, exit
successfully so the kubelet will start and the cluster can be recovered
via bootkube.
Fixes: TECREL-187
cc @coresolve @coverprice @sym3tri

modules/aws: enable cluster recovery after cleanup

---

platforms/digitalocean/resources/do-puller.sh
platforms/digitalocean/resources/do-pusher.sh

Use the latest version of aknudsen/do-spaces-tool as it fixes a [critical bug](https://github.com/aknuds1/do-spaces-tool/issues/1), which makes cluster bootstrapping fail due to not being able to upload to the DigitalOcean bucket.

digitalocean: Upgrade do-spaces-tool

---

Jenkinsfile

To support Jenkinsfile development:
- Parameterize the slack channel that gets notified on failure.
- Check the is-enabled flag on every call to notifyBuildSlack, not just one of them.
- Remove notifyBuildSlack callsite param that was never used.

Parameterize Slack integration

---

installer/frontend/actions.js
installer/frontend/cluster-config.js

Steps towards the ultimate goal of removing `DEFAULT_CLUSTER_CONFIG`.
`__deleteEverything__()` is only used by the unit tests.

frontend: Remove some uses of DEFAULT_CLUSTER_CONFIG

---

installer/frontend/fields.js
installer/frontend/ui-tests/pages/clusterInfoPage.js

We don't allow lower case characters in the name, so change the validation error message to indicate that.
Before this change, the name `1a` would result in the error `Value must be a valid AWS Stack Name: [a-zA-Z][-a-zA-Z0-9]*`, which was confusing because we don't actually allow upper case characters.

frontend: Fix confusing Cluster Name validation error message

---

Jenkinsfile
images/tectonic-installer/Dockerfile

Previously the quay.io/coreos/tectonic-installer:master image contained
the entire Tectonic installer repository. Instead with this patch, only
the Tectonic tarball build by Bazel is added to the image on /tectonic.

Add tectonic tarball instead of repo to tectonic installer docker image

---

config.tf

This fixes TECREL-188
@pst @ant31 @fabxc 
/cc @sym3tri @cpanato @mxinden @sudhaponnaganti 
Note this is a preview, https://github.com/coreos-inc/tectonic-prometheus-operator/pull/173 still has to be merged first and the release has to be finished.

*: bump monitoring stack to 1.9.5

---

installer/frontend/__tests__/fields.js
installer/frontend/__tests__/protocols.js
installer/frontend/__tests__/reducer.js
installer/frontend/actions.js
installer/frontend/app.jsx
installer/frontend/aws-actions.js
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/ui.jsx
installer/frontend/form.js
installer/frontend/reducer.js
installer/frontend/server.js

Benefits
- Makes action dispatch consistent (was a mix of action creators, action dispatching "helpers" and using the action types directly)
- Moves complexity from reducers (which should be kept simple) to action creators
- Reduces boilerplate
Remove `configActionTypes.APPEND` and `configActionTypes.ADD_IN` reducers (logic moved to action creators).
Convert `configActionTypes.REMOVE_FIELD_LIST_ROW` action to a more generic
`configActionTypes.DELETE_IN` action and convert `dirtyActionTypes.CLEAN` to `dirtyActionTypes.DELETE_IN` to match.
Greatly simplify the `dirtyActionTypes.ADD` reducer by using Immutable.js.
Separate form actions out into `formActions`.
Make `extraData`, `inFly` and `refreshExtraData()` only available to components that need them (currently just `AsyncSelect`).

frontend: Use Redux action creators for all action types

---

README.md
contrib/tectonic-cli-examples/README.md

- Extend `### Hacking` session of root README.md
- Remove obsolete contrib/tectonic-cli-examples/README.md
//CC @spangenberg

Adjust documentation to Bazel and Tectonic cli

---

installer/frontend/reducer.js

This reducer is not supposed to be specifically for fields, so should not enforce this check. Also, we do an equivalent check in `formActions.updateField()`, which should be sufficient.

frontend: Remove field default check in configActionTypes.SET reducer

---

installer/frontend/components/nodes.jsx

This is a radio input with a default value, so the validator is redundant. We don't use validators like this for our other radio inputs.

frontend: Remove Etcd radio "required" validator

---

Jenkinsfile
tests/jenkins-jobs/scripts/log-analyzer-copy.sh

Log file uploader changes:
- consistently adds log filename (as field `logfile`). Prior to this, it was only adding the logfile name for `tap.log`.
- add the Jenkins job name as field `job`, so we can filter the Dashboards to only look at the production job. This is to support development on the Jenkins job itself; currently there is an instance of a similar job used to develop changes to the main Jenkins job, and we don't want output from that interfering with the dashboards.
- Refactored the log file script itself. (This wasn't necessary, but it will make future changes easier) Changes include: Docs, usage, more checks & validation, a "dry run" option, and use of modern Bash features. (I didn't feel POSIX compliance was important, but let me know if you feel otherwise).

Log file uploader adds Jenkins job & logfile name to metadata

---

Jenkinsfile
tests/jenkins-jobs/scripts/report-status-to-github.sh
tests/jenkins-jobs/tectonic_builder_docker_image.groovy
tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy
tests/jenkins-jobs/tectonic_smoke_test_docker_image_job.groovy

This is to support making changes to the Jenkinsfile safely from another repo, and in future from another Jenkins instance.
Of note, the .trim() line was added because the "originalCommitId" had a hidden trailing newline.

Parameterize github repository in Jenkinsfile

---

modules/container_linux/main.tf
modules/container_linux/outputs.tf

Due to the way Terraform ternary expressions are evaluated, even if you
specify a Container Linux version to install, Terraform will invoke the
container_linux module external data source and try to run `curl` and
make an HTTP request. If the host is offline or does not have `curl`
installed, then this module will fail. This commit enables this module
to be circumvented by explicitly defining the Container Linux version to
install. Furthermore, this enables non-unix hosts to use the module.
Due to Terraform's limited support for maps, there is no way to interpolate
a list of maps using `join`, `element`, `merge`, etc. This approach serializes
the maps and extracts the version using the known format of the map.
cc @mxinden @enxebre

modules/container_linux: avoid shell

---

Documentation/dev/frontend.md

This note is no longer true since #3019 was merged.

docs/frontend: Remove out of date note about Redux actions

---

installer/frontend/__tests__/fields.js
installer/frontend/actions.js
installer/frontend/cluster-config.js
installer/frontend/components/aws-cloud-credentials.jsx
installer/frontend/components/aws-submit-keys.jsx
installer/frontend/components/aws-tags.jsx
installer/frontend/components/aws-vpc.jsx
installer/frontend/components/bm-credentials.jsx
installer/frontend/components/bm-hostname.jsx
installer/frontend/components/bm-matchbox.jsx
installer/frontend/components/bm-nodeforms.jsx
installer/frontend/components/bm-sshkeys.jsx
installer/frontend/components/certificate-authority.jsx
installer/frontend/components/cluster-info.jsx
installer/frontend/components/nodes.jsx
installer/frontend/components/users.jsx
installer/frontend/fields.js
installer/frontend/form.js
installer/frontend/reducer.js

Rename `DEFAULT_CLUSTER_CONFIG` to `FIELD_DEFAULTS`, which is now only used for storing `default` values passed to `new Field`.
Make `default` optional for `Field`.
Remove `__deleteEverything__` action and move that logic to the unit tests because it is specifically for the unit tests.

frontend: Change DEFAULT_CLUSTER_CONFIG  to FIELD_DEFAULTS and make Field's default optional

---

Jenkinsfile

With the new Tectonic cli flow, the cluster `build` folder does not
exist anymore. Instead the cli creates a folder on the top level with
the name of the cluster, containing all relevant files.
For now we need to support both flows. For AWS the Tectonic CLI is used.
For Azure and all other platforms we still use plain terraform.

tests: Adjust log archive step to new cli folder structure

---

README.md
installer/cmd/tectonic/main.go
tests/rspec/lib/aws_cluster.rb

Standardize the arguments for the CLI.
All commands should either accept a `--dir` flag or a `<dir>` argument; we must pick one.
cc @alexsomesan @mxinden

installer,tests: standardize CLI flags

---

Jenkinsfile

To prevent issues via malformed user input, interpolate the shell
commands via bash env variables [1], instead of groovy string interpolation.
An alternative via a Groovy function was suggested by @coverprice [2]:
```
def shellEscape(s) {
'\'' + s.replace('\'', '\'\\\'\'') + '\''
}
originalCommitId = sh(returnStdout: true, script: "git rev-parse " +
shellEscape(params.SPECIFIC_GIT_COMMIT)).trim()
```
Both seem to be valid options. I suggest the solution via basic bash
primitives, for its simplicity.
[1] See https://stackoverflow.com/a/4273137/4011134
[2]
https://github.com/coreos/tectonic-installer/pull/3061#discussion_r171965414
@coverprice What do you think?
Thanks @lucab for the bash security 101!

tests: Sanitize user input via Jenkins parameters

---

installer/frontend/aws-actions.js
installer/frontend/ui-tests/output/aws-custom-vpc.tfvars
installer/frontend/ui-tests/output/aws-external-etcd.tfvars

Change the action to always overwrite the AWS subnets so that the subnet keys (which include the AWS AZs) are updated when the AWS region is changed.
The bug was introduced by #2620, so this PR partially reverts #2620. Unfortunately, this brings back the original bug where any user entered subnet CIDRs are overwritten if the page is refreshed. Fixing that will require a larger code change.

frontend: Fix AWS custom subnet validation bug when AWS region changes

---

BUILD.bazel
examples/BUILD.bazel

As long as we are not auto-generating the Tectonic CLI cluster
configuration examples, add the existing manually created ones to the
tarball.

Add Tectonic CLI cluster configuration examples to tarball

---

installer/BUILD.bazel
installer/pkg/validate/BUILD.bazel
installer/pkg/validate/validate.go
installer/pkg/validate/validate_test.go

Based on the frontend validators from [frontend/validate.js](https://github.com/coreos/tectonic-installer/blob/master/installer/frontend/validate.js) and [frontend/fields.js](https://github.com/coreos/tectonic-installer/blob/master/installer/frontend/fields.js).

Add validate Go package

---

installer/api/handlers_tectonic.go

(PR for `track-1` branch)
Change log messages output when the license and pull secret files are not found:
- Instead of WARNING level, output as INFO level (not visible in terminal with default logging level)
- Include the expected filenames, not just the expected directory
cc: @sym3tri, @aaronlevy

installer: For missing license / pull secret, log as INFO with filenames

---

installer/pkg/config/validate_test.go

@enxebre sorry I just realized you pointed out a commented code that was leftover from the nodepools PR.
PTAL

installer/tests: remove leftover commented test

---

tests/rspec/lib/aws_cluster.rb

Instead of logging the terraform output to Jenkins output by default,
only do so on failures. The successful logs will still be captured in
the log files, which are both archived on Jenkins as well as send to
Elastic search.
@cpanato what do you think?

tests: Print tf logs only on failure

---

tests/rspec/lib/aws_cluster.rb
tests/rspec/lib/cluster.rb

Instead of returning a boolean as a success feedback, raise an error.
This seems to be the idiomatic way for both the framework as well as
Ruby.

tests: Raise error on failed tectonic / terraform command

---

.gitignore
README.md

Document how to build the repo using docker so that you do not need to install bazel to get started. This method has the benefit of caching build artifacts so subsequent invocations are faster.
cc @mxinden @spangenberg @sym3tri

README: add instructions to build using Docker

---

modules/bootkube-ut2/assets.tf
modules/bootkube-ut2/resources/kubeconfig
modules/bootkube-ut2/resources/kubeconfig-kubelet
modules/tls/ca/self-signed/main.tf
modules/tls/ca/user-provided/assets.tf
modules/tls/ca/user-provided/outputs.tf
modules/tls/ca/user-provided/variables.tf

Fixes that were missed in #2972
* bootkube-ut2: update trust in kubeconfigs to root-ca
* tls: update user-provided variables and outputs
* also fix the duplicated organization for root-ca.

Fixes that were missed in #2972

---

Jenkinsfile
tests/smoke/aws/vars/aws-basic.yaml

tests: add master and worker role

---

installer/pkg/workflow/BUILD.bazel
installer/pkg/workflow/executor.go
installer/pkg/workflow/terraform.go
tests/rspec/spec/spec_helper.rb

This PR resolves an issue whereby the tectonic binary didn't necessarily use the packages terraform binary

Cli: get terraform binary from inside the package

---

installer/README.md

Updates the `installer/README.md` example of invoking gazelle, such that it can be run from inside the installer directory.
@yifan-gu also found that:
- 2 customized `BAZEL.build` files with `# gazelle:ignore` directives are removed by the `glide install -v` step, and must be restored with `git checkout ...` before running `bazel run //:gazelle`. Otherwise Gazelle will regenerate BUILD.bazel files for them that won't work.
- Remove the `glide.lock` is necessary before running `glide install -v`, otherwise the lock file won't be updated.

Correct bazel invocation example

---

contrib/internal-cluster/vpn.tf
modules/ignition/etcd.tf

Cherry-pick from track-1 PR (#3153)
Forces TLS client auth for etcd.
Fixes: https://jira.coreos.com/browse/INST-1026

modules: force etcd TLS client auth

---

config.tf

This bumps just hyperkube. Console + KVO changes will follow in separate PRs.

Bump hyperkube to 1.9.6_coreos.0

---

installer/pkg/config/cluster.go
installer/pkg/workflow/destroy.go
installer/pkg/workflow/fixtures/terraform.tfvars
installer/pkg/workflow/install.go
installer/pkg/workflow/utils.go

This lays the groundwork for per-platform steps.
If step FOO is desired, prefer `steps/FOO/aws`, but fall back to `steps/FOO` if missing.

cli: plumb-through per-platform steps

---

Jenkinsfile
images/kubernetes-e2e/Dockerfile
images/kubernetes-e2e/build.sh

Bump track-1 K8s conformance tests to 1.9.6, and adds a script to build + tag it.

Bump track-1 K8s conformance tests to 1.9.6

---

config.tf

This version of console has all the styling cleanup, bug fixes, and k8s 1.9 compatibility changes that we want.

Bump Tectonic Console to v6.0.1.

---

config.tf

A few bug fixes and style tweaks.

Bump Tectonic Console to v6.0.4.

---

config.tf

Bump Tectonic Console to v6.0.5 for 1.9.6.

---

.bazelrc

This change is needed to build with Bazel versions 0.12.x and beyond.
The reason is that Bazel seems to have introduced a change in the way paths in .bazelrc are evaluated.

Fix paths in .bazelrc for Bazel >0.12.x

---

installer/pkg/config/aws/aws.go

Fixing some type definition.
Ref: https://jira.coreos.com/browse/INST-1029

installer: Fix the plural definition of the aws struct.

---

modules/ignition/resources/services/rm-assets.service

This PR eliminates a race where sometimes the /opt/tectonic cleanup occurred before the bootkube and tectonic services had finished, causing bootstrapping to fail. This PR reverts a change from b2e0bcf2f26141706cbf96e508afd14ee351af7c to ensure correctness since the rm-assets service once again depends on bootkube and tectonic.
Without this change, sometimes the bootstrap node will fail to bootstrap the cluster and no containers will  run.
cc @enxebre @yifan-gu

modules: eliminate bootstrap cleanup race

---

config.tf

Using the image built from https://github.com/coreos-inc/tectonic-operators/tree/master/operator/channel

config.tf: Bump tco.

---

config.tf

This release adds support for 1.9 and improves console integration. It also contains a new release of etcd-operator.
I haven't been able to run our full integration tests on 1.9 yet due to an odd issue with etcd init containers, but we have made several updates to support 1.9

bump alm to 0.4.0

---

modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

This fixes tectonic-alm-operator crashlooping

tectonic-alm-operator: update deployment for newer x-operator base image

---

modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

Since TCO is using 2-way merge for the containers in the manifest,
using `args` alone will not remove the old deployment's `command`,
thus new deployment spec end up with both `command` and `args`,
which will causes error during the upgrade.

tectonic-alm-operator: Use command instead of args.

---

modules/azure/vnet/variables.tf
modules/dns/azure/variables.tf

Previously, Tectonic was failing to create DNS records and vnets if a
user passed in a resource ID that used a Resource Group name with
parentheses or periods. These are valid in a Resource Group
name according to the Azure naming conventions:
> Alphanumeric, underscore, parentheses, hyphen, and period (except at
end) [source](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#general)
This change loosens the capture group to include the allowed
punctuation.
Tested with Terraform 0.11.7
(In case you don't have permissions to add labels, please ask a …

fix: Loosen Tectonic's Azure Resource Group capture

---

Jenkinsfile
images/tectonic-builder/Dockerfile
images/tectonic-builder/Dockerfile.bazel

images: Pin bazel to specific version in docker image

---

Documentation/dev/libvirt-howto.md

Make the libvirt steps more explicit. They should be runnable from start-to-finish by newcomers to tectonic.

İmprove libvirt documentation

---

installer/pkg/config/aws/aws.go

False values for booleans are omitted when marshaling JSON in golang.
https://github.com/golang/go/issues/13284
fixes INST-1083

Remove public resources in private VPC deployment

---

installer/pkg/config/BUILD.bazel
installer/pkg/config/validate.go
installer/pkg/workflow/BUILD.bazel
installer/pkg/workflow/init.go
installer/pkg/workflow/utils.go

This commit adds cluster name validation and also ensures that running `tectonic init` performs config validation.
Fixes: INST-991
Should be merged AFTER #3233, as the first commit is just that PR
cc @enxebre @alexsomesan

 installer/pkg/config: validate cluster name

---

.bazelrc
.gitignore

Fix INST-1061.
Change bazel ouput to .build so bazel subsequent runs will ignore the hidden folder

Bazel output

---

Documentation/variables/aws.md
installer/pkg/config/aws/aws.go
steps/variables-aws.tf

Now that assets are no longer distributed using an assets bucket, we can
eliminate this option, which is not even used today.
Part of: INST-974

*: remove unused s3 bucket name option

---

README.md

This shouldn't cause any problems on systems without SELinux, but will allow to get rid of permission errors on systems like Fedora 28.
Currently command
```
docker run --rm -v $PWD:$PWD -w $PWD quay.io/coreos/tectonic-builder:bazel-v0.3 bazel --output_base=.cache build tarball
```
Causes errors similar to this one:
```
Error: Output base directory '/home/paulfantom/Development/CoreOS/tectonic-installer/.cache' could not be created: (error: 13): Permission denied
```

fix docs for containerized builds on systems with SELinux enabled

---

examples/tectonic.aws.yaml

Without this, tectonic.service on the master will fail due to kubectl
validation errors on rbac/binding-admin.yaml.
I wasted a pretty amazing amount of time due to this omission.

examples: add admin section to aws config

---

modules/ignition/resources/services/rm-assets.service

this PR fixes inst-1093 rm-assets service runs even after tectonic.service failed.

inst-1093: fix rm-assets race conditions

---

examples/tectonic.aws.yaml

Current example aws deployment expects 0 etcd nodes which causes failure to provision cluster. Change to 3, so it will work as expected.

expect 3 etcd nodes instead of 0

---

config.tf

This new version includes the removal of the following:
- coreos-metadata.service - This metadata from this service (typically
the public IP address) isn't actually used by etcd.
- k8s-node-bootstrap.yaml - This service used to be responsible for
installing the correct version of docker and kubelet. Now that
TNC exists, it can inject the correct versions directly.
- runtime-mappings.yaml - This was used by k8s-node-bootstrap as a
fallback for when it was unable to contact the cluster.

config.tf: bump node controller operator

---

Documentation/variables/aws.md
installer/pkg/config/aws/aws.go
installer/pkg/config/cluster.go
installer/pkg/config/types.go
installer/pkg/config/validate.go
installer/pkg/config/validate_test.go
installer/pkg/workflow/fixtures/terraform.tfvars
modules/aws/vpc/master-elb.tf
modules/dns/route53/tectonic.tf
modules/dns/route53/variables.tf
steps/masters/aws/main.tf
steps/topology/aws/main.tf
steps/variables-aws.tf
tests/smoke/aws/vars/aws-basic.tfvars.json
tests/smoke/aws/vars/aws-vpc-internal.tfvars.json

This commit merges two dependent configuration options,
tectonic_aws_private_endpoints and tectonic_aws_public_endpoints, into
one single option: tectonic_aws_endpoints. This ensures users cannot end
up with a cluster without entirely endpoints. This commit also adds
validation of the endpoints field to ensure it is one of the accepted
values.
Fixes: INST-924

*: collapse two endpoints booleans into one field

---

.travis.yml
examples/tectonic.libvirt.yaml

Run basic tests in travis-ci platform. This runs same tests as Jenkins instance in "basic" mode, adds 3 types of linters (terraform, yaml, go), and builds package.
This doesn't deploy anything to AWS so it is meant to be run on every PR.
Linters:
- `tflint` is used to lint terraform files in whole repository
- `yamllint` is used to lint every file in `examples` and `installer` directories and subdirectories. It is permissive about line length.
- `golint` recursively checks go files in `installer` directory. For now it is set to be in permissive mode (enforcing version is commented-out) due to some errors in [libvirt.go](installer/pkg/config/libvirt/libvirt.go) file.

add travis CI platform

---

examples/tectonic.libvirt.yaml
installer/pkg/config-generator/ignition.go
installer/pkg/config/cluster.go
installer/pkg/config/libvirt/libvirt.go
installer/pkg/config/validate.go
installer/pkg/config/validate_test.go
installer/pkg/validate/validate.go
installer/pkg/validate/validate_test.go
installer/pkg/workflow/fixtures/terraform.tfvars
modules/libvirt/volume/main.tf
modules/libvirt/volume/variables.tf
steps/topology/libvirt/main.tf
steps/variables-libvirt.tf

This commit adds validation for all libvirt fields. Additionally, it
moves the default values for these validated fields from Terraform to
Golang so that the defaults are handled consistently and we do not
accidentally omit configuration values by forgetting to plumb values
through Terraform.
Addresses: INST-1089
CC @enxebre @squeed 
We need to set up our libvirt smoke tests so we can properly test future changes like this.

installer: validate libvirt

---

Documentation/variables/config.md
examples/tectonic.aws.yaml
examples/tectonic.libvirt.yaml
installer/pkg/config-generator/fixtures/test-aws.yaml
installer/pkg/config/cluster.go
installer/pkg/workflow/fixtures/aws.basic.yaml
installer/pkg/workflow/fixtures/terraform.tfvars

This commit removes the tls validity period option from the yaml config.
This options is not used anywhere in terraform.
cc @trawler @spangenberg  @enxebre

*: remove tls_validity_period

---

installer/pkg/config/aws/aws.go

It seems that due to all of the rebasing of the cleanup and validation
changes, some fields we not properly merged. These two fields should be
eliminated. The are the last references to
`tectonic_aws_public_endpoints` and `tectonic_aws_private_endpoints` in
the repository.
cc @enxebre @trawler

installer/pkg/config/aws: fix merge

---

Documentation/dev/libvirt-howto.md

With the recent introduction of OpenShift components, the default
Container Linux image didn't have a large enough disk and was failing to
reliably boot clusters. The additional suggested 8GB was an arbitrary
choice on my part, but I figured most users could spare another 8GB.

docs: instruct libvirt users to expand OS image

---

images/tectonic-installer/Dockerfile.ci

The CI infra will use this as a shim for testing until we evolve the
installer image into a final form.
Hold briefly while I test the jobs on this.

Add a new CI Dockerfile for testing with CentOS and prow

---

modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml

Since TCO is using 2-way merge for the containers in the manifest,
using args alone will not remove the old deployment's command,
thus new deployment spec end up with both command and args,
which will causes error during the upgrade.

Cherry-pick of #3229 from 1.9.6 to track-1

---

examples/tectonic.aws.yaml
installer/pkg/config-generator/generator.go
installer/pkg/config-generator/ignition.go
installer/pkg/config/cluster.go
installer/pkg/workflow/fixtures/aws.basic.yaml
installer/pkg/workflow/fixtures/terraform.tfvars
installer/pkg/workflow/utils.go

This moves the validation of the platform up to the point of
unmarshalling, reducing the risk that a developer may end up with an
unexpected platform.

installer: clean up use of Platform type

---

Jenkinsfile

Currently docker container cannot be built since we are forcefully removing workspace before building container and Dockerfile cannot be found.
This PR causes to rely on cleaning workspace in post action only.
Most of the lines have indentation changed and only one line is removed.
This cannot be tested on any other branch than "master".

Clean workspace in post action only

---

Jenkinsfile

Fix Jenkis pipeline to enable nightly build on master branch.
This cannot be tested as PR, and will be tested manually via Jenkins Web interface with builds on master branch.

Fix nightly builds

---

tests/smoke/cluster_test.go

Increase timeout to 15 minutes

extend timeout of KillAPI test

---

modules/bootkube/resources/bootkube.service

bootkube.sh makes heavy use of docker but doesn't wait until it's ready.
This worked on Container Linux because docker was socket activated.
That's not the case on RHCOS right now, so we need to be explicit.

modules/bootkube: explicitly depend on docker
